// frameworks/angular/components/navigation/arena-breadcrumbs/ArenaBreadcrumbs.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { isArenaPrimaryActivation } from '../../../AnchorActivation';
import type { ArenaCrumb } from '../../../Api.generated';
import { arenaBreadcrumbsStyles } from './ArenaBreadcrumbs.variants';
import manifest from './ArenaBreadcrumbs.classes.generated';

@Component({
  selector: 'arena-breadcrumbs',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <nav [class]="styles().root()" [attr.data-arena-part]="parts.root" [attr.aria-label]="label()">
      @for (crumb of items(); track crumb.label; let last = $last) {
        @if (last) {
          <span [class]="styles().current()" [attr.data-arena-part]="parts.current" aria-current="page">{{ crumb.label }}</span>
        } @else {
          <a [class]="styles().crumb()" [attr.data-arena-part]="parts.crumb" [attr.href]="crumb.href ?? '#'" (click)="onCrumbClick(crumb, $event)">{{ crumb.label }}</a>
          <span [class]="styles().separator()" [attr.data-arena-part]="parts.separator" aria-hidden="true">{{ separator() }}</span>
        }
      }
    </nav>
  `,
})
export class ArenaBreadcrumbs {
  protected readonly parts = manifest.parts;

  /** Names this navigation landmark. Required, and guarded at runtime: nothing can derive it, and the constant "Breadcrumb" it used to hardcode made two trails on one page indistinguishable as landmarks while satisfying the requirement mechanically. Say which hierarchy this is a trail through: "Project navigation", never "Breadcrumb". */
  readonly ariaLabel = input.required<string>();
  /** The trail, root first. The last entry is the current location and is never a link. */
  readonly items = input.required<readonly ArenaCrumb[]>();
  /** Drawn between crumbs, never before the first. Arena draws it, in its own aria-hidden span. */
  readonly separator = input<string, string | undefined>('/', { transform: (value) => value ?? '/' });
  /** A non-current crumb was activated, carrying that crumb alone. The native MouseEvent is not forwarded, because a platform's own event type never travels in a payload; what the listener needs from it, the chance to route instead of navigating, arrives as behaviour rather than as data. Arena has already cancelled the anchor by the time this fires, so a listener routes and does not double-navigate. It fires for a primary click with no modifier and for Enter; ctrl-click, middle-click and open-in-new-tab are the browser's and fire nothing, so a consumer who wires no listener still has a working trail of real links. */
  readonly navigate = output<ArenaCrumb>();

  protected readonly label = computed(() => {
    const name = this.ariaLabel();
    if (name.trim() === '') {
      throw new Error('ArenaBreadcrumbs: `ariaLabel` is required, and names which hierarchy this trail runs through');
    }
    return name;
  });

  protected readonly styles = computed(() => arenaBreadcrumbsStyles());

  protected onCrumbClick(crumb: ArenaCrumb, event: MouseEvent): void {
    if (!isArenaPrimaryActivation(event)) return;
    event.preventDefault();
    this.navigate.emit(crumb);
  }
}

// frameworks/react/components/navigation/arena-breadcrumbs/ArenaBreadcrumbs.tsx
import React from 'react';

import { isArenaPrimaryActivation } from '../../../AnchorActivation.ts';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaBreadcrumbs.classes.generated.ts';
import type { ArenaCrumb } from '../../../Api.generated';

export type { ArenaCrumb };
export interface ArenaBreadcrumbsProps {

  /** Names this navigation landmark. Required, and guarded at runtime: nothing can derive it, and the constant "Breadcrumb" it used to hardcode made two trails on one page indistinguishable as landmarks while satisfying the requirement mechanically. Say which hierarchy this is a trail through: "Project navigation", never "Breadcrumb". */
  ariaLabel: string;

  /** The trail, root first. The last entry is the current location and is never a link. */
  items: readonly ArenaCrumb[];

  /** Drawn between crumbs, never before the first. Arena draws it, in its own aria-hidden span. */
  separator?: string;

  /** A non-current crumb was activated, carrying that crumb alone. The native MouseEvent is not forwarded, because a platform's own event type never travels in a payload; what the listener needs from it, the chance to route instead of navigating, arrives as behaviour rather than as data. Arena has already cancelled the anchor by the time this fires, so a listener routes and does not double-navigate. It fires for a primary click with no modifier and for Enter; ctrl-click, middle-click and open-in-new-tab are the browser's and fire nothing, so a consumer who wires no listener still has a working trail of real links. */
  onNavigate?: (crumb: ArenaCrumb) => void;
}


const breadcrumbStyles = arenaStyles(manifest);

export function ArenaBreadcrumbs({ items, ariaLabel, separator = '/', onNavigate }: ArenaBreadcrumbsProps) {
  if (!ariaLabel?.trim()) throw new Error('ArenaBreadcrumbs: `ariaLabel` is required');
  if (!items) throw new Error('ArenaBreadcrumbs: `items` is required');
  const styles = breadcrumbStyles();
  return (
    <nav aria-label={ariaLabel} className={styles.root()} data-arena-part={manifest.parts.root}>
      {items.map((it, i) => {
        const last = i === items.length - 1;
        return (
          <React.Fragment key={i}>
            {last ? (
              <span aria-current="page" className={styles.current()} data-arena-part={manifest.parts.current}>{it.label}</span>
            ) : (
              <a href={it.href || '#'}
                onClick={(e) => {
                  if (!isArenaPrimaryActivation(e)) return;
                  e.preventDefault();
                  onNavigate?.(it);
                }}
                className={styles.crumb()} data-arena-part={manifest.parts.crumb}>
                {it.label}
              </a>
            )}
            {!last && <span aria-hidden="true" className={styles.separator()} data-arena-part={manifest.parts.separator}>{separator}</span>}
          </React.Fragment>
        );
      })}
    </nav>
  );
}
