// frameworks/angular/components/feedback/arena-onboarding/ArenaOnboarding.ts
import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  ElementRef,
  afterRenderEffect,
  booleanAttribute,
  computed,
  inject,
  input,
  output,
  untracked,
  viewChild,
} from '@angular/core';
import { arenaOnboardingStyles } from './ArenaOnboarding.variants';
import manifest from './ArenaOnboarding.classes.generated';
import { type FocusTrapState, arenaHandleOpenTransition, arenaTrapTabKey } from '../../../FocusTrap';
import { onboardingWidth, onboardingHeightReserve, sp3, sp4 } from '../../../Tokens.generated';

const SSR_VIEWPORT_H = 900;
import type { ArenaOnboardingAnchor, ArenaOnboardingStep } from '../../../Api.generated';
import { ARENA_LOCALE } from '../../../ArenaLocale';
import { arenaPhrase } from '../../../Phrase';

@Component({
  selector: 'arena-onboarding',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.data-arena-part]': 'parts.root',
    '(click)': 'onScrimClick()',
    '(keydown)': 'onKeydown($event)',
  },
  template: `
    @if (visible()) {
      <div #panel [class]="styles().panel()" [attr.data-arena-part]="parts.panel" role="dialog" aria-modal="true" tabindex="-1"
           [attr.aria-label]="label()"
           (click)="$event.stopPropagation()"
           [style.top.px]="position()?.top" [style.left.px]="position()?.left">
        @if (step().eyebrow; as eyebrow) {
          <div [class]="styles().eyebrow()" [attr.data-arena-part]="parts.eyebrow">{{ eyebrow }}</div>
        }
        @if (step().title; as title) {
          <div [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ title }}</div>
        }
        @if (step().body; as body) {
          <div [class]="styles().body()" [attr.data-arena-part]="parts.body">{{ body }}</div>
        }
        <div [class]="styles().foot()" [attr.data-arena-part]="parts.foot">
          <div [class]="styles().dots()" [attr.data-arena-part]="parts.dots" [attr.aria-label]="progressName()">
            @for (dot of steps(); track $index) {
              <span [class]="styles().dot() + ' ' + ($index === index() ? styles().dotOn() : styles().dotOff())"
                    [attr.data-arena-part]="parts.dot"></span>
            }
          </div>
          @if (index() > 0) {
            <button type="button" [class]="styles().text()" [attr.data-arena-part]="parts.text" (click)="back.emit()">{{ locale.onboardingBack }}</button>
          }
          @if (!last()) {
            <button type="button" [class]="styles().text()" [attr.data-arena-part]="parts.text" (click)="skip.emit()">{{ locale.onboardingSkip }}</button>
          }
          <button type="button" [class]="styles().next()" [attr.data-arena-part]="parts.next" (click)="last() ? done.emit() : next.emit()">
            {{ last() ? locale.onboardingDone : locale.onboardingNext }}
          </button>
        </div>
      </div>
    }
  `,
})
export class ArenaOnboarding {
  protected readonly parts = manifest.parts;
  protected readonly locale = inject(ARENA_LOCALE);

  /** Whether the tour is shown. Closed renders nothing, scrim included. */
  readonly open = input.required<boolean, unknown>({ transform: booleanAttribute });
  /** The tour, in order. An empty tour renders nothing. */
  readonly steps = input.required<readonly ArenaOnboardingStep[]>();
  /** Which step is current. The host owns it and answers next/back. */
  readonly index = input<number, number | undefined>(0, { transform: (value) => value ?? 0 });
  /** Where to attach the coachmark, as the two viewport coordinates it positions from. Absent floats it bottom-right. */
  readonly anchor = input<ArenaOnboardingAnchor>();
  /** Next was activated on a step that is not the last. */
  readonly next = output<void>();
  /** Back was activated on a step that is not the first. */
  readonly back = output<void>();
  /** Skip was activated, or the scrim was clicked. */
  readonly skip = output<void>();
  /** The final step's confirming control was activated. */
  readonly done = output<void>();

  private readonly doc = inject(DOCUMENT);
  private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');

  protected readonly progressName = computed(() => arenaPhrase(this.locale.onboardingProgress, { current: this.index() + 1, total: this.steps().length }));
  protected readonly visible = computed(() => this.open() && this.steps().length > 0);
  protected readonly step = computed<ArenaOnboardingStep>(() => this.steps()[this.index()] ?? {});
  protected readonly last = computed(() => this.index() === this.steps().length - 1);

  protected readonly label = computed(() => {
    const current = this.step();
    return current.title ?? current.eyebrow ?? arenaPhrase(this.locale.onboardingStep, { current: this.index() + 1, total: this.steps().length });
  });

  protected readonly styles = computed(() => arenaOnboardingStyles({
    placement: this.anchor() ? 'anchored' : 'floating',
    open: this.open(),
  }));

  protected readonly position = computed(() => {
    const rect = this.anchor();
    if (!rect) return null;
    const view = this.doc.defaultView;
    const W = onboardingWidth;
    const EDGE = sp4;
    const top = Math.min(rect.bottom + sp3, (view?.innerHeight ?? SSR_VIEWPORT_H) - onboardingHeightReserve);
    const left = view ? Math.min(rect.left, view.innerWidth - W - EDGE) : rect.left;
    return { top, left: Math.max(EDGE, left) };
  });

  private readonly focusTrap: FocusTrapState = { wasOpen: false, restoreTo: null };

  constructor() {
    afterRenderEffect(() => {

      const isOpen = this.visible();
      untracked(() => {
        arenaHandleOpenTransition(this.focusTrap, isOpen, this.panel()?.nativeElement ?? null, this.doc.activeElement);
      });
    });
  }

  protected onScrimClick(): void {
    if (this.visible()) this.skip.emit();
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (!this.visible()) return;
    if (event.key === 'Escape') {
      event.preventDefault();
      this.skip.emit();
      return;
    }
    if (event.key === 'Tab') {
      const panel = this.panel()?.nativeElement;
      if (panel) arenaTrapTabKey(panel, event, this.doc.activeElement);
    }
  }
}

// frameworks/react/components/feedback/arena-onboarding/ArenaOnboarding.tsx
import React, { useRef } from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaOnboarding.classes.generated.ts';
import { onboardingWidth, onboardingHeightReserve, sp3, sp4 } from '../../../Tokens.generated.js';

const SSR_VIEWPORT_H = 900;
import { useArenaDialogModal } from '../../../UseDialogModal.ts';

import type { ArenaOnboardingStep, ArenaOnboardingAnchor } from '../../../Api.generated';
import { useArenaLocale } from '../../../ArenaLocale.ts';
import { arenaPhrase } from '../../../Phrase.ts';

export type { ArenaOnboardingStep };

export interface ArenaOnboardingProps {

  /** Whether the tour is shown. Closed renders nothing, scrim included. */
  open: boolean;

  /** The tour, in order. An empty tour renders nothing. */
  steps: readonly ArenaOnboardingStep[];

  /** Which step is current. The host owns it and answers next/back. */
  index?: number;

  /** Where to attach the coachmark, as the two viewport coordinates it positions from. Absent floats it bottom-right. */
  anchor?: ArenaOnboardingAnchor;

  /** Next was activated on a step that is not the last. */
  onNext?: () => void;

  /** Back was activated on a step that is not the first. */
  onBack?: () => void;

  /** Skip was activated, or the scrim was clicked. */
  onSkip?: () => void;

  /** The final step's confirming control was activated. */
  onDone?: () => void;
}


const arenaOnboardingStyles = arenaStyles(manifest);

export function ArenaOnboarding({ open, steps, index = 0, onNext, onBack, onSkip, onDone, anchor }: ArenaOnboardingProps) {
  const locale = useArenaLocale();
  if (open == null) throw new Error('ArenaOnboarding: `open` is required');
  if (steps == null) throw new Error('ArenaOnboarding: `steps` is required');

  const panelRef = useRef<HTMLDivElement | null>(null);
  const onKeyDown = useArenaDialogModal({ open, panelRef, onDismiss: onSkip });
  if (!open || !steps.length) return null;
  const step = steps[index] || {};
  const last = index === steps.length - 1;

  const label = step.title ?? step.eyebrow ?? arenaPhrase(locale.onboardingStep, { current: index + 1, total: steps.length });

  const W = onboardingWidth;
  const EDGE = sp4;

  let pos: React.CSSProperties | undefined;
  if (anchor) {

    const top = Math.min(anchor.bottom + sp3, (typeof window !== 'undefined' ? window.innerHeight : SSR_VIEWPORT_H) - onboardingHeightReserve);
    let left = anchor.left;
    if (typeof window !== 'undefined') left = Math.min(left, window.innerWidth - W - EDGE);
    pos = { top, left: Math.max(EDGE, left) };
  }

  const styles = arenaOnboardingStyles({ placement: anchor ? 'anchored' : 'floating', open: true });
  return (
    <div onClick={onSkip} className={styles.root()} data-arena-part={manifest.parts.root}>
      <div role="dialog" aria-modal="true" aria-label={label}
        ref={panelRef} tabIndex={-1} onKeyDown={onKeyDown} onClick={(e) => e.stopPropagation()}
        className={styles.panel()} data-arena-part={manifest.parts.panel} style={pos}>
        {step.eyebrow && <div className={styles.eyebrow()} data-arena-part={manifest.parts.eyebrow}>{step.eyebrow}</div>}
        {step.title && <div className={styles.title()} data-arena-part={manifest.parts.title}>{step.title}</div>}
        {step.body && <div className={styles.body()} data-arena-part={manifest.parts.body}>{step.body}</div>}
        <div className={styles.foot()} data-arena-part={manifest.parts.foot}>
          <div className={styles.dots()} data-arena-part={manifest.parts.dots} aria-label={arenaPhrase(locale.onboardingProgress, { current: index + 1, total: steps.length })}>
            {steps.map((_, i) => (
              <span key={i} className={`${styles.dot()} ${i === index ? styles.dotOn() : styles.dotOff()}`}
                data-arena-part={manifest.parts.dot} />
            ))}
          </div>
          {index > 0 && <button onClick={onBack} className={styles.text()} data-arena-part={manifest.parts.text}>{locale.onboardingBack}</button>}
          {!last && <button onClick={onSkip} className={styles.text()} data-arena-part={manifest.parts.text}>{locale.onboardingSkip}</button>}
          <button onClick={last ? onDone : onNext} className={styles.next()} data-arena-part={manifest.parts.next}>
            {last ? locale.onboardingDone : locale.onboardingNext}
          </button>
        </div>
      </div>
    </div>
  );
}
