// frameworks/angular/components/display/arena-table/ArenaTable.ts
import {
  ChangeDetectionStrategy, Component, ElementRef, afterRenderEffect, booleanAttribute, computed,
  contentChildren, effect, inject, input, output, untracked,
} from '@angular/core';
import type {
  ArenaSelectOption, ArenaTableColumn, ArenaTablePage, ArenaTablePageControl, ArenaTableSlice,
  ArenaTableSort, ArenaTableSortControl,
} from '../../../Api.generated';
import { arenaContainerWidth, arenaReadBreakpoint } from '../../../ContainerSize';
import { arenaWarnOnce } from '../../../WarnOnce';
import { ArenaPagination } from '../../navigation/arena-pagination/ArenaPagination';
import { ArenaSelect } from '../../forms/arena-select/ArenaSelect';
import { ArenaTableRow } from '../arena-table-row/ArenaTableRow';
import { ArenaTableState } from './ArenaTableState';
import { arenaTableStyles } from './ArenaTable.variants';
import manifest from './ArenaTable.classes.generated';
import { ARENA_LOCALE } from '../../../ArenaLocale';

export function arenaSortOptionValue(column: number, direction: ArenaTableSort['direction']): string {
  return `${column}:${direction}`;
}

export function arenaParseSortOption(value: string): ArenaTableSort | null {
  const [column, direction] = value.split(':');
  const index = Number.parseInt(column ?? '', 10);
  if (!Number.isInteger(index) || (direction !== 'asc' && direction !== 'desc')) return null;
  return { column: index, direction };
}

@Component({
  selector: 'arena-table',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [ArenaTableState],
  imports: [ArenaPagination, ArenaSelect],
  host: { '[class]': 'styles().root()',
    '[attr.data-arena-part]': 'parts.root', },
  template: `
    @if (sortBar()) {
      <div [class]="styles().sortBar()" [attr.data-arena-part]="parts.sortBar">
        <div [class]="styles().sortField()" [attr.data-arena-part]="parts.sortField">
          <arena-select [label]="sortLabel" [options]="sortOptions()" [value]="sortValue()"
                        (change)="onSortPick($event)" />
        </div>
      </div>
    }
    <table [class]="styles().grid()" [attr.data-arena-part]="parts.grid" [attr.role]="gridRole()"
           [attr.aria-label]="gridName()" [attr.aria-rowcount]="rowCount()"
           (keydown)="onKeydown($event)">
      @if (!narrow() && !empty()) {
        <thead>
          <tr [class]="styles().headRow()" [attr.data-arena-part]="parts.headRow"
              [attr.aria-rowindex]="extent() ? 1 : null">
            @for (column of columns(); track $index; let i = $index) {
              <th scope="col" [class]="headerClass(column)" [attr.data-arena-part]="parts.th" [style.width]="column.width"
                  [attr.tabindex]="state.isStop(0, i) ? 0 : -1"
                  [attr.aria-sort]="sortStateOf(i)"
                  (focus)="moveTo(0, i)" (click)="onHeader(i)">{{ column.header }}@if (sortStateOf(i) !== null && sortStateOf(i) !== 'none') {
                <i [class]="styles().sortCaret() + ' ' + caretOf(i)" [attr.data-arena-part]="parts.sortCaret" aria-hidden="true"></i>
              }</th>
            }
          </tr>
        </thead>
      }
      <tbody [class]="styles().body()" [attr.data-arena-part]="parts.body" [attr.role]="groupRole()"><ng-content /></tbody>
    </table>
    @if (empty()) {
      <div [class]="styles().empty()" [attr.data-arena-part]="parts.empty"><ng-content select="[empty]">{{ locale.tableEmpty }}</ng-content></div>
    } @else if (pager(); as paging) {
      <div [class]="styles().pager()" [attr.data-arena-part]="parts.pager">
        <arena-pagination [page]="paging.index" [pageCount]="pageCount()"
                          [ariaLabel]="gridLabel()" (change)="pageChange.emit($event)" />
      </div>
    }
  `,
})
export class ArenaTable {
  protected readonly parts = manifest.parts;
  protected readonly locale = inject(ARENA_LOCALE);

  /** Names the grid for assistive technology. Required, and guarded at runtime: nothing can derive it; ArenaCalendar names its grid from the range it is showing, and a data table's subject is editorial. Say what the rows are, never "ArenaTable". */
  readonly label = input.required<string>();
  /** The columns, in order. A column heads and sets its cells; it never says what goes in them. */
  readonly columns = input.required<readonly ArenaTableColumn[]>();
  /** ArenaCard mode below --bp-md. Set false only when the columns are meaningless apart. */
  readonly responsive = input(true, { transform: booleanAttribute });
  /** Which column the rows are ordered by and which way. Controlled: ArenaTable draws the caret and the aria-sort, and the consumer does the ordering, because ArenaTable does not hold the rows. Absent, no header is a sort target. */
  readonly sort = input<ArenaTableSort>();
  /** How the sort affordance is reached in CARD MODE, where there is no header row to activate and a `sortable` column therefore has no control under it at all. 'auto' draws one compact select above the cards, listing every sortable column in each direction, which is the shape a phone has room for; 'none' leaves card mode unsorted by hand, for a table whose order is the document's rather than the reader's. Above --bp-md the header row is the control and this member draws nothing. The header row does NOT come back below the breakpoint, because card mode exists for the one reason a grid does not fit. It is a member rather than something a consumer draws for themselves because the state it edits, ArenaTableSort, is Arena's: left to each consumer, the label, the option order and the way a direction is worded are invented once per project over a model they did not define. */
  readonly sortControl = input<ArenaTableSortControl, ArenaTableSortControl | undefined>(
    'auto',
    { transform: (value) => value ?? 'auto' },
  );
  /** Which page of a longer list is on screen. Present, ArenaTable draws its own ArenaPagination below the grid and names it from `label`, which is what gives that required name its uniqueness on a page with two paged tables. Absent, no pager is drawn and the projected rows are the whole list. */
  readonly page = input<ArenaTablePage>();
  /** Where the projected rows sit inside a longer list, which is what `aria-rowcount` and `aria-rowindex` carry on the grid. Absent with `page` bound, both are derived from the page, so a paged table needs nothing here. Bind it when the projection is not a page: a window a scroller renders, an infinite list that grows, or a page inside which you render less again. It is a separate member from `page` because the two answer separate questions, the same split `page` and `pageControl` make: `page` is the model the pager draws, and this is where the rows in the DOM sit in the list they came from. Bound together, this one answers the two attributes whole rather than composing with the page, because a reader is told one position and two sources for it is how they disagree. */
  readonly slice = input<ArenaTableSlice>();
  /** Whether ArenaTable draws the pager below the grid. 'auto' draws it whenever `page` is bound, which is what a table showing one list of its own wants; 'none' draws nothing and leaves the consumer to place an ArenaPagination themselves, over this table or over two of them at once. It is a separate member from `page` because the two are separate facts: `page` is what the table KNOWS about a longer list, and this is what it DRAWS about it. Bound together, a consumer who wanted the control elsewhere had to withhold `page` and leave the table knowing nothing about paging at all, which is a member deliberately unbound and a comment explaining why. The same split, and the same reasoning, as `sort` and `sortControl`. */
  readonly pageControl = input<ArenaTablePageControl, ArenaTablePageControl | undefined>(
    'auto',
    { transform: (value) => value ?? 'auto' },
  );
  /** A sortable header was activated, carrying the column and the direction it should become: the same column flips, a different one starts ascending. ArenaTable never reorders anything itself, so a consumer who ignores this event gets a caret that moves and rows that do not, which is why the member is controlled rather than a starting value. */
  readonly sortChange = output<ArenaTableSort>();
  /** A page was chosen, carrying the new 1-based page. It also fires with 1 when the current page has gone PAST THE END, which is the only reset ArenaTable performs; a filter that leaves the page in range is silent, so returning the reader to page one on a change of criterion stays the consumer's, beside the criterion they hold. */
  readonly pageChange = output<number>();

  protected readonly state = inject(ArenaTableState);

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly measured = arenaContainerWidth();
  private readonly medium = arenaReadBreakpoint('md');

  protected readonly rows = contentChildren(ArenaTableRow);

  protected readonly narrow = computed(() => {
    const width = this.measured();
    return this.responsive() && width !== null && width < this.medium;
  });

  protected readonly gridLabel = computed(() => {
    const name = this.label();
    if (name.trim() === '') {
      throw new Error('ArenaTable: `label` is required, and names what the rows are — never "ArenaTable"');
    }
    return name;
  });

  protected readonly empty = computed(() => this.rows().length === 0);

  protected readonly flat = computed(() => this.narrow() || this.empty());

  protected readonly gridRole = computed(() => (this.flat() ? 'presentation' : 'grid'));

  protected readonly groupRole = computed(() => (this.flat() ? 'presentation' : null));

  protected readonly gridName = computed(() => {
    if (this.empty()) return null;
    const name = this.gridLabel();
    return this.narrow() ? null : name;
  });

  protected readonly pager = computed(() => (this.pageControl() === 'none' ? undefined : this.page()));

  protected readonly extent = computed(() => {
    if (this.flat()) return null;
    const sits = this.slice();
    if (sits) return sits;
    const paging = this.page();
    return paging ? { total: paging.total, offset: (paging.index - 1) * paging.size } : null;
  });

  protected readonly rowCount = computed(() => {
    const sits = this.extent();
    if (sits === null) return null;
    return sits.total < 0 ? -1 : sits.total + 1;
  });

  protected readonly pageCount = computed(() => {
    const paging = this.page();
    if (!paging) return 1;
    return Math.max(1, Math.ceil(paging.total / Math.max(1, paging.size)));
  });

  protected readonly styles = computed(() => arenaTableStyles({ narrow: this.narrow() }));

  protected readonly sortLabel = 'Sort by';

  protected readonly sortable = computed(() => this.columns()
    .map((column, index) => ({ column, index }))
    .filter(({ column }) => column.sortable));

  protected readonly sortBar = computed(() => this.narrow() && !this.empty()
    && this.sortControl() !== 'none' && Boolean(this.sort()) && this.sortable().length > 0);

  protected readonly sortOptions = computed<ArenaSelectOption[]>(() => this.sortable().flatMap(
    ({ column, index }) => [
      { value: arenaSortOptionValue(index, 'asc'), label: `${column.header} \u2191` },
      { value: arenaSortOptionValue(index, 'desc'), label: `${column.header} \u2193` },
    ],
  ));

  protected readonly sortValue = computed(() => {
    const current = this.sort();
    return current ? arenaSortOptionValue(current.column, current.direction) : undefined;
  });

  protected onSortPick(value: string): void {
    const picked = arenaParseSortOption(value);
    if (picked) this.sortChange.emit(picked);
  }

  protected sortStateOf(column: number): string | null {
    if (!this.columns()[column]?.sortable || !this.sort()) return null;
    const current = this.sort();
    if (current?.column !== column) return 'none';
    return current.direction === 'asc' ? 'ascending' : 'descending';
  }

  protected caretOf(column: number): string {
    return this.sort()?.direction === 'asc' ? 'ph-bold ph-caret-up' : 'ph-bold ph-caret-down';
  }

  protected headerClass(column: ArenaTableColumn): string {
    const base = arenaTableStyles({ narrow: false, align: column.align ?? 'left' }).th();
    return column.sortable && this.sort() ? `${base} ${this.styles().thSortable()}` : base;
  }

  protected onHeader(column: number): void {
    if (!this.columns()[column]?.sortable) return;
    const current = this.sort();
    if (!current) return;
    this.sortChange.emit(current.column === column
      ? { column, direction: current.direction === 'asc' ? 'desc' : 'asc' }
      : { column, direction: 'asc' });
  }

  constructor() {
    this.state.columns = this.columns;
    this.state.narrow = this.narrow;
    this.state.rows = this.rows;
    this.state.extent = this.extent;

    effect(() => {
      const paging = this.page();
      const pages = this.pageCount();
      if (!paging || paging.index <= pages) return;
      untracked(() => this.pageChange.emit(1));
    });

    effect(() => {
      const current = this.sort();
      const columns = this.columns();
      if (!current) return;
      const column = columns[current.column];
      if (column?.sortable) return;
      const name = column ? `"${column.header}"` : 'no column at all';
      arenaWarnOnce(`ArenaTable "${untracked(() => this.label())}": sort.column ${current.column} is ${name},`
        + ' which does not declare `sortable`, so no header is a target and the caret is not drawn.'
        + ' ArenaTableSort.column is an INDEX, so moving a column reorders the rows in silence; keep the'
        + ' sort field inside the column entry it belongs to and the two move together.');
    });

    afterRenderEffect(() => {
      this.state.clamped();
      if (this.flat()) return;
      const grid = this.host.nativeElement.querySelector('table');
      if (!grid) return;
      const active = grid.ownerDocument.activeElement;
      if (!active || !grid.contains(active)) return;
      if (active.tagName !== 'TD' && active.tagName !== 'TH') return;
      const stop = grid.querySelector<HTMLElement>('td[tabindex="0"], th[tabindex="0"]');
      if (stop && stop !== active) stop.focus();
    });
  }

  protected moveTo(row: number, col: number): void {
    if (!this.state.isStop(row, col)) this.state.cursor.set({ row, col });
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (this.flat()) return;
    const target = event.target as Element | null;
    if (target?.tagName !== 'TD' && target?.tagName !== 'TH') return;

    const lengths = this.state.lengths();
    const at = this.state.clamped();
    let { row, col } = at;

    if (event.key === 'Enter' && at.row === 0) {
      event.preventDefault();
      this.onHeader(at.col);
      return;
    }
    if (event.key === ' ' && at.row === 0) {
      event.preventDefault();
      this.onHeader(at.col);
      return;
    }
    if (event.key === 'ArrowUp') row = Math.max(0, row - 1);
    else if (event.key === 'ArrowDown') row = Math.min(lengths.length - 1, row + 1);
    else if (event.key === 'ArrowLeft') col = Math.max(0, col - 1);
    else if (event.key === 'ArrowRight') col = Math.min(Math.max((lengths[row] ?? 1) - 1, 0), col + 1);
    else if (event.key === 'Home') col = 0;
    else if (event.key === 'End') col = Math.max((lengths[row] ?? 1) - 1, 0);
    else if (event.key === 'Enter') {
      event.preventDefault();
      if (at.row > 0) this.state.activate(at.row);
      return;
    } else return;

    col = Math.min(col, Math.max((lengths[row] ?? 1) - 1, 0));
    event.preventDefault();
    this.moveTo(row, col);
  }
}

// frameworks/react/components/display/arena-table/ArenaTable.tsx
import React, { useEffect, useRef, useState } from 'react';
import { arenaWarnOnce } from '../../../WarnOnce.ts';
import { useArenaContainerWidth, arenaReadBreakpoint } from '../../../UseArenaContainerWidth.ts';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaTable.classes.generated.ts';

import { ArenaPagination } from '../../navigation/arena-pagination/ArenaPagination.tsx';
import { ArenaSelect } from '../../forms/arena-select/ArenaSelect.tsx';
import type { ArenaTableRowProps } from '../arena-table-row/ArenaTableRow.tsx';

import type {
  ArenaSelectOption, ArenaTableColumn, ArenaTablePage, ArenaTablePageControl, ArenaTableSlice,
  ArenaTableSort, ArenaTableSortControl,
} from '../../../Api.generated';

export type { ArenaTableColumn };

export interface ArenaTableProps {

  /** Names the grid for assistive technology. Required, and guarded at runtime: nothing can derive it; ArenaCalendar names its grid from the range it is showing, and a data table's subject is editorial. Say what the rows are, never "ArenaTable". */
  label: string;

  /** The columns, in order. A column heads and sets its cells; it never says what goes in them. */
  columns: readonly ArenaTableColumn[];

  /** The rows. One ArenaTableRow per row. Where a row sits, the columns its cells are set against and how the keyboard reaches them are ArenaTable's to decide and no row's to declare; how that reaches a row is each layer's own idiom. */
  children?: React.ReactNode;

  /** What shows when no row is written. In that state NO grid is drawn at all, header row included: a column head over a "no results" sentence describes a table that is not there, and a role="grid" holding neither a header nor a row is a degenerate render, the same judgement ArenaTabs makes when it draws no panel for a tab that does not exist. Every layer falls back to the string 'No data.' when nothing is given, each in its own idiom for a default. Unlike ArenaTable.label this one IS derivable: 'No data.' states what happened rather than what the component is, which is the distinction that makes a fallback useful here and useless there. A consumer with a better sentence, what to do next or why the list is empty, projects it. */
  empty?: React.ReactNode;

  /** ArenaCard mode below --bp-md. Set false only when the columns are meaningless apart. */
  responsive?: boolean;

  /** Which column the rows are ordered by and which way. Controlled: ArenaTable draws the caret and the aria-sort, and the consumer does the ordering, because ArenaTable does not hold the rows. Absent, no header is a sort target. */
  sort?: ArenaTableSort;

  /** How the sort affordance is reached in CARD MODE, where there is no header row to activate and a `sortable` column therefore has no control under it at all. 'auto' draws one compact select above the cards, listing every sortable column in each direction, which is the shape a phone has room for; 'none' leaves card mode unsorted by hand, for a table whose order is the document's rather than the reader's. Above --bp-md the header row is the control and this member draws nothing. The header row does NOT come back below the breakpoint, because card mode exists for the one reason a grid does not fit. It is a member rather than something a consumer draws for themselves because the state it edits, ArenaTableSort, is Arena's: left to each consumer, the label, the option order and the way a direction is worded are invented once per project over a model they did not define. */
  sortControl?: ArenaTableSortControl;

  /** A sortable header was activated, carrying the column and the direction it should become: the same column flips, a different one starts ascending. ArenaTable never reorders anything itself, so a consumer who ignores this event gets a caret that moves and rows that do not, which is why the member is controlled rather than a starting value. */
  onSortChange?: (sort: ArenaTableSort) => void;

  /** Which page of a longer list is on screen. Present, ArenaTable draws its own ArenaPagination below the grid and names it from `label`, which is what gives that required name its uniqueness on a page with two paged tables. Absent, no pager is drawn and the projected rows are the whole list. */
  page?: ArenaTablePage;

  /** Whether ArenaTable draws the pager below the grid. 'auto' draws it whenever `page` is bound, which is what a table showing one list of its own wants; 'none' draws nothing and leaves the consumer to place an ArenaPagination themselves, over this table or over two of them at once. It is a separate member from `page` because the two are separate facts: `page` is what the table KNOWS about a longer list, and this is what it DRAWS about it. Bound together, a consumer who wanted the control elsewhere had to withhold `page` and leave the table knowing nothing about paging at all, which is a member deliberately unbound and a comment explaining why. The same split, and the same reasoning, as `sort` and `sortControl`. */
  pageControl?: ArenaTablePageControl;

  /** Where the projected rows sit inside a longer list, which is what `aria-rowcount` and `aria-rowindex` carry on the grid. Absent with `page` bound, both are derived from the page, so a paged table needs nothing here. Bind it when the projection is not a page: a window a scroller renders, an infinite list that grows, or a page inside which you render less again. It is a separate member from `page` because the two answer separate questions, the same split `page` and `pageControl` make: `page` is the model the pager draws, and this is where the rows in the DOM sit in the list they came from. Bound together, this one answers the two attributes whole rather than composing with the page, because a reader is told one position and two sources for it is how they disagree. */
  slice?: ArenaTableSlice;

  /** A page was chosen, carrying the new 1-based page. It also fires with 1 when the current page has gone PAST THE END, which is the only reset ArenaTable performs; a filter that leaves the page in range is silent, so returning the reader to page one on a change of criterion stays the consumer's, beside the criterion they hold. */
  onPageChange?: (page: number) => void;
}


export function arenaSortOptionValue(column: number, direction: ArenaTableSort['direction']): string {
  return `${column}:${direction}`;
}

export function arenaParseSortOption(value: string): ArenaTableSort | null {
  const [column, direction] = value.split(':');
  const index = Number.parseInt(column ?? '', 10);
  if (!Number.isInteger(index) || (direction !== 'asc' && direction !== 'desc')) return null;
  return { column: index, direction };
}

const arenaTableStyles = arenaStyles(manifest);

export function ArenaTable({
  columns, children, empty = 'No data.', responsive = true, label,
  sort, sortControl = 'auto', onSortChange, page, slice, pageControl = 'auto', onPageChange,
}: ArenaTableProps) {
  if (!label?.trim()) throw new Error('ArenaTable: `label` is required');
  if (columns == null) throw new Error('ArenaTable: `columns` is required');
  const [ref, width] = useArenaContainerWidth();

  const narrow = responsive && width !== null && width < arenaReadBreakpoint('md');

  const rowEls = React.Children.toArray(children);
  const bare = rowEls.length === 0;
  const flat = narrow || bare;

  const pageCount = page ? Math.max(1, Math.ceil(page.total / Math.max(1, page.size))) : 1;

  const extent = slice ?? (page ? { total: page.total, offset: (page.index - 1) * page.size } : null);
  const rowCount = extent === null ? undefined : extent.total < 0 ? -1 : extent.total + 1;

  useEffect(() => {
    if (page && page.index > pageCount) onPageChange?.(1);
  }, [page?.index, pageCount]);

  useEffect(() => {
    if (!sort) return;
    const column = columns[sort.column];
    if (column?.sortable) return;
    const name = column ? `"${column.header}"` : 'no column at all';
    arenaWarnOnce(`ArenaTable "${label}": sort.column ${sort.column} is ${name}, which does not declare`
      + ' `sortable`, so no header is a target and the caret is not drawn. ArenaTableSort.column is an'
      + ' INDEX, so moving a column reorders the rows in silence; keep the sort field inside the'
      + ' column entry it belongs to and the two move together.');
  }, [sort?.column, columns]);

  const sortStateOf = (index: number): 'ascending' | 'descending' | 'none' | undefined => {
    if (!columns[index]?.sortable || !sort) return undefined;
    if (sort.column !== index) return 'none';
    return sort.direction === 'asc' ? 'ascending' : 'descending';
  };

  const onHeaderActivate = (index: number) => {
    if (!columns[index]?.sortable || !sort || !onSortChange) return;
    onSortChange(sort.column === index
      ? { column: index, direction: sort.direction === 'asc' ? 'desc' : 'asc' }
      : { column: index, direction: 'asc' });
  };

  const gridRef = useRef<HTMLTableElement | null>(null);
  const [cursor, setCursor] = useState({ row: 0, col: 0 });

  const cellCounts = rowEls.map((row) => (
    React.isValidElement(row) ? React.Children.toArray(row.props.children).length : 0
  ));
  const rowLens = bare ? [] : [columns.length, ...cellCounts];

  const curRow = Math.min(Math.max(cursor.row, 0), Math.max(rowLens.length - 1, 0));
  const curCol = Math.min(Math.max(cursor.col, 0), Math.max((rowLens[curRow] || 0) - 1, 0));

  useEffect(() => {
    const g = gridRef.current;
    if (!g || flat) return;
    const active = g.ownerDocument.activeElement;
    if (!active || !g.contains(active)) return;

    if (active.tagName !== 'TD' && active.tagName !== 'TH') return;
    const cell = g.querySelector<HTMLElement>('td[tabindex="0"], th[tabindex="0"]');
    if (cell && cell !== active) cell.focus();
  }, [curRow, curCol]);

  const onGridKeyDown = (e: React.KeyboardEvent) => {
    if (flat) return;
    const t = e.target;
    if (!(t instanceof Element)) return;

    if (t.tagName !== 'TD' && t.tagName !== 'TH') return;

    let row = curRow;
    let col = curCol;
    if (e.key === 'ArrowUp') row = Math.max(0, row - 1);
    else if (e.key === 'ArrowDown') row = Math.min(rowLens.length - 1, row + 1);
    else if (e.key === 'ArrowLeft') col = Math.max(0, col - 1);
    else if (e.key === 'ArrowRight') col = Math.min(Math.max((rowLens[row] || 1) - 1, 0), col + 1);

    else if (e.key === 'Home') col = 0;
    else if (e.key === 'End') col = Math.max((rowLens[row] || 1) - 1, 0);
    else if (e.key === 'Enter' || e.key === ' ') {

      e.preventDefault();
      if (curRow === 0) { onHeaderActivate(curCol); return; }
      if (e.key === ' ') return;
      const rowEl = rowEls[curRow - 1];
      if (rowEl && React.isValidElement<ArenaTableRowProps>(rowEl)) {
        const { onClick: activate, interactive, disabled } = rowEl.props;
        if (interactive && activate && !disabled) activate();
      }
      return;
    } else return;

    col = Math.min(col, Math.max((rowLens[row] || 1) - 1, 0));

    e.preventDefault();

    if (row !== curRow || col !== curCol) setCursor({ row, col });
  };

  const onCellFocus = (ri: number, ci: number) => {
    if (ri !== curRow || ci !== curCol) setCursor({ row: ri, col: ci });
  };

  const headerNav = (ci: number) => ({
    tabIndex: 0 === curRow && ci === curCol ? 0 : -1,
    onFocus: (e: React.FocusEvent) => { if (e.target === e.currentTarget) onCellFocus(0, ci); },
  });

  const sortable = columns.map((column, index) => ({ column, index })).filter((c) => c.column.sortable);
  const sortBar = narrow && !bare && sortControl !== 'none' && Boolean(sort) && sortable.length > 0;
  const sortOptions: ArenaSelectOption[] = sortable.flatMap(({ column, index }) => [
    { value: arenaSortOptionValue(index, 'asc'), label: `${column.header} \u2191` },
    { value: arenaSortOptionValue(index, 'desc'), label: `${column.header} \u2193` },
  ]);
  const sortValue = sort ? arenaSortOptionValue(sort.column, sort.direction) : undefined;

  const headerClass = (c: ArenaTableColumn): string => {
    const base = arenaTableStyles({ narrow: false, align: c.align || 'left' }).th();
    return c.sortable && sort ? `${base} ${arenaTableStyles({ narrow: false }).thSortable()}` : base;
  };

  return (
    <div ref={ref} className={arenaTableStyles({ narrow }).root()} data-arena-part={manifest.parts.root}>
      {narrow && sortBar && (
        <div className={arenaTableStyles({ narrow: true }).sortBar()} data-arena-part={manifest.parts.sortBar}>
          <div className={arenaTableStyles({ narrow: true }).sortField()} data-arena-part={manifest.parts.sortField}>
            <ArenaSelect label="Sort by" options={sortOptions} value={sortValue}
              onChange={(picked) => { const next = arenaParseSortOption(picked); if (next) onSortChange?.(next); }} />
          </div>
        </div>
      )}
      <table role={flat ? 'presentation' : 'grid'} aria-label={flat ? undefined : label} ref={gridRef}
        aria-rowcount={flat ? undefined : rowCount}
        onKeyDown={onGridKeyDown}
        className={arenaTableStyles({ narrow }).grid()} data-arena-part={manifest.parts.grid}>
        {!flat && (
          <thead>
            <tr aria-rowindex={extent ? 1 : undefined}
              className={arenaTableStyles({ narrow: false }).headRow()} data-arena-part={manifest.parts.headRow}>
              {columns.map((c, ci) => (
                <th key={ci} scope="col" {...headerNav(ci)}
                  aria-sort={sortStateOf(ci)}
                  onClick={c.sortable && sort ? () => onHeaderActivate(ci) : undefined}
                  className={headerClass(c)} data-arena-part={manifest.parts.th}
                  style={{ width: c.width }}>{c.header}{sortStateOf(ci) && sortStateOf(ci) !== 'none' && (
                      <i aria-hidden="true"
                        className={`${arenaTableStyles({ narrow: false }).sortCaret()} ${sort?.direction === 'asc' ? 'ph-bold ph-caret-up' : 'ph-bold ph-caret-down'}`} data-arena-part={manifest.parts.sortCaret} />
                    )}</th>
              ))}
            </tr>
          </thead>
        )}
        <tbody role={flat ? 'presentation' : undefined}
          className={arenaTableStyles({ narrow }).body()} data-arena-part={manifest.parts.body}>
          {rowEls.map((row, ri) => (React.isValidElement(row)
            ? React.cloneElement(row, {
              rowIndex: ri + 1,
              ariaRowIndex: flat || !extent ? null : extent.offset + ri + 2,
              columns,
              layout: narrow ? 'card' : 'table',
              cursorCol: narrow || curRow !== ri + 1 ? null : curCol,
              onCellFocus: narrow ? undefined : onCellFocus,
            })
            : row))}
        </tbody>
      </table>
      {bare && (
        <div className={arenaTableStyles({ narrow }).empty()} data-arena-part={manifest.parts.empty}>{empty}</div>
      )}
      {!bare && page && pageControl !== 'none' && (
        <div className={arenaTableStyles({ narrow: false }).pager()} data-arena-part={manifest.parts.pager}>
          <ArenaPagination page={page.index} pageCount={pageCount} ariaLabel={label}
            onChange={(next) => onPageChange?.(next)} />
        </div>
      )}
    </div>
  );
}
