// frameworks/react/components/navigation/arena-side-nav-collapsible/ArenaSideNavCollapsible.tsx
import React, { useEffect, useState } from 'react';
import type { ArenaSideNavInjected } from '../arena-side-nav/SideNavInject.tsx';
import { arenaIndentFor, arenaInjectInto } from '../arena-side-nav/SideNavInject.tsx';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from '../arena-side-nav/ArenaSideNav.classes.generated.ts';
import { ArenaSideNavItem } from '../arena-side-nav-item/ArenaSideNavItem.tsx';

export interface ArenaSideNavCollapsibleProps {

  /** Identifies the group. The disclosure pattern needs two DOM ids that resolve -- the trigger's aria-controls must name the region, and the region's aria-labelledby must name the trigger -- and Arena derives both from this member, as `${id}-trigger` and `${id}-region`. Neither wiring is conditional: every collapsible has a trigger and a region, so there is no shape in which the id goes unused, and that is why it is required rather than optional. A group is a thing a consumer names anyway. Falsy-guarded as well as required: a blank id yields the pair `-trigger`/`-region`, which every other blank-id collapsible on the page would share, and duplicate ids make aria-controls resolve to the wrong element rather than to none. A consumer can address either element from outside as a consequence -- an aria-describedby, a deep link, a test hook -- but that is a benefit of the derivation, not the reason for it. */
  id: string;

  /** What the trigger reads, and the accessible name of both the trigger and the region it controls. Required and falsy-guarded. */
  label: string;

  /** A Phosphor class name drawn before the label. The caret that reports expanded-ness is Arena's own and is not this member. */
  icon?: string;

  /** Whether the group starts open. It is a seed, not a control: after the first render the state is the component's, and the group also opens itself when it comes to hold the active destination. */
  defaultExpanded?: boolean;

  /** What the group holds -- items, sections, further collapsibles. Each sits one nesting level deeper. */
  children?: React.ReactNode;

  /** The trigger was pressed, carrying the state it moved to. It fires on a press ONLY: the automatic expansion that follows the active destination is Arena's decision rather than the user's, and reporting it here would be a lie a consumer persists. */
  onToggle?: (expanded: boolean) => void;
}


const arenaSideNavStyles = arenaStyles(manifest);

export function arenaSubtreeHasItem(children: React.ReactNode, id: string | undefined): boolean {
  if (!id) return false;
  for (const child of React.Children.toArray(children)) {
    if (!React.isValidElement(child)) continue;
    const props = child.props as { id?: string; children?: React.ReactNode };
    if (child.type === ArenaSideNavItem && props.id === id) return true;
    if (arenaSubtreeHasItem(props.children, id)) return true;
  }
  return false;
}

export function ArenaSideNavCollapsible({
  id, label, icon, defaultExpanded = false, children, onToggle,
  depth = 0, activeId, indentStep = 3, onActivate, collapsed = false,
}: ArenaSideNavCollapsibleProps & Partial<ArenaSideNavInjected>) {

  if (!id) throw new Error('ArenaSideNavCollapsible: `id` is required');
  if (!label) throw new Error('ArenaSideNavCollapsible: `label` is required');

  const holdsActive = arenaSubtreeHasItem(children, activeId);

  const [expanded, setExpanded] = useState(defaultExpanded || holdsActive);
  useEffect(() => { if (holdsActive) setExpanded(true); }, [holdsActive]);

  const regionId = `${id}-region`;
  const triggerId = `${id}-trigger`;

  const press = () => {
    const next = !expanded;
    setExpanded(next);
    if (onToggle) onToggle(next);
  };

  const styles = arenaSideNavStyles({ collapsed });
  if (collapsed) {
    return (
      <div className={styles.section()} data-arena-part={manifest.parts.section}>
        <div aria-hidden="true" className={styles.separator()} data-arena-part={manifest.parts.separator} />
        <div role="group" aria-label={label} className={styles.region()} data-arena-part={manifest.parts.region} data-arena-boundary="">
          {arenaInjectInto(children, { depth, activeId, indentStep, onActivate, collapsed })}
        </div>
      </div>
    );
  }
  const glyph = icon ? <i className={`${icon} ${styles.icon()}`} data-arena-part={manifest.parts.icon} aria-hidden="true" /> : null;

  return (
    <div className={styles.section()} data-arena-part={manifest.parts.section}>
      {

}
      <button id={triggerId} type="button" aria-expanded={expanded} aria-controls={regionId}
        onClick={press}
        className={styles.trigger()} data-arena-part={manifest.parts.trigger}
        style={{ paddingInlineStart: arenaIndentFor(indentStep, depth) }}>
        {glyph}
        <span className={styles.triggerLabel()} data-arena-part={manifest.parts.triggerLabel}>{label}</span>
        <i className={`${expanded ? 'ph-bold ph-caret-down' : 'ph-bold ph-caret-right'} ${styles.caret()}`} data-arena-part={manifest.parts.caret}
          aria-hidden="true" />
      </button>
      {
}
      <div id={regionId} role="group" aria-labelledby={triggerId} hidden={!expanded}
        className={styles.region()} data-arena-part={manifest.parts.region} data-arena-boundary="">
        {arenaInjectInto(children, { depth: depth + 1, activeId, indentStep, onActivate, collapsed })}
      </div>
    </div>
  );
}

// frameworks/angular/components/navigation/arena-side-nav-collapsible/ArenaSideNavCollapsible.ts
import {
  ChangeDetectionStrategy, Component, booleanAttribute, computed, DestroyRef, effect,
  inject, input, output, signal, untracked,
} from '@angular/core';
import { ArenaSideNavState, arenaIndentFor } from '../arena-side-nav/ArenaSideNavState';
import { arenaSideNavStyles } from '../arena-side-nav/ArenaSideNav.variants';
import manifest from '../arena-side-nav/ArenaSideNav.classes.generated';

@Component({
  selector: 'arena-side-nav-collapsible',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [ArenaSideNavState],
  host: {
    '[class]': 'styles().section()',
    '[attr.data-arena-part]': 'parts.section',
    '[attr.id]': 'null',
  },
  template: `
    @if (rail()) {
      <div aria-hidden="true" [class]="styles().separator()" [attr.data-arena-part]="parts.separator"></div>
    } @else {
      <button type="button" [id]="triggerId()" [class]="styles().trigger()" [attr.data-arena-part]="parts.trigger"
              [style.paddingInlineStart]="indent()"
              [attr.aria-expanded]="expanded()" [attr.aria-controls]="regionId()"
              (click)="press()" (keydown)="onKeydown($event)">
        @if (icon(); as glyph) {
          <i [class]="styles().icon() + ' ' + glyph" [attr.data-arena-part]="parts.icon" aria-hidden="true"></i>
        }
        <span [class]="styles().triggerLabel()" [attr.data-arena-part]="parts.triggerLabel">{{ heading() }}</span>
        <i [class]="styles().caret() + ' ' + caretGlyph()" [attr.data-arena-part]="parts.caret" aria-hidden="true"></i>
      </button>
    }
    <div [id]="regionId()" [class]="styles().region()" [attr.data-arena-part]="parts.region" data-arena-boundary role="group"
         [attr.aria-labelledby]="rail() ? null : triggerId()" [attr.aria-label]="rail() ? heading() : null"
         [hidden]="!rail() && !expanded()">
      <ng-content />
    </div>
  `,
})
export class ArenaSideNavCollapsible {
  protected readonly parts = manifest.parts;

  /** Identifies the group. The disclosure pattern needs two DOM ids that resolve -- the trigger's aria-controls must name the region, and the region's aria-labelledby must name the trigger -- and Arena derives both from this member, as `${id}-trigger` and `${id}-region`. Neither wiring is conditional: every collapsible has a trigger and a region, so there is no shape in which the id goes unused, and that is why it is required rather than optional. A group is a thing a consumer names anyway. Falsy-guarded as well as required: a blank id yields the pair `-trigger`/`-region`, which every other blank-id collapsible on the page would share, and duplicate ids make aria-controls resolve to the wrong element rather than to none. A consumer can address either element from outside as a consequence -- an aria-describedby, a deep link, a test hook -- but that is a benefit of the derivation, not the reason for it. */
  readonly id = input.required<string>();
  /** What the trigger reads, and the accessible name of both the trigger and the region it controls. Required and falsy-guarded. */
  readonly label = input.required<string>();
  /** A Phosphor class name drawn before the label. The caret that reports expanded-ness is Arena's own and is not this member. */
  readonly icon = input<string>();
  /** Whether the group starts open. It is a seed, not a control: after the first render the state is the component's, and the group also opens itself when it comes to hold the active destination. */
  readonly defaultExpanded = input(false, { transform: booleanAttribute });
  /** The trigger was pressed, carrying the state it moved to. It fires on a press ONLY: the automatic expansion that follows the active destination is Arena's decision rather than the user's, and reporting it here would be a lie a consumer persists. */
  readonly toggle = output<boolean>();

  private readonly parent = inject(ArenaSideNavState, { skipSelf: true });
  private readonly own = inject(ArenaSideNavState);
  private readonly open = signal<boolean | null>(null);

  protected readonly triggerId = computed(() => `${this.key()}-trigger`);
  protected readonly regionId = computed(() => `${this.key()}-region`);
  protected readonly expanded = computed(() => this.open() ?? (this.defaultExpanded() || this.holdsActive()));
  protected readonly caretGlyph = computed(() => (this.expanded() ? 'ph-bold ph-caret-down' : 'ph-bold ph-caret-right'));

  protected readonly holdsActive = this.own.holdsActive;

  protected readonly heading = computed(() => {
    const text = this.label();
    if (text.trim() === '') {
      throw new Error('ArenaSideNavCollapsible: `label` is required, and names the group its trigger opens');
    }
    return text;
  });

  protected readonly indent = computed(() => (this.parent.collapsed() ? null : arenaIndentFor(this.parent.indentStep(), this.parent.depth())));
  protected readonly rail = computed(() => this.parent.collapsed());
  protected readonly styles = computed(() => arenaSideNavStyles({ collapsed: this.parent.collapsed() }));

  constructor() {
    this.own.depth = computed(() => this.parent.depth() + 1);
    this.own.activeId = this.parent.activeId;
    this.own.indentStep = this.parent.indentStep;
    this.own.collapsed = this.parent.collapsed;
    this.own.activate = (id: string) => this.parent.activate(id);
    this.parent.adopt(this.own);
    inject(DestroyRef).onDestroy(() => this.parent.orphan(this.own));

    effect(() => {
      const holds = this.holdsActive();
      untracked(() => {
        if (holds) this.open.set(true);
      });
    });
  }

  protected press(): void {
    const next = !this.expanded();
    this.open.set(next);
    this.toggle.emit(next);
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (event.key !== 'Enter' && event.key !== ' ') return;
    event.preventDefault();
    this.press();
  }

  private key(): string {
    const id = this.id();
    if (id.trim() === '') {
      throw new Error('ArenaSideNavCollapsible: `id` is required, and is what its trigger and its region are named from');
    }
    return id;
  }
}
