// frameworks/react/components/charts/arena-line-chart/ArenaLineChart.tsx
import React, { useEffect, useRef, useState } from 'react';
import { useArenaContainerWidth } from '../../../UseArenaContainerWidth.ts';
import {
  arenaSrOnly, arenaAreaFill, arenaPlotWidth, arenaRailStyle, arenaValueWriter, ARENA_CHART_HEIGHT,
} from '../../../DataVisuals.ts';
import { arenaWarnOnce } from '../../../WarnOnce.ts';
import {
  arenaLinearScale, arenaPointScale, arenaPointAt, arenaScaleValue, arenaNearestPointIndex,
} from '../ChartScales.ts';
import { arenaLinePoints, arenaLineAreaPath, arenaCurvePath, arenaCurveAreaPath } from '../ChartMarks.ts';
import { arenaPlotBox, arenaAxisModel, arenaTickLabelX, arenaCategoryLabelY, arenaValueGutter } from '../ChartAxis.ts';
import { arenaChartTable, arenaSeriesColors, arenaSwatchHue, arenaSeriesDomain, arenaSeriesPointCount } from '../ChartSeries.ts';
import { arenaLegendStrip } from '../ChartLegend.ts';
import { arenaTooltipAnchor } from '../ChartTooltip.ts';
import { arenaCursorHandles, arenaCursorStep, arenaPointerClears, arenaPointerUpdates } from '../ChartPointer.ts';
import { chartPointR, chartPointRHover } from '../../../Tokens.generated.js';

import type { ArenaNumberFormat, ArenaSeries } from '../../../Api.generated';
import { useArenaLocale } from '../../../ArenaLocale.ts';
import { arenaPhrase } from '../../../Phrase.ts';
import type { ArenaLineChartClass } from '../../../Vocabulary.generated.ts';
import { arenaClassName } from '../../../VocabularyClass.ts';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaLineChart.classes.generated.ts';

export interface ArenaLineChartProps {
  className?: ArenaLineChartClass;


  /** One label per point, in the same order as every series' `values`. A label with no value in a series ends that series' line there rather than dropping to zero. */
  labels: readonly string[];

  /** The plotted series, drawn as one polyline each over the same ordered sequence. One series is the common case and draws exactly what it drew before. The area fill is refused past one series, because two fills occlude each other and the reader cannot tell which value either edge belongs to. */
  series: readonly ArenaSeries[];

  /** Names the chart for its accessible name and for the caption of its data table. This is the CHART's name, not a series': a series names itself. Required and guarded rather than defaulted, because a fallback of the chart TYPE satisfies roles.label mechanically and tells a screen-reader user nothing, so two charts on one page announce identically. */
  label: string;

  /** Fill under the line at 18% of the series colour: a tint, never a gradient. For a single series; two fills occlude each other. */
  area?: boolean;

  /** Draw the series as a smooth curve rather than straight segments between points. The interpolation is monotone cubic, not Catmull-Rom, and that is the whole of the decision: a Catmull-Rom curve overshoots, so between two measured points it draws a peak or a trough nobody measured, and a chart that draws data which does not exist is the one thing a chart may not do. A monotone curve stays inside the band its own two points define, keeps a flat tangent at a turning point, and never crosses zero unless the values do. It changes the path string and nothing else: the points, the crosshair, the tooltip and the data cursor read the same numbers at the same places. */
  curve?: boolean;

  /** Appended verbatim to every number the chart draws: the axis ticks, the tooltip and the accessible table. Carries its own leading space if one is wanted. */
  valueSuffix?: string;

  /** Drawn verbatim before every number the chart writes, as valueSuffix is drawn after it. A currency that precedes its amount is the majority case worldwide and had no expression: with suffix alone, "1234.5 Bs." is what a chart drew where the table beside it read "Bs. 1.234,50", and the accessible table inherited the disagreement. */
  valuePrefix?: string;

  /** How each number is written before the prefix and suffix are added: which locale, how many fraction digits, whether thousands are grouped, whether large numbers are compacted. Absent, the raw JavaScript number, which is what this chart drew before the member existed. */
  valueFormat?: ArenaNumberFormat;

  /** The plot's height in px, the --chart-height token by default. A number rather than a dimension string, because the chart does arithmetic with it to place every mark, and a caller-supplied "20rem" is neither a token nor a derivation of one. */
  height?: number;

  /** The narrowest gap, in px, the chart draws between two adjacent points. Below it the chart stops compressing and overflows its container horizontally instead, scrolled and anchored to the most recent point: marker spacing is a legibility constant, not something that yields to the viewport, and thirty days in 390px is unreadable at any font size. Absent, the chart fits whatever width it is given. The rail it scrolls in is the same region the data cursor lives in, and it is keyboard-reachable whether it overflows or not. */
  minPointSpacing?: number;
}


const arenaLineChartStyles = arenaStyles(manifest);

export function ArenaLineChart({ className, 
  labels, series, label, area = false, curve = false, valueSuffix, valuePrefix, valueFormat,
  height = ARENA_CHART_HEIGHT, minPointSpacing,
}: ArenaLineChartProps) {
  const locale = useArenaLocale();
  const styles = arenaLineChartStyles();
  if (!label) throw new Error('ArenaLineChart: `label` is required (it names the chart for the accessible name, and nothing can derive that)');
  if (!labels) throw new Error('ArenaLineChart: `labels` is required');
  if (!series) throw new Error('ArenaLineChart: `series` is required');
  const [ref, measured] = useArenaContainerWidth();
  const rail = useRef<HTMLDivElement>(null);
  const [hover, setHover] = useState<number | null>(null);

  const available = measured ?? 600;
  const n = arenaSeriesPointCount(series);
  const width = arenaPlotWidth(available, n, minPointSpacing);
  const scrolls = width > available;
  const fmt = arenaValueWriter({ prefix: valuePrefix, suffix: valueSuffix, format: valueFormat });

  useEffect(() => {
    const box = rail.current;
    if (!box || !scrolls) return;
    box.scrollLeft = box.scrollWidth - box.clientWidth;
  }, [scrolls, width]);

  if (area && series.length > 1) {
    arenaWarnOnce('ArenaLineChart: `area` is for a single series. Two fills occlude each other and the reader cannot tell which value either edge belongs to, so none is drawn.');
  }
  const fills = area && series.length === 1;

  const domain = arenaSeriesDomain(series);
  const strip = arenaLegendStrip(height, series.length);
  const gutter = arenaValueGutter(domain, fmt);
  const box = arenaPlotBox(width, strip.plotH, gutter);
  const yScale = arenaLinearScale(domain.min, domain.max, box.y + box.h, box.y);
  const xScale = arenaPointScale(n, box.x, box.w);
  const axis = arenaAxisModel(yScale, domain, fmt);
  const colors = series.map((one, s) => arenaSeriesColors(one, 1, s + 1)[0] as string);
  const table = arenaChartTable(locale.chartTablePoint, series, labels, fmt);

  const plotted = series.map(
    (one) => one.values.map((value, i) => ({ x: arenaPointAt(xScale, i), y: arenaScaleValue(yScale, value) })),
  );

  const name = arenaPhrase(locale.lineChartName, { label });

  const onPointer = (e: React.PointerEvent<SVGRectElement>, phase: string) => {
    if (!n || !arenaPointerUpdates(e.pointerType, phase)) return;
    const svg = e.currentTarget.ownerSVGElement?.getBoundingClientRect();
    if (!svg) return;
    const across = Array.from({ length: n }, (_, i) => ({ x: arenaPointAt(xScale, i), y: 0 }));
    const index = arenaNearestPointIndex(across, e.clientX - svg.left);
    if (index >= 0) setHover(index);
  };

  const onKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (!arenaCursorHandles(e.key, 'x')) return;
    e.preventDefault();
    setHover(arenaCursorStep(hover, e.key, n, 'x'));
  };

  return (
    <div className={arenaClassName('ArenaLineChart', styles.frame(), className)} ref={ref} data-arena-part={manifest.parts.frame} {...styles.$data.frame()} style={{ height }}>
      <div ref={rail} style={arenaRailStyle} tabIndex={0} role="group" aria-label={name} onKeyDown={onKeyDown}>
      <svg width={scrolls ? width : '100%'} height={strip.plotH} role="img" aria-label={name} style={{ display: 'block', overflow: 'visible' }}>
        {axis.ticks.map((tick, i) => (
          <g key={i}>
            <line x1={box.x} x2={box.x + box.w} y1={tick.y} y2={tick.y} stroke="var(--edge-separator)" style={{ strokeWidth: 'var(--bw)' }} />
            <text x={arenaTickLabelX(gutter)} y={tick.y} textAnchor="end" dominantBaseline="middle"
              fill="color-mix(in oklab,var(--ink-muted) var(--level-ink-muted),transparent)" fontFamily="var(--font-mono)" style={{ fontSize: 'var(--dz-text-2xs)' }}>{tick.label}</text>
          </g>
        ))}
        <line x1={box.x} x2={box.x + box.w} y1={axis.zeroY} y2={axis.zeroY} stroke="var(--edge-axis)" style={{ strokeWidth: 'var(--bw)' }} />

        {}
        {fills && plotted.map((points, s) => points.length > 0 && (
          <path key={s} d={curve ? arenaCurveAreaPath(points, axis.zeroY) : arenaLineAreaPath(points, axis.zeroY)}
            fill={arenaAreaFill(colors[s] as string)} stroke="none" />
        ))}

        {hover !== null && (
          <line x1={arenaPointAt(xScale, hover)} x2={arenaPointAt(xScale, hover)} y1={box.y} y2={box.y + box.h}
            stroke="var(--edge-axis)" style={{ strokeWidth: 'var(--bw)' }} strokeDasharray="3 3" />
        )}

        {plotted.map((points, s) => points.length > 1 && (curve ? (
          <path key={s} d={arenaCurvePath(points)} fill="none" stroke={colors[s]} style={{ strokeWidth: 'var(--bw-strong)' }}
            strokeLinejoin="round" strokeLinecap="round" />
        ) : (
          <polyline key={s} points={arenaLinePoints(points)} fill="none" stroke={colors[s]} style={{ strokeWidth: 'var(--bw-strong)' }}
            strokeLinejoin="round" strokeLinecap="round" />
        )))}

        {plotted.map((points, s) => points.map((point, i) => (
          <circle key={`${s}-${i}`} cx={point.x} cy={point.y} r={hover === i ? chartPointRHover : chartPointR}
            fill={colors[s]} stroke="var(--fill-surface)" style={{ strokeWidth: 'var(--bw-strong)' }} />
        )))}

        {

}
        {Array.from({ length: n }, (_, i) => (
          <text key={i} x={arenaPointAt(xScale, i)} y={arenaCategoryLabelY(strip.plotH)} textAnchor="middle"
            fill="color-mix(in oklab,var(--ink-muted) var(--level-ink-muted),transparent)" fontFamily="var(--font-body)" style={{ fontSize: 'var(--dz-text-xs)' }}>{labels[i] ?? ''}</text>
        ))}

        {
}
        <rect x={box.x} y={box.y} width={box.w} height={box.h} fill="transparent"
          onPointerMove={(e) => onPointer(e, 'move')} onPointerDown={(e) => onPointer(e, 'down')}
          onPointerLeave={(e) => { if (arenaPointerClears(e.pointerType)) setHover(null); }}
          onPointerCancel={() => setHover(null)} />
      </svg>
      </div>

      {strip.stripH > 0 && (
        <div aria-hidden="true" className={styles.legend()} data-arena-part={manifest.parts.legend} {...styles.$data.legend()} style={{ height: strip.stripH }}>
          {series.map((one, s) => (
            <span key={s} className={styles.legendItem()} data-arena-part={manifest.parts.legendItem} {...styles.$data.legendItem()}>
              <span className={arenaLineChartStyles(arenaSwatchHue(one, 0, s + 1)).legendSwatch()} data-arena-part={manifest.parts.legendSwatch} {...arenaLineChartStyles(arenaSwatchHue(one, 0, s + 1)).$data.legendSwatch()} />
              <span className={styles.legendLabel()} data-arena-part={manifest.parts.legendLabel} {...styles.$data.legendLabel()}>{one.label}</span>
            </span>
          ))}
        </div>
      )}

      {hover !== null && hover < n && (
        <div className={styles.tooltip()} data-arena-part={manifest.parts.tooltip} {...styles.$data.tooltip()} style={{
          ...arenaTooltipAnchor(arenaPointAt(xScale, hover),
            Math.min(...series.map((one) => arenaScaleValue(yScale, one.values[hover] ?? 0)))),
        }}>
          <div className={styles.tooltipLabel()} data-arena-part={manifest.parts.tooltipLabel} {...styles.$data.tooltipLabel()}>{labels[hover]}</div>
          {series.map((one, s) => one.values[hover] !== undefined && (
            <div key={s} className={styles.tooltipValue()} data-arena-part={manifest.parts.tooltipValue} {...styles.$data.tooltipValue()}>
              {`${series.length > 1 ? `${one.label}: ` : ''}${fmt(one.values[hover] as number)}`}
            </div>
          ))}
        </div>
      )}

      <table style={arenaSrOnly}>
        <caption>{name}</caption>
        <thead><tr>{table.columns.map((column, i) => <th key={i}>{column}</th>)}</tr></thead>
        <tbody>
          {table.rows.map((row, i) => (
            <tr key={i}><th scope="row">{row.header}</th>{row.cells.map((cell, j) => <td key={j}>{cell}</td>)}</tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// frameworks/angular/components/charts/arena-line-chart/ArenaLineChart.ts
import {
  afterRenderEffect, booleanAttribute, ChangeDetectionStrategy, Component, computed, ElementRef, inject, input, signal, viewChild,
} from '@angular/core';
import { arenaContainerWidth } from '../../../ContainerSize';
import { arenaWarnOnce } from '../../../WarnOnce';
import {
  ARENA_CHART_HEIGHT, ARENA_RAIL_STYLE, ARENA_SR_ONLY, arenaAreaFill, arenaPlotWidth, arenaValueWriter,
} from '../../../DataVisuals';
import {
  arenaLinearScale, arenaPointScale, arenaPointAt, arenaScaleValue, arenaNearestPointIndex,
} from '../ChartScales';
import { arenaLinePoints, arenaLineAreaPath, arenaCurvePath, arenaCurveAreaPath } from '../ChartMarks';
import { arenaPlotBox, arenaAxisModel, arenaTickLabelX, arenaCategoryLabelY, arenaValueGutter } from '../ChartAxis';
import { arenaChartTable, arenaSeriesColors, arenaSwatchChoice, arenaSeriesDomain, arenaSeriesPointCount } from '../ChartSeries';
import { arenaTooltipAnchor } from '../ChartTooltip';
import { arenaCursorHandles, arenaCursorStep, arenaPointerClears, arenaPointerUpdates } from '../ChartPointer';
import { arenaLegendStrip } from '../ChartLegend';
import { arenaLineChartStyles } from './ArenaLineChart.variants';
import manifest from './ArenaLineChart.classes.generated';
import type { ArenaNumberFormat, ArenaSeries } from '../../../Api.generated';
import { chartPointR, chartPointRHover } from '../../../Tokens.generated';
import { ARENA_LOCALE } from '../../../ArenaLocale';
import { ArenaSlotAttributes } from '../../../SlotData';
import { arenaPhrase } from '../../../Phrase';

const ASSUMED_WIDTH = 600;

const POINT_R = chartPointR;
const POINT_R_HOVER = chartPointRHover;

const LINE_STYLE = { strokeWidth: 'var(--bw)' } as const satisfies Readonly<Record<string, string>>;

const SERIES_STROKE_STYLE = { strokeWidth: 'var(--bw-strong)' } as const satisfies Readonly<Record<string, string>>;

const TICK_LABEL_STYLE = { fontSize: 'var(--dz-text-2xs)' } as const satisfies Readonly<Record<string, string>>;

const POINT_LABEL_STYLE = { fontSize: 'var(--dz-text-xs)' } as const satisfies Readonly<Record<string, string>>;




@Component({
  selector: 'arena-line-chart',
  standalone: true,
  imports: [ArenaSlotAttributes],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <div [class]="styles.frame()" [attr.data-arena-part]="parts.frame" [style.height.px]="height()">
    <div #rail [style]="arenaRailStyle" tabindex="0" role="group" [attr.aria-label]="name()"
         (keydown)="onKey($event)">
    <svg [attr.width]="scrolls() ? width() : '100%'" [attr.height]="plotH()" role="img" [attr.aria-label]="name()"
         style="display:block;overflow:visible">
      @for (tick of gridLines(); track tick.value) {
        <g>
          <line [attr.x1]="plotLeft()" [attr.x2]="plotRight()" [attr.y1]="tick.y" [attr.y2]="tick.y"
                stroke="var(--edge-separator)" [style]="lineStyle" />
          <text [attr.x]="tickLabelX()" [attr.y]="tick.y" text-anchor="end" dominant-baseline="middle"
                fill="color-mix(in oklab,var(--ink-muted) var(--level-ink-muted),transparent)" font-family="var(--font-mono)"
                [style]="tickLabelStyle">{{ tick.label }}</text>
        </g>
      }
      <line [attr.x1]="plotLeft()" [attr.x2]="plotRight()" [attr.y1]="zeroY()" [attr.y2]="zeroY()"
            stroke="var(--edge-axis)" [style]="lineStyle" />

      @if (fills()) {
        @for (line of lines(); track line.key) {
          @if (line.points.length > 0) {
            <path [attr.d]="line.areaPath" [attr.fill]="line.areaFill" stroke="none" />
          }
        }
      }

      @if (active(); as point) {
        <line [attr.x1]="point.x" [attr.x2]="point.x" [attr.y1]="plotTop()" [attr.y2]="plotBottom()"
              stroke="var(--edge-axis)" stroke-dasharray="3 3" [style]="lineStyle" />
      }

      @for (line of lines(); track line.key) {
        @if (line.points.length > 1) {
          @if (curve()) {
            <path [attr.d]="line.curvePath" fill="none" [attr.stroke]="line.color"
                  stroke-linejoin="round" stroke-linecap="round" [style]="seriesStrokeStyle" />
          } @else {
            <polyline [attr.points]="line.polyline" fill="none" [attr.stroke]="line.color"
                      stroke-linejoin="round" stroke-linecap="round" [style]="seriesStrokeStyle" />
          }
        }
      }

      @for (mark of marks(); track mark.key) {
        <circle [attr.cx]="mark.x" [attr.cy]="mark.y"
                [attr.r]="hover() === mark.index ? pointRHover : pointR"
                [attr.fill]="mark.color" stroke="var(--fill-surface)" [style]="seriesStrokeStyle" />
      }

      @for (point of axisPoints(); track point.index) {
        <text [attr.x]="point.x" [attr.y]="pointLabelY()" text-anchor="middle"
              fill="color-mix(in oklab,var(--ink-muted) var(--level-ink-muted),transparent)" font-family="var(--font-body)"
              [style]="pointLabelStyle">{{ point.label }}</text>
      }

      <rect [attr.x]="plotLeft()" [attr.y]="plotTop()" [attr.width]="innerWidth()" [attr.height]="innerHeight()"
            fill="transparent" (pointermove)="onPointer($event, 'move')" (pointerdown)="onPointer($event, 'down')"
            (pointerleave)="onPointerLeave($event)" (pointercancel)="hover.set(null)" />
    </svg>
    </div>

    @if (legend(); as keys) {
      <div aria-hidden="true" [class]="styles.legend()" [attr.data-arena-part]="parts.legend" [style.height.px]="stripH()">
        @for (key of keys; track key.index) {
          <span [class]="styles.legendItem()" [attr.data-arena-part]="parts.legendItem">
            <span [class]="styles.legendSwatch()" [arenaSlotData]="key.swatch" [attr.data-arena-part]="parts.legendSwatch"></span>
            <span [class]="styles.legendLabel()" [attr.data-arena-part]="parts.legendLabel">{{ key.label }}</span>
          </span>
        }
      </div>
    }

    @if (active(); as point) {
      <div [class]="styles.tooltip()" [attr.data-arena-part]="parts.tooltip" [style.left.px]="point.anchor.left" [style.top]="point.anchor.top">
        <div [class]="styles.tooltipLabel()" [attr.data-arena-part]="parts.tooltipLabel">{{ point.label }}</div>
        @for (reading of point.readings; track reading.key) {
          <div [class]="styles.tooltipValue()" [attr.data-arena-part]="parts.tooltipValue">{{ reading.name }}{{ reading.value }}</div>
        }
      </div>
    }

    <table [style]="arenaSrOnly">
      <caption>{{ name() }}</caption>
      <thead><tr>@for (column of table().columns; track $index) { <th>{{ column }}</th> }</tr></thead>
      <tbody>
        @for (row of table().rows; track $index) {
          <tr><th scope="row">{{ row.header }}</th>@for (cell of row.cells; track $index) { <td>{{ cell }}</td> }</tr>
        }
      </tbody>
    </table>
    </div>
  `,
})
export class ArenaLineChart {
  protected readonly locale = inject(ARENA_LOCALE);
  /** One label per point, in the same order as every series' `values`. A label with no value in a series ends that series' line there rather than dropping to zero. */
  readonly labels = input.required<readonly string[]>();
  /** The plotted series, drawn as one polyline each over the same ordered sequence. One series is the common case and draws exactly what it drew before. The area fill is refused past one series, because two fills occlude each other and the reader cannot tell which value either edge belongs to. */
  readonly series = input.required<readonly ArenaSeries[]>();
  /** Names the chart for its accessible name and for the caption of its data table. This is the CHART's name, not a series': a series names itself. Required and guarded rather than defaulted, because a fallback of the chart TYPE satisfies roles.label mechanically and tells a screen-reader user nothing, so two charts on one page announce identically. */
  readonly label = input.required<string>();
  /** Fill under the line at 18% of the series colour: a tint, never a gradient. For a single series; two fills occlude each other. */
  readonly area = input(false, { transform: booleanAttribute });
  /** Draw the series as a smooth curve rather than straight segments between points. The interpolation is monotone cubic, not Catmull-Rom, and that is the whole of the decision: a Catmull-Rom curve overshoots, so between two measured points it draws a peak or a trough nobody measured, and a chart that draws data which does not exist is the one thing a chart may not do. A monotone curve stays inside the band its own two points define, keeps a flat tangent at a turning point, and never crosses zero unless the values do. It changes the path string and nothing else: the points, the crosshair, the tooltip and the data cursor read the same numbers at the same places. */
  readonly curve = input(false, { transform: booleanAttribute });
  /** Appended verbatim to every number the chart draws: the axis ticks, the tooltip and the accessible table. Carries its own leading space if one is wanted. */
  readonly valueSuffix = input<string>();
  /** Drawn verbatim before every number the chart writes, as valueSuffix is drawn after it. A currency that precedes its amount is the majority case worldwide and had no expression: with suffix alone, "1234.5 Bs." is what a chart drew where the table beside it read "Bs. 1.234,50", and the accessible table inherited the disagreement. */
  readonly valuePrefix = input<string>();
  /** How each number is written before the prefix and suffix are added: which locale, how many fraction digits, whether thousands are grouped, whether large numbers are compacted. Absent, the raw JavaScript number, which is what this chart drew before the member existed. */
  readonly valueFormat = input<ArenaNumberFormat>();
  /** The plot's height in px, the --chart-height token by default. A number rather than a dimension string, because the chart does arithmetic with it to place every mark, and a caller-supplied "20rem" is neither a token nor a derivation of one. */
  readonly height = input<number, number | undefined>(
    ARENA_CHART_HEIGHT,
    { transform: (value) => value ?? ARENA_CHART_HEIGHT },
  );
  /** The narrowest gap, in px, the chart draws between two adjacent points. Below it the chart stops compressing and overflows its container horizontally instead, scrolled and anchored to the most recent point: marker spacing is a legibility constant, not something that yields to the viewport, and thirty days in 390px is unreadable at any font size. Absent, the chart fits whatever width it is given. The rail it scrolls in is the same region the data cursor lives in, and it is keyboard-reachable whether it overflows or not. */
  readonly minPointSpacing = input<number>();

  protected readonly parts = manifest.parts;
  protected readonly styles = arenaLineChartStyles();
  protected readonly arenaSrOnly = ARENA_SR_ONLY;
  protected readonly arenaRailStyle = ARENA_RAIL_STYLE;
  protected readonly lineStyle = LINE_STYLE;
  protected readonly seriesStrokeStyle = SERIES_STROKE_STYLE;
  protected readonly tickLabelStyle = TICK_LABEL_STYLE;
  protected readonly pointLabelStyle = POINT_LABEL_STYLE;
  protected readonly pointR = POINT_R;
  protected readonly pointRHover = POINT_R_HOVER;
  protected readonly tickLabelX = computed(() => arenaTickLabelX(this.gutter()));
  protected readonly pointLabelY = computed(() => arenaCategoryLabelY(this.strip().plotH));
  protected readonly hover = signal<number | null>(null);

  private readonly write = computed(() => arenaValueWriter({
    prefix: this.valuePrefix(), suffix: this.valueSuffix(), format: this.valueFormat(),
  }));

  private readonly measured = arenaContainerWidth(() => this.rail()?.nativeElement);

  private readonly available = computed(() => this.measured() ?? ASSUMED_WIDTH);

  protected readonly width = computed(
    () => arenaPlotWidth(this.available(), this.pointCount(), this.minPointSpacing()),
  );

  protected readonly scrolls = computed(() => this.width() > this.available());

  private readonly rail = viewChild<ElementRef<HTMLElement>>('rail');

  protected readonly colors = computed(
    () => this.series().map((one, index) => arenaSeriesColors(one, 1, index + 1)[0] as string),
  );

  protected readonly fills = computed(() => {
    if (this.area() && this.series().length > 1) {
      arenaWarnOnce('ArenaLineChart: `area` is for a single series. Two fills occlude each other and the reader cannot tell which value either edge belongs to, so none is drawn.');
      return false;
    }
    return this.area();
  });

  protected readonly name = computed(() => {
    return arenaPhrase(this.locale.lineChartName, { label: this.label() });
  });

  private readonly domain = computed(() => arenaSeriesDomain(this.series()));
  protected readonly pointCount = computed(() => arenaSeriesPointCount(this.series()));
  private readonly strip = computed(() => arenaLegendStrip(this.height(), this.series().length));
  protected readonly plotH = computed(() => this.strip().plotH);
  protected readonly stripH = computed(() => this.strip().stripH);
  private readonly gutter = computed(() => arenaValueGutter(this.domain(), this.write()));

  private readonly box = computed(() => arenaPlotBox(this.width(), this.strip().plotH, this.gutter()));
  protected readonly plotLeft = computed(() => this.box().x);
  protected readonly plotRight = computed(() => this.box().x + this.box().w);
  protected readonly plotTop = computed(() => this.box().y);
  protected readonly innerWidth = computed(() => this.box().w);
  protected readonly innerHeight = computed(() => this.box().h);

  private readonly yScale = computed(() => {
    const box = this.box();
    const domain = this.domain();
    return arenaLinearScale(domain.min, domain.max, box.y + box.h, box.y);
  });

  private readonly xScale = computed(() => {
    const box = this.box();
    return arenaPointScale(this.pointCount(), box.x, box.w);
  });

  private readonly axis = computed(() => arenaAxisModel(this.yScale(), this.domain(), this.write()));

  protected readonly zeroY = computed(() => this.axis().zeroY);
  protected readonly plotBottom = computed(() => this.box().y + this.box().h);
  protected readonly gridLines = computed(() => this.axis().ticks);

  protected readonly lines = computed(() => {
    const yScale = this.yScale();
    const xScale = this.xScale();
    const colors = this.colors();
    const zeroY = this.zeroY();
    const curved = this.curve();
    return this.series().map((one, index) => {
      const points = one.values.map((value, i) => ({ x: arenaPointAt(xScale, i), y: arenaScaleValue(yScale, value) }));
      return {
        key: index,
        color: colors[index],
        polyline: arenaLinePoints(points),
        curvePath: arenaCurvePath(points),
        areaPath: curved ? arenaCurveAreaPath(points, zeroY) : arenaLineAreaPath(points, zeroY),
        areaFill: arenaAreaFill(colors[index] as string),
        points,
      };
    });
  });

  protected readonly marks = computed(() => this.lines().flatMap(
    (line) => line.points.map((point, index) => ({ key: `${line.key}-${index}`, index, x: point.x, y: point.y, color: line.color })),
  ));

  protected readonly axisPoints = computed(() => {
    const xScale = this.xScale();
    const labels = this.labels();
    const count = this.pointCount();
    return Array.from({ length: count }, (_, index) => ({ index, x: arenaPointAt(xScale, index), label: labels[index] ?? '' }));
  });

  protected readonly legend = computed(() => {
    if (this.strip().stripH === 0) return null;
    return this.series().map((one, index) => ({
      index, label: one.label, swatch: arenaLineChartStyles(arenaSwatchChoice(one, index + 1)).$data.legendSwatch(),
    }));
  });

  protected readonly table = computed(() => arenaChartTable(
    this.locale.chartTablePoint, this.series(), this.labels(), this.write(),
  ));

  protected readonly active = computed(() => {
    const index = this.hover();
    if (index === null || index >= this.pointCount()) return null;
    const yScale = this.yScale();
    const readings = this.series().flatMap((one, key) => {
      const value = one.values[index];
      return value === undefined ? [] : [{
        key,
        y: arenaScaleValue(yScale, value),
        name: this.series().length > 1 ? `${one.label}: ` : '',
        value: this.write()(value),
      }];
    });
    if (readings.length === 0) return null;
    const x = arenaPointAt(this.xScale(), index);
    return {
      x,
      label: this.labels()[index] ?? '',
      readings,
      anchor: arenaTooltipAnchor(x, Math.min(...readings.map((one) => one.y))),
    };
  });

  constructor() {

    afterRenderEffect(() => {
      const rail = this.rail()?.nativeElement;
      if (!rail || !this.scrolls()) return;
      rail.scrollLeft = rail.scrollWidth - rail.clientWidth;
    });
  }

  protected onPointer(event: PointerEvent, phase: string): void {
    if (!arenaPointerUpdates(event.pointerType, phase)) return;

    const box = (event.currentTarget as SVGRectElement).ownerSVGElement?.getBoundingClientRect();
    if (!box) return;
    const xScale = this.xScale();
    const across = Array.from({ length: this.pointCount() }, (_, i) => ({ x: arenaPointAt(xScale, i), y: 0 }));
    const index = arenaNearestPointIndex(across, event.clientX - box.left);
    if (index >= 0) this.hover.set(index);
  }

  protected onPointerLeave(event: PointerEvent): void {
    if (arenaPointerClears(event.pointerType)) this.hover.set(null);
  }

  protected onKey(event: KeyboardEvent): void {
    if (!arenaCursorHandles(event.key, 'x')) return;
    event.preventDefault();
    this.hover.set(arenaCursorStep(this.hover(), event.key, this.pointCount(), 'x'));
  }
}
