// frameworks/react/components/feedback/arena-confirm-dialog/ArenaConfirmDialog.tsx
import React, { useId, useRef, useState } from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaConfirmDialog.classes.generated.ts';
import { ArenaButton } from '../../forms/arena-button/ArenaButton.tsx';
import { useArenaDialogModal } from '../../../UseDialogModal.ts';
import { useArenaLocale } from '../../../ArenaLocale.ts';
import { arenaPhrase } from '../../../Phrase.ts';

export interface ArenaConfirmDialogProps {
  /** Whether the dialog is shown. The host owns it, as in the other three modals: defaulting it would let an ArenaConfirmDialog whose open was never wired render nothing forever and look like a working closed dialog. */
  open: boolean;
  /** The dialog was dismissed -- by the Cancel action or by the Escape key, in both layers. A scrim click is deliberately NOT one of them: this component never closes on click-outside. No payload. */
  onCancel?: () => void;
  /** The action was confirmed. */
  onConfirm?: () => void;

  /** The dialog heading, and the name the panel's aria-labelledby points at. Required: nothing can derive a name for a confirmation, because its subject is editorial, and a modal announcing only its role is worse than none at all. Required whatever open is, since a required member absent is a caller bug rather than a state to render: render the component when there is something to confirm, and hold on to the subject across a cancel so it still has a name while it closes. */
  title: string;
  /** Small uppercase label above the title. Absent, the provided locale's confirmDialogEyebrow answers it. */
  eyebrow?: string;
  /** The dialog body: the question and any detail. */
  children?: React.ReactNode;
  /** The confirm button's label. Absent, the provided locale's confirmDialogConfirm answers it. */
  confirmLabel?: string;
  /** The cancel button's label. Absent, the provided locale's confirmDialogCancel answers it. */
  cancelLabel?: string;
  /** Gives the confirm button Arena's only filled danger surface. */
  destructive?: boolean;
  /** Locks the confirm button until this exact word is typed. */
  requireText?: string;
}


const confirmStyles = arenaStyles(manifest);

export function ArenaConfirmDialog({ open, onCancel, onConfirm, title, eyebrow, children,
  confirmLabel, cancelLabel, destructive = false, requireText }: ArenaConfirmDialogProps) {
  const locale = useArenaLocale();
  const kicker = eyebrow ?? locale.confirmDialogEyebrow;
  const confirmText = confirmLabel ?? locale.confirmDialogConfirm;
  const cancelText = cancelLabel ?? locale.confirmDialogCancel;

  if (!title) throw new Error('ArenaConfirmDialog: `title` is required');
  if (open == null) throw new Error('ArenaConfirmDialog: `open` is required');
  const [typed, setTyped] = useState('');

  const panelRef = useRef<HTMLDivElement | null>(null);
  const onKeyDown = useArenaDialogModal({ open, panelRef, onDismiss: onCancel });

  const titleId = useId();
  if (!open) return null;
  const locked = requireText ? typed.trim() !== requireText : false;
  const styles = confirmStyles({ destructive, invalid: locked && typed !== '', open: true });
  return (
    <div className={styles.root()} data-arena-part={manifest.parts.root}>
      <div role="alertdialog" aria-modal="true"
        ref={panelRef} tabIndex={-1} onKeyDown={onKeyDown} aria-labelledby={titleId}
        className={styles.panel()} data-arena-part={manifest.parts.panel}>
        <div className={styles.head()} data-arena-part={manifest.parts.head}>
          <div className={styles.eyebrow()} data-arena-part={manifest.parts.eyebrow}>{kicker}</div>
          <div id={titleId} className={styles.title()} data-arena-part={manifest.parts.title}>{title}</div>
        </div>
        <div className={styles.body()} data-arena-part={manifest.parts.body} data-arena-boundary="">
          {children}
          {requireText && (
            <div className={styles.requireBlock()} data-arena-part={manifest.parts.requireBlock}>
              <div className={styles.requireLabel()} data-arena-part={manifest.parts.requireLabel}>{arenaPhrase(locale.confirmDialogRequire, { text: requireText })}</div>
              <input value={typed} onChange={(e) => setTyped(e.target.value)}
                className={styles.input()} data-arena-part={manifest.parts.input} />
            </div>
          )}
        </div>
        <div className={styles.foot()} data-arena-part={manifest.parts.foot}>
          <ArenaButton variant="ghost" onClick={onCancel}>{cancelText}</ArenaButton>
          <button type="button" onClick={onConfirm} disabled={locked} className={styles.confirm()} data-arena-part={manifest.parts.confirm}>
            {confirmText}
          </button>
        </div>
      </div>
    </div>
  );
}

// frameworks/angular/components/feedback/arena-confirm-dialog/ArenaConfirmDialog.ts
import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  ElementRef,
  afterRenderEffect,
  booleanAttribute,
  computed,
  inject,
  input,
  output,
  signal,
  untracked,
  viewChild,
} from '@angular/core';
import { ArenaButton } from '../../forms/arena-button/ArenaButton';
import { arenaConfirmDialogStyles } from './ArenaConfirmDialog.variants';
import manifest from './ArenaConfirmDialog.classes.generated';
import { type FocusTrapState, arenaHandleOpenTransition, arenaTrapTabKey } from '../../../FocusTrap';
import { ArenaIdGenerator } from '../../../ArenaIds';
import { ARENA_LOCALE } from '../../../ArenaLocale';
import { arenaPhrase } from '../../../Phrase';

export function isArenaConfirmLocked(required: string | undefined, typed: string): boolean {
  return required !== undefined && required !== '' && typed.trim() !== required;
}

@Component({
  selector: 'arena-confirm-dialog',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.data-arena-part]': 'open() ? parts.root : null',
    '(keydown)': 'onKeydown($event)',
    '[attr.title]': 'null',
  },
  imports: [ArenaButton],
  template: `
    @if (open()) {
      <div #panel [class]="styles().panel()" [attr.data-arena-part]="parts.panel" role="alertdialog" aria-modal="true" tabindex="-1"
           [attr.aria-labelledby]="titleId" [attr.aria-describedby]="descId">
        <div [class]="styles().head()" [attr.data-arena-part]="parts.head">
          <div [class]="styles().eyebrow()" [attr.data-arena-part]="parts.eyebrow">{{ kicker() }}</div>
          <div [id]="titleId" [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ title() }}</div>
        </div>
        <div [id]="descId" [class]="styles().body()" [attr.data-arena-part]="parts.body" data-arena-boundary>
          <ng-content />
          @if (requireText(); as required) {
            <div [class]="styles().requireBlock()" [attr.data-arena-part]="parts.requireBlock">
              <div [class]="styles().requireLabel()" [attr.data-arena-part]="parts.requireLabel">{{ requirePrompt(required) }}</div>
              <input [class]="styles().input()" [attr.data-arena-part]="parts.input" [value]="typed()" (input)="onType($event)" />
            </div>
          }
        </div>
        <div [class]="styles().foot()" [attr.data-arena-part]="parts.foot">
          <arena-button variant="ghost" (click)="cancel.emit()">{{ cancelText() }}</arena-button>
          <button type="button" [class]="styles().confirm()" [attr.data-arena-part]="parts.confirm" [disabled]="locked()" (click)="confirm.emit()">{{ confirmText() }}</button>
        </div>
      </div>
    }
  `,
})
export class ArenaConfirmDialog {
  protected readonly parts = manifest.parts;
  protected readonly locale = inject(ARENA_LOCALE);
  protected readonly kicker = computed(() => this.eyebrow() ?? this.locale.confirmDialogEyebrow);
  protected readonly confirmText = computed(() => this.confirmLabel() ?? this.locale.confirmDialogConfirm);
  protected readonly cancelText = computed(() => this.cancelLabel() ?? this.locale.confirmDialogCancel);

  protected requirePrompt(text: string): string {
    return arenaPhrase(this.locale.confirmDialogRequire, { text });
  }

  /** Whether the dialog is shown. The host owns it, as in the other three modals: defaulting it would let an ArenaConfirmDialog whose open was never wired render nothing forever and look like a working closed dialog. */
  readonly open = input.required<boolean, unknown>({ transform: booleanAttribute });

  /** The dialog heading, and the name the panel's aria-labelledby points at. Required: nothing can derive a name for a confirmation, because its subject is editorial, and a modal announcing only its role is worse than none at all. Required whatever open is, since a required member absent is a caller bug rather than a state to render: render the component when there is something to confirm, and hold on to the subject across a cancel so it still has a name while it closes. */
  readonly title = input.required<string>();
  /** Small uppercase label above the title. Absent, the provided locale's confirmDialogEyebrow answers it. */
  readonly eyebrow = input<string>();
  /** The confirm button's label. Absent, the provided locale's confirmDialogConfirm answers it. */
  readonly confirmLabel = input<string>();
  /** The cancel button's label. Absent, the provided locale's confirmDialogCancel answers it. */
  readonly cancelLabel = input<string>();
  /** Gives the confirm button Arena's only filled danger surface. */
  readonly destructive = input(false, { transform: booleanAttribute });
  /** Locks the confirm button until this exact word is typed. */
  readonly requireText = input<string>();
  /** The dialog was dismissed -- by the Cancel action or by the Escape key, in both layers. A scrim click is deliberately NOT one of them: this component never closes on click-outside. No payload. */
  readonly cancel = output<void>();
  /** The action was confirmed. */
  readonly confirm = output<void>();

  private readonly doc = inject(DOCUMENT);
  private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');

  private readonly uid = inject(ArenaIdGenerator).next('arena-confirm-dialog');
  protected readonly titleId = `${this.uid}-title`;
  protected readonly descId = `${this.uid}-body`;

  protected readonly typed = signal('');
  protected readonly locked = computed(() => isArenaConfirmLocked(this.requireText(), this.typed()));
  protected readonly styles = computed(() => arenaConfirmDialogStyles({
    destructive: this.destructive(),
    invalid: this.locked() && this.typed().length > 0,
    open: this.open(),
  }));

  private readonly focusTrap: FocusTrapState = { wasOpen: false, restoreTo: null };

  constructor() {
    afterRenderEffect(() => {
      const isOpen = this.open();
      untracked(() => {
        arenaHandleOpenTransition(this.focusTrap, isOpen, this.panel()?.nativeElement ?? null, this.doc.activeElement);
      });
    });
  }

  protected onType(event: Event): void {
    this.typed.set((event.target as HTMLInputElement).value);
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (!this.open()) return;
    if (event.key === 'Escape') {
      event.preventDefault();
      this.cancel.emit();
      return;
    }
    if (event.key === 'Tab') {
      const panel = this.panel()?.nativeElement;
      if (panel) arenaTrapTabKey(panel, event, this.doc.activeElement);
    }
  }
}
