// frameworks/angular/components/charts/arena-pyramid-chart/ArenaPyramidChart.ts
import {
  ChangeDetectionStrategy, Component, computed, ElementRef, inject, input, signal, viewChild,
} from '@angular/core';
import { arenaContainerWidth } from '../../../ContainerSize';
import {
  ARENA_CHART_HEIGHT, ARENA_SR_ONLY, arenaValueWriter,
} from '../../../DataVisuals';
import {
  arenaLinearScale, arenaBandScale, arenaBandCenter, arenaBandIndex, arenaBandMark, arenaScaleValue,
} from '../ChartScales';
import { arenaBarPathH } from '../ChartMarks';
import { arenaPlotBoxH, arenaAxisModelX, arenaCategoryLabelX, arenaTickLabelY } from '../ChartAxis';
import {
  arenaChartTable, arenaSeriesColors, arenaSeriesPointCount, arenaMirrorDomain, arenaTwoSeries,
} from '../ChartSeries';
import { arenaLegendStrip } from '../ChartLegend';
import { arenaTooltipAnchor } from '../ChartTooltip';
import { arenaCursorHandles, arenaCursorStep, arenaPointerClears, arenaPointerUpdates } from '../ChartPointer';
import { arenaPyramidChartStyles } from './ArenaPyramidChart.variants';
import manifest from './ArenaPyramidChart.classes.generated';
import type { ArenaNumberFormat, ArenaSeries } from '../../../Api.generated';
import { chartBarGap, chartBarRadius } from '../../../Tokens.generated';
import { ARENA_LOCALE } from '../../../ArenaLocale';
import { arenaPhrase } from '../../../Phrase';

const BAR_RADIUS = chartBarRadius;

const ASSUMED_WIDTH = 600;

const REGION_STYLE = { display: 'block', outlineOffset: 'var(--focus-offset)' } as const satisfies Readonly<Record<string, string>>;

const LINE_STYLE = { strokeWidth: 'var(--bw)' } as const satisfies Readonly<Record<string, string>>;

const TICK_LABEL_STYLE = { fontSize: 'var(--dz-text-2xs)' } as const satisfies Readonly<Record<string, string>>;

const CATEGORY_LABEL_STYLE = { fontSize: 'var(--dz-text-xs)' } as const satisfies Readonly<Record<string, string>>;

const BAR_STYLE = { transition: 'opacity var(--dur-hover) var(--ease-hover)' } as const satisfies Readonly<Record<string, string>>;




@Component({
  selector: 'arena-pyramid-chart',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    style: 'display:block;position:relative;width:100%',
    '[style.height.px]': 'height()',
  },
  template: `
    <div #region [style]="regionStyle" tabindex="0" role="group" [attr.aria-label]="name()"
         (keydown)="onKey($event)">
    <svg width="100%" [attr.height]="plotH()" role="img" [attr.aria-label]="name()"
         style="display:block;overflow:visible">
      @for (tick of gridLines(); track tick.value) {
        <g>
          <line [attr.x1]="tick.x" [attr.x2]="tick.x" [attr.y1]="plotTop()" [attr.y2]="plotBottom()"
                stroke="var(--border)" [style]="lineStyle" />
          <text [attr.x]="tick.x" [attr.y]="tickLabelY()" text-anchor="middle"
                fill="var(--text-muted)" font-family="var(--font-mono)"
                [style]="tickLabelStyle">{{ tick.label }}</text>
        </g>
      }
      <line [attr.x1]="zeroX()" [attr.x2]="zeroX()" [attr.y1]="plotTop()" [attr.y2]="plotBottom()"
            stroke="var(--line-strong)" [style]="lineStyle" />

      @for (bar of bars(); track bar.index) {
        <g>
          @for (mark of bar.marks; track mark.key) {
            <path [attr.d]="mark.path" [attr.fill]="mark.color"
                  [attr.opacity]="hover() === null || hover() === bar.index ? 1 : 0.55"
                  [style]="barStyle" />
          }
        </g>
      }

      @for (bar of bars(); track bar.index) {
        <text [attr.x]="categoryLabelX" [attr.y]="bar.midY" text-anchor="end" dominant-baseline="middle"
              fill="var(--text-muted)" font-family="var(--font-body)"
              [style]="categoryLabelStyle">{{ bar.label }}</text>
      }

      <rect [attr.x]="plotLeft()" [attr.y]="plotTop()" [attr.width]="innerWidth()" [attr.height]="innerHeight()"
            fill="transparent" (pointermove)="onPointer($event, 'move')" (pointerdown)="onPointer($event, 'down')"
            (pointerleave)="onPointerLeave($event)" (pointercancel)="hover.set(null)" />
    </svg>
    </div>

    @if (legend(); as keys) {
      <div aria-hidden="true" [class]="styles.legend()" [attr.data-arena-part]="parts.legend" [style.height.px]="stripH()">
        @for (key of keys; track key.index) {
          <span [class]="styles.legendItem()" [attr.data-arena-part]="parts.legendItem">
            <span [class]="styles.legendSwatch()" [attr.data-arena-part]="parts.legendSwatch" [style.background]="key.color"></span>
            <span [class]="styles.legendLabel()" [attr.data-arena-part]="parts.legendLabel">{{ key.label }}</span>
          </span>
        }
      </div>
    }

    @if (active(); as point) {
      <div [class]="styles.tooltip()" [attr.data-arena-part]="parts.tooltip" [style.left.px]="point.anchor.left" [style.top]="point.anchor.top">
        <div [class]="styles.tooltipLabel()" [attr.data-arena-part]="parts.tooltipLabel">{{ point.label }}</div>
        @for (mark of point.marks; track mark.key) {
          <div [class]="styles.tooltipValue()" [attr.data-arena-part]="parts.tooltipValue">{{ mark.name }}{{ mark.value }}</div>
        }
      </div>
    }

    <table [style]="arenaSrOnly">
      <caption>{{ name() }}</caption>
      <thead><tr>@for (column of table().columns; track $index) { <th>{{ column }}</th> }</tr></thead>
      <tbody>
        @for (row of table().rows; track $index) {
          <tr><th scope="row">{{ row.header }}</th>@for (cell of row.cells; track $index) { <td>{{ cell }}</td> }</tr>
        }
      </tbody>
    </table>
  `,
})
export class ArenaPyramidChart {
  protected readonly locale = inject(ARENA_LOCALE);
  /** One label per band, in the same order as both series' `values`, running down the left edge. On a population pyramid these are the age brackets, oldest first or youngest first as the data is given: the chart does not reorder them, because which end is the top is a decision about the population and not about the drawing. */
  readonly labels = input.required<readonly string[]>();
  /** Exactly two series, one for each side of the centre line, in order: the first is drawn to the left and the second to the right. Both carry counts rather than signed values, and the chart negates the first when it draws it, so the accessible table reads the numbers that were passed and the picture reads the shape they make. A third series has nowhere to go and warns; a single one is a horizontal bar chart and should be one. */
  readonly series = input.required<readonly ArenaSeries[]>();
  /** Names the chart for its accessible name and for the caption of its data table. This is the CHART's name, not a series': a series names itself. Required and guarded rather than defaulted, because a fallback of the chart TYPE satisfies roles.label mechanically and tells a screen-reader user nothing, so two charts on one page announce identically. */
  readonly label = input.required<string>();
  /** Appended verbatim to every number the chart draws: the axis ticks, the tooltip and the accessible table. The ticks carry the magnitude, never the minus sign the left side is drawn with, because both sides count upward from the centre. */
  readonly valueSuffix = input<string>();
  /** Drawn verbatim before every number the chart writes, as valueSuffix is drawn after it. A currency that precedes its amount is the majority case worldwide and had no expression: with suffix alone, "1234.5 Bs." is what a chart drew where the table beside it read "Bs. 1.234,50", and the accessible table inherited the disagreement. */
  readonly valuePrefix = input<string>();
  /** How each number is written before the prefix and suffix are added: which locale, how many fraction digits, whether thousands are grouped, whether large numbers are compacted. Absent, the raw JavaScript number, which is what this chart drew before the member existed. */
  readonly valueFormat = input<ArenaNumberFormat>();
  /** The plot's height in px, the --chart-height token by default. It is the axis the bands run down, so a pyramid of many brackets wants more of it: pass the room the data needs rather than letting the bands thin out. A number rather than a dimension string, because the chart does arithmetic with it to place every mark. */
  readonly height = input<number, number | undefined>(
    ARENA_CHART_HEIGHT,
    { transform: (value) => value ?? ARENA_CHART_HEIGHT },
  );

  protected readonly parts = manifest.parts;
  protected readonly styles = arenaPyramidChartStyles();
  protected readonly arenaSrOnly = ARENA_SR_ONLY;
  protected readonly regionStyle = REGION_STYLE;
  protected readonly lineStyle = LINE_STYLE;
  protected readonly tickLabelStyle = TICK_LABEL_STYLE;
  protected readonly categoryLabelStyle = CATEGORY_LABEL_STYLE;
  protected readonly barStyle = BAR_STYLE;
  protected readonly categoryLabelX = arenaCategoryLabelX();
  protected readonly hover = signal<number | null>(null);

  private readonly write = computed(() => arenaValueWriter({
    prefix: this.valuePrefix(), suffix: this.valueSuffix(), format: this.valueFormat(),
  }));

  private readonly region = viewChild<ElementRef<HTMLElement>>('region');

  private readonly measured = arenaContainerWidth(() => this.region()?.nativeElement);

  private readonly width = computed(() => this.measured() ?? ASSUMED_WIDTH);

  protected readonly name = computed(() => {
    return arenaPhrase(this.locale.pyramidChartName, { label: this.label() });
  });

  private readonly sides = computed(() => arenaTwoSeries(this.series(), 'ArenaPyramidChart'));

  private readonly away = computed(() => {
    const write = this.write();
    return (value: number) => write(Math.abs(value));
  });

  private readonly domain = computed(() => arenaMirrorDomain(this.sides()));

  private readonly points = computed(() => arenaSeriesPointCount(this.sides()));
  private readonly strip = computed(() => arenaLegendStrip(this.height(), this.sides().length));
  protected readonly plotH = computed(() => this.strip().plotH);
  protected readonly stripH = computed(() => this.strip().stripH);
  private readonly box = computed(() => arenaPlotBoxH(this.width(), this.strip().plotH));
  protected readonly plotLeft = computed(() => this.box().x);
  protected readonly plotTop = computed(() => this.box().y);
  protected readonly plotBottom = computed(() => this.box().y + this.box().h);
  protected readonly innerWidth = computed(() => this.box().w);
  protected readonly innerHeight = computed(() => this.box().h);
  protected readonly tickLabelY = computed(() => arenaTickLabelY(this.strip().plotH));

  private readonly xScale = computed(() => {
    const box = this.box();
    const domain = this.domain();
    return arenaLinearScale(domain.min, domain.max, box.x, box.x + box.w);
  });

  private readonly bands = computed(() => {
    const box = this.box();
    return arenaBandScale(this.points(), box.y, box.h, chartBarGap);
  });

  private readonly axis = computed(() => arenaAxisModelX(this.xScale(), this.domain(), this.away()));

  protected readonly zeroX = computed(() => this.axis().zeroX);
  protected readonly gridLines = computed(() => this.axis().ticks);

  protected readonly bars = computed(() => {
    const sides = this.sides();
    const bands = this.bands();
    const xScale = this.xScale();
    const zeroX = this.zeroX();
    const write = this.write();
    const labels = this.labels();
    return Array.from({ length: this.points() }, (_, index) => ({
      index,
      midY: arenaBandCenter(bands, index),
      label: labels[index] ?? '',
      marks: sides.flatMap((one, s) => {
        const value = one.values[index];
        if (value === undefined) return [];
        const signed = s === 0 ? -value : value;
        return [{
          key: s,
          name: `${one.label}: `,
          path: arenaBarPathH(arenaBandMark(bands, index), bands.band,
            arenaScaleValue(xScale, signed), zeroX, BAR_RADIUS),
          color: arenaSeriesColors(one, this.points(), s + 1)[index],
          value: write(value),
        }];
      }),
    }));
  });

  protected readonly legend = computed(() => {
    const sides = this.sides();
    if (this.strip().stripH === 0) return null;
    return sides.map((one, index) => ({
      index,
      label: one.label,
      color: arenaSeriesColors(one, this.points(), index + 1)[0],
    }));
  });

  protected readonly table = computed(() => arenaChartTable(
    this.locale.chartTableCategory, this.sides(), this.labels(), this.write(),
  ));

  protected readonly active = computed(() => {
    const index = this.hover();
    const bar = index === null ? null : this.bars()[index] ?? null;
    if (!bar || bar.marks.length === 0) return null;
    return { ...bar, anchor: arenaTooltipAnchor(this.zeroX(), bar.midY) };
  });

  protected onPointer(event: PointerEvent, phase: string): void {
    if (!arenaPointerUpdates(event.pointerType, phase)) return;
    const box = (event.currentTarget as SVGRectElement).ownerSVGElement?.getBoundingClientRect();
    if (!box) return;
    const index = arenaBandIndex(this.bands(), event.clientY - box.top);
    if (index >= 0) this.hover.set(index);
  }

  protected onPointerLeave(event: PointerEvent): void {
    if (arenaPointerClears(event.pointerType)) this.hover.set(null);
  }

  protected onKey(event: KeyboardEvent): void {
    if (!arenaCursorHandles(event.key, 'y')) return;
    event.preventDefault();
    this.hover.set(arenaCursorStep(this.hover(), event.key, this.points(), 'y'));
  }
}

// frameworks/react/components/charts/arena-pyramid-chart/ArenaPyramidChart.tsx
import React, { useState } from 'react';
import { useArenaContainerWidth } from '../../../UseArenaContainerWidth.ts';
import { arenaSrOnly, arenaValueWriter, ARENA_CHART_HEIGHT } from '../../../DataVisuals.ts';
import {
  arenaLinearScale, arenaBandScale, arenaBandCenter, arenaBandIndex, arenaBandMark, arenaScaleValue,
} from '../ChartScales.ts';
import { arenaBarPathH } from '../ChartMarks.ts';
import { arenaPlotBoxH, arenaAxisModelX, arenaCategoryLabelX, arenaTickLabelY } from '../ChartAxis.ts';
import {
  arenaChartTable, arenaSeriesColors, arenaSeriesPointCount, arenaMirrorDomain, arenaTwoSeries,
} from '../ChartSeries.ts';
import { arenaLegendStrip } from '../ChartLegend.ts';
import { arenaTooltipAnchor } from '../ChartTooltip.ts';
import { arenaCursorHandles, arenaCursorStep, arenaPointerClears, arenaPointerUpdates } from '../ChartPointer.ts';
import { chartBarGap, chartBarRadius } from '../../../Tokens.generated.js';

import type { ArenaNumberFormat, ArenaSeries } from '../../../Api.generated';
import { useArenaLocale } from '../../../ArenaLocale.ts';
import { arenaPhrase } from '../../../Phrase.ts';
import type { ArenaPyramidChartClass } from '../../../Vocabulary.generated.ts';
import { arenaClassName } from '../../../VocabularyClass.ts';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaPyramidChart.classes.generated.ts';

export interface ArenaPyramidChartProps {
  className?: ArenaPyramidChartClass;


  /** One label per band, in the same order as both series' `values`, running down the left edge. On a population pyramid these are the age brackets, oldest first or youngest first as the data is given: the chart does not reorder them, because which end is the top is a decision about the population and not about the drawing. */
  labels: readonly string[];

  /** Exactly two series, one for each side of the centre line, in order: the first is drawn to the left and the second to the right. Both carry counts rather than signed values, and the chart negates the first when it draws it, so the accessible table reads the numbers that were passed and the picture reads the shape they make. A third series has nowhere to go and warns; a single one is a horizontal bar chart and should be one. */
  series: readonly ArenaSeries[];

  /** Names the chart for its accessible name and for the caption of its data table. This is the CHART's name, not a series': a series names itself. Required and guarded rather than defaulted, because a fallback of the chart TYPE satisfies roles.label mechanically and tells a screen-reader user nothing, so two charts on one page announce identically. */
  label: string;

  /** Appended verbatim to every number the chart draws: the axis ticks, the tooltip and the accessible table. The ticks carry the magnitude, never the minus sign the left side is drawn with, because both sides count upward from the centre. */
  valueSuffix?: string;

  /** Drawn verbatim before every number the chart writes, as valueSuffix is drawn after it. A currency that precedes its amount is the majority case worldwide and had no expression: with suffix alone, "1234.5 Bs." is what a chart drew where the table beside it read "Bs. 1.234,50", and the accessible table inherited the disagreement. */
  valuePrefix?: string;

  /** How each number is written before the prefix and suffix are added: which locale, how many fraction digits, whether thousands are grouped, whether large numbers are compacted. Absent, the raw JavaScript number, which is what this chart drew before the member existed. */
  valueFormat?: ArenaNumberFormat;

  /** The plot's height in px, the --chart-height token by default. It is the axis the bands run down, so a pyramid of many brackets wants more of it: pass the room the data needs rather than letting the bands thin out. A number rather than a dimension string, because the chart does arithmetic with it to place every mark. */
  height?: number;
}


const arenaPyramidChartStyles = arenaStyles(manifest);

export function ArenaPyramidChart({ className, 
  labels, series, label, valueSuffix, valuePrefix, valueFormat,
  height = ARENA_CHART_HEIGHT,
}: ArenaPyramidChartProps) {
  const locale = useArenaLocale();
  const styles = arenaPyramidChartStyles();
  if (!label) throw new Error('ArenaPyramidChart: `label` is required (it names the chart for the accessible name, and nothing can derive that)');
  if (!labels) throw new Error('ArenaPyramidChart: `labels` is required');
  if (!series) throw new Error('ArenaPyramidChart: `series` is required');
  const [ref, measured] = useArenaContainerWidth();
  const [hover, setHover] = useState<number | null>(null);

  const width = measured ?? 600;
  const sides = arenaTwoSeries(series, 'ArenaPyramidChart');
  const n = arenaSeriesPointCount(sides);
  const fmt = arenaValueWriter({ prefix: valuePrefix, suffix: valueSuffix, format: valueFormat });
  const away = (value: number) => fmt(Math.abs(value));

  const domain = arenaMirrorDomain(sides);
  const strip = arenaLegendStrip(height, sides.length);
  const box = arenaPlotBoxH(width, strip.plotH);
  const xScale = arenaLinearScale(domain.min, domain.max, box.x, box.x + box.w);
  const bands = arenaBandScale(n, box.y, box.h, chartBarGap);
  const axis = arenaAxisModelX(xScale, domain, away);
  const colors = sides.map((one, s) => arenaSeriesColors(one, n, s + 1));
  const table = arenaChartTable(locale.chartTableCategory, sides, labels, fmt);

  const name = arenaPhrase(locale.pyramidChartName, { label });

  const onPointer = (e: React.PointerEvent<SVGRectElement>, phase: string) => {
    if (!arenaPointerUpdates(e.pointerType, phase)) return;
    const svg = e.currentTarget.ownerSVGElement?.getBoundingClientRect();
    if (!svg) return;
    const index = arenaBandIndex(bands, e.clientY - svg.top);
    if (index >= 0) setHover(index);
  };

  const onKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (!arenaCursorHandles(e.key, 'y')) return;
    e.preventDefault();
    setHover(arenaCursorStep(hover, e.key, n, 'y'));
  };

  return (
    <div className={arenaClassName('ArenaPyramidChart', undefined, className)} ref={ref} style={{ position: 'relative', width: '100%', height }}>
      <div tabIndex={0} role="group" aria-label={name} onKeyDown={onKeyDown}
        style={{ display: 'block', outlineOffset: 'var(--focus-offset)' }}>
      <svg width="100%" height={strip.plotH} role="img" aria-label={name}
        style={{ display: 'block', overflow: 'visible' }}>
        {axis.ticks.map((tick, i) => (
          <g key={i}>
            <line x1={tick.x} x2={tick.x} y1={box.y} y2={box.y + box.h}
              stroke="var(--border)" style={{ strokeWidth: 'var(--bw)' }} />
            <text x={tick.x} y={arenaTickLabelY(strip.plotH)} textAnchor="middle"
              fill="var(--text-muted)" fontFamily="var(--font-mono)" style={{ fontSize: 'var(--dz-text-2xs)' }}>{tick.label}</text>
          </g>
        ))}
        <line x1={axis.zeroX} x2={axis.zeroX} y1={box.y} y2={box.y + box.h}
          stroke="var(--line-strong)" style={{ strokeWidth: 'var(--bw)' }} />

        {Array.from({ length: n }, (_, i) => (
          <g key={i}>
            {sides.map((one, s) => {
              const value = one.values[i];
              if (value === undefined) return null;
              const away = s === 0 ? -value : value;
              return (
                <path key={s} d={arenaBarPathH(arenaBandMark(bands, i), bands.band,
                  arenaScaleValue(xScale, away), axis.zeroX, chartBarRadius)} fill={colors[s]?.[i]}
                  opacity={hover === null || hover === i ? 1 : 0.55}
                  style={{ transition: 'opacity var(--dur-hover) var(--ease-hover)' }} />
              );
            })}
          </g>
        ))}

        {Array.from({ length: n }, (_, i) => (
          <text key={i} x={arenaCategoryLabelX()} y={arenaBandCenter(bands, i)} textAnchor="end" dominantBaseline="middle"
            fill="var(--text-muted)" fontFamily="var(--font-body)" style={{ fontSize: 'var(--dz-text-xs)' }}>{labels[i] ?? ''}</text>
        ))}

        <rect x={box.x} y={box.y} width={box.w} height={box.h} fill="transparent"
          onPointerMove={(e) => onPointer(e, 'move')} onPointerDown={(e) => onPointer(e, 'down')}
          onPointerLeave={(e) => { if (arenaPointerClears(e.pointerType)) setHover(null); }}
          onPointerCancel={() => setHover(null)} />
      </svg>
      </div>

      {strip.stripH > 0 && (
        <div aria-hidden="true" className={styles.legend()} data-arena-part={manifest.parts.legend} style={{ height: strip.stripH }}>
          {sides.map((one, s) => (
            <span key={s} className={styles.legendItem()} data-arena-part={manifest.parts.legendItem}>
              <span className={styles.legendSwatch()} data-arena-part={manifest.parts.legendSwatch} style={{ background: colors[s]?.[0] }} />
              <span className={styles.legendLabel()} data-arena-part={manifest.parts.legendLabel}>{one.label}</span>
            </span>
          ))}
        </div>
      )}

      {hover !== null && hover < n && (
        <div className={styles.tooltip()} data-arena-part={manifest.parts.tooltip} style={{
          ...arenaTooltipAnchor(axis.zeroX, arenaBandCenter(bands, hover)),
        }}>
          <div className={styles.tooltipLabel()} data-arena-part={manifest.parts.tooltipLabel}>{labels[hover]}</div>
          {sides.map((one, s) => one.values[hover] !== undefined && (
            <div key={s} className={styles.tooltipValue()} data-arena-part={manifest.parts.tooltipValue}>
              {`${one.label}: ${fmt(one.values[hover] as number)}`}
            </div>
          ))}
        </div>
      )}

      <table style={arenaSrOnly}>
        <caption>{name}</caption>
        <thead><tr>{table.columns.map((column, i) => <th key={i}>{column}</th>)}</tr></thead>
        <tbody>
          {table.rows.map((row, i) => (
            <tr key={i}><th scope="row">{row.header}</th>{row.cells.map((cell, j) => <td key={j}>{cell}</td>)}</tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
