// frameworks/angular/components/display/arena-unauth-card/ArenaUnauthCard.ts
import { ChangeDetectionStrategy, Component, computed, contentChild, input } from '@angular/core';
import type { ArenaHeadingLevel } from '../../../Api.generated';
import { ArenaCard } from '../arena-card/ArenaCard';
import { ArenaBrand, ArenaFooter } from '../../../ProjectionMarkers';
import { arenaUnauthCardStyles } from './ArenaUnauthCard.variants';
import manifest from './ArenaUnauthCard.classes.generated';

@Component({
  selector: 'arena-unauth-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.data-arena-part]': 'parts.root',
    '[attr.title]': 'null',
  },
  imports: [ArenaCard],
  template: `
    <arena-card>
      <div [class]="styles().body()" [attr.data-arena-part]="parts.body" data-arena-boundary>
        @if (brand()) {
          <div [class]="styles().brand()" [attr.data-arena-part]="parts.brand" data-arena-boundary><ng-content select="[brand]" /></div>
        }
        @if (eyebrow(); as label) {
          <div [class]="styles().eyebrow()" [attr.data-arena-part]="parts.eyebrow">{{ label }}</div>
        }
        @if (title(); as heading) {
          @switch (headingLevel()) {
            @case ('h1') { <h1 [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ heading }}</h1> }
            @case ('h2') { <h2 [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ heading }}</h2> }
            @case ('h3') { <h3 [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ heading }}</h3> }
            @case ('h4') { <h4 [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ heading }}</h4> }
            @default { <div [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ heading }}</div> }
          }
        }
        <ng-content />
        @if (footer()) {
          <div [class]="styles().footer()" [attr.data-arena-part]="parts.footer" data-arena-boundary><ng-content select="[footer]" /></div>
        }
      </div>
    </arena-card>
  `,
})
export class ArenaUnauthCard {
  protected readonly parts = manifest.parts;

  /** Mono crimson microlabel: the product, not the task. */
  readonly eyebrow = input<string>();
  /** The task. "Welcome back", "Check your inbox". */
  readonly title = input<string>();
  /** Which rung of the document outline the title takes. Only the element changes: the title's class is the same at every value, so the render is identical and no appearance follows from it. It defaults to `h2` because this title is drawn in the section register rather than the card one, so the outline follows the register the same way every other title on the ladder does. A signed-out screen whose only title is this one says `h1` and gets the page's one heading, which is the case the member exists for. `none` takes the title out of the outline entirely; with no title there is no heading either way. */
  readonly headingLevel = input<ArenaHeadingLevel, ArenaHeadingLevel | undefined>(
    'h2', { transform: (value) => value ?? 'h2' },
  );

  protected readonly brand = contentChild(ArenaBrand);
  protected readonly footer = contentChild(ArenaFooter);

  protected readonly styles = computed(() => arenaUnauthCardStyles());
}

// frameworks/react/components/display/arena-unauth-card/ArenaUnauthCard.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaUnauthCard.classes.generated.ts';
import { ArenaCard } from '../arena-card/ArenaCard.tsx';

import type { ArenaHeadingLevel } from '../../../Api.generated';

export interface ArenaUnauthCardProps {

  /** The brand lock-up above the panel's content. An ArenaAppLogo, in practice. */
  brand?: React.ReactNode;

  /** Mono crimson microlabel: the product, not the task. */
  eyebrow?: string;

  /** The task. "Welcome back", "Check your inbox". */
  title?: string;

  /** Which rung of the document outline the title takes. Only the element changes: the title's class is the same at every value, so the render is identical and no appearance follows from it. It defaults to `h2` because this title is drawn in the section register rather than the card one, so the outline follows the register the same way every other title on the ladder does. A signed-out screen whose only title is this one says `h1` and gets the page's one heading, which is the case the member exists for. `none` takes the title out of the outline entirely; with no title there is no heading either way. */
  headingLevel?: ArenaHeadingLevel;

  /** Centred muted line below the content: a recovery link, a legal note. */
  footer?: React.ReactNode;

  /** The fields, composed from ArenaInput and ArenaButton. */
  children?: React.ReactNode;
}


const unauthStyles = arenaStyles(manifest);

export function ArenaUnauthCard({ brand, eyebrow, title, headingLevel = 'h2', footer, children }: ArenaUnauthCardProps) {
  const styles = unauthStyles();
  const Heading = headingLevel === 'none' ? 'div' : headingLevel;
  return (
    <div className={styles.root()} data-arena-part={manifest.parts.root}>
      <ArenaCard>
        <div className={styles.body()} data-arena-part={manifest.parts.body} data-arena-boundary="">
          {brand && <div className={styles.brand()} data-arena-part={manifest.parts.brand} data-arena-boundary="">{brand}</div>}
          {eyebrow && <div className={styles.eyebrow()} data-arena-part={manifest.parts.eyebrow}>{eyebrow}</div>}
          {title && <Heading className={styles.title()} data-arena-part={manifest.parts.title}>{title}</Heading>}
          {children}
          {footer && <div className={styles.footer()} data-arena-part={manifest.parts.footer} data-arena-boundary="">{footer}</div>}
        </div>
      </ArenaCard>
    </div>
  );
}
