// frameworks/react/components/forms/arena-select/ArenaSelect.tsx
import React, { useId } from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaSelect.classes.generated.ts';

import type { ArenaSelectOption } from '../../../Api.generated';

export type { ArenaSelectOption };
export interface ArenaSelectProps {

  /** Field label above the control. */
  label?: string;

  /** An empty-valued first option, drawn before the choices and unselectable once a real one is made -- "Choose a customer". It is an option rather than an attribute because a native select has no placeholder, and it is what makes "nothing chosen yet" distinguishable from "the first choice". */
  placeholder?: string;

  /** The choices, drawn as native options. */
  options?: readonly ArenaSelectOption[];

  /** The selected option's value. */
  value?: string;

  /** Blocks the control and dims it. */
  disabled?: boolean;

  /** Must have a value for the form to submit. */
  required?: boolean;

  /** A line of help under the field. */
  hint?: string;

  /** Controlled error message. It is the whole validation surface here, unlike ArenaInput, which also takes a `validate` function: a native select offers a closed list, so there is no value to parse and nothing for a validator to reject that the options did not already prevent. */
  error?: string;

  /** Force the valid (green check) state. */
  valid?: boolean;

  /** Phosphor class name drawn at the field's start. */
  icon?: string;

  /** Submitted with the form. */
  name?: string;


  /** A different option was chosen; carries its value. */
  onChange?: (value: string) => void;
}

const arenaSelectStyles = arenaStyles(manifest);

export function ArenaSelect({
  label, placeholder, options = [], value, onChange, disabled = false, required = false,
  hint, error, valid = false, icon, name,
}: ArenaSelectProps) {
  const selectId = `select-${useId().replace(/:/g, '')}`;
  const noteId = `${selectId}-note`;

  const hasError = Boolean(error);
  const styles = arenaSelectStyles({
    state: hasError ? 'error' : valid ? 'valid' : 'neutral',
    disabled,
    hasIcon: Boolean(icon),
  });

  return (
    <div className={styles.root()} data-arena-part={manifest.parts.root}>
      {label && <label htmlFor={selectId} className={styles.label()} data-arena-part={manifest.parts.label}>{label}</label>}
      <div className={styles.wrap()} data-arena-part={manifest.parts.wrap}>
        {icon && <i className={`${icon} ${styles.iconWrap()}`} data-arena-part={manifest.parts.iconWrap} aria-hidden="true" />}
        <select id={selectId} value={value} onChange={(e) => onChange && onChange(e.target.value)} disabled={disabled}
          required={required} name={name}
          aria-invalid={hasError || undefined} aria-describedby={error || hint ? noteId : undefined}
          className={styles.field()} data-arena-part={manifest.parts.field}>
          {placeholder && <option value="" disabled>{placeholder}</option>}
          {options.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
        </select>
        <span className={styles.caret()} data-arena-part={manifest.parts.caret} aria-hidden="true">▾</span>
      </div>
      {error
        ? <span id={noteId} className={styles.error()} data-arena-part={manifest.parts.error}>{error}</span>
        : hint && <span id={noteId} className={styles.hint()} data-arena-part={manifest.parts.hint}>{hint}</span>}
    </div>
  );
}

// frameworks/angular/components/forms/arena-select/ArenaSelect.ts
import {
  ChangeDetectionStrategy, Component, booleanAttribute, computed, input, output,
} from '@angular/core';
import type { ArenaSelectOption } from '../../../Api.generated';
import { arenaSelectStyles } from './ArenaSelect.variants';
import manifest from './ArenaSelect.classes.generated';

let nextId = 0;

@Component({
  selector: 'arena-select',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.data-arena-part]': 'parts.root',
    '[attr.name]': 'null',
  },
  template: `
    @if (label(); as text) {
      <label [class]="styles().label()" [attr.data-arena-part]="parts.label" [attr.for]="selectId">{{ text }}</label>
    }
    <div [class]="styles().wrap()" [attr.data-arena-part]="parts.wrap">
      @if (icon(); as glyph) {
        <i [class]="styles().iconWrap() + ' ' + glyph" [attr.data-arena-part]="parts.iconWrap" aria-hidden="true"></i>
      }
      <select [class]="styles().field()" [attr.data-arena-part]="parts.field" [attr.id]="selectId" [disabled]="disabled()"
              [required]="required()" [attr.name]="name()"
              [attr.aria-invalid]="hasError()" [attr.aria-describedby]="describedBy()"
              (change)="onChange($event)">
        @if (placeholder(); as text) {
          <option value="" [disabled]="true" [selected]="!value()">{{ text }}</option>
        }
        @for (option of options(); track option.value) {
          <option [value]="option.value" [selected]="option.value === value()">{{ option.label }}</option>
        }
      </select>
      <span [class]="styles().caret()" [attr.data-arena-part]="parts.caret" aria-hidden="true">&#9662;</span>
    </div>
    @if (error(); as message) {
      <span [class]="styles().error()" [attr.data-arena-part]="parts.error" [attr.id]="noteId">{{ message }}</span>
    } @else if (hint(); as text) {
      <span [class]="styles().hint()" [attr.data-arena-part]="parts.hint" [attr.id]="noteId">{{ text }}</span>
    }
  `,
})
export class ArenaSelect {
  protected readonly parts = manifest.parts;

  /** Field label above the control. */
  readonly label = input<string>();
  /** An empty-valued first option, drawn before the choices and unselectable once a real one is made -- "Choose a customer". It is an option rather than an attribute because a native select has no placeholder, and it is what makes "nothing chosen yet" distinguishable from "the first choice". */
  readonly placeholder = input<string>();
  /** The choices, drawn as native options. */
  readonly options = input<readonly ArenaSelectOption[], readonly ArenaSelectOption[] | undefined>(
    [],
    { transform: (value) => value ?? [] },
  );
  /** The selected option's value. */
  readonly value = input<string>();
  /** Blocks the control and dims it. */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Must have a value for the form to submit. */
  readonly required = input(false, { transform: booleanAttribute });
  /** A line of help under the field. */
  readonly hint = input<string>();
  /** Controlled error message. It is the whole validation surface here, unlike ArenaInput, which also takes a `validate` function: a native select offers a closed list, so there is no value to parse and nothing for a validator to reject that the options did not already prevent. */
  readonly error = input<string>();
  /** Force the valid (green check) state. */
  readonly valid = input(false, { transform: booleanAttribute });
  /** Phosphor class name drawn at the field's start. */
  readonly icon = input<string>();
  /** Submitted with the form. */
  readonly name = input<string>();
  /** A different option was chosen; carries its value. */
  readonly change = output<string>();

  protected readonly selectId = `arena-select-${nextId++}`;
  protected readonly noteId = `${this.selectId}-note`;

  protected readonly hasError = computed(() => Boolean(this.error()));

  protected readonly describedBy = computed(() => (this.error() || this.hint() ? this.noteId : null));

  protected readonly styles = computed(() => arenaSelectStyles({
    disabled: this.disabled(),
    hasIcon: Boolean(this.icon()),
    state: this.hasError() ? 'error' : this.valid() ? 'valid' : 'neutral',
  }));

  protected onChange(event: Event): void {
    event.stopPropagation();
    this.change.emit((event.target as HTMLSelectElement).value);
  }
}
