// scripts/lib/react/playground-react.ts
/* Emits a React demo entry from the layer-neutral model. Every member is written out as its
 * own attribute rather than spread, so the two layers' entries read as translations of each
 * other; Angular has no spread and this side has no reason to diverge from it. A literal
 * reaches JSX through JSON.stringify inside an expression container, which is one escaping
 * rule for every form rather than one per type. renderNode spells a bare text node for
 * CHILDREN position, where a container is what carries a string, and expressionNode is the
 * same node for EXPRESSION position, where the caller has already opened one: the two list
 * builders place their items there, so spelling it the first way nests a container in a
 * container and the file stops parsing. */

import { playgroundPage, sheetLinks, UP } from '../arena/playground-page.ts';
import { bindingName } from '../arena/api-surface.ts';
import { placeOf, SUBJECT } from '../arena/playground-model.ts';
import type { FixtureChild, FixtureNode, Knob, Place, Places, PlaygroundEvent, PlaygroundModel }
  from '../arena/playground-model.ts';

export const PRIMITIVES = new Set(['string', 'number', 'boolean']);

export const VALIDATOR_TABLE = `
const VALIDATORS: Record<string, (value: string) => string> = {
  nonEmpty: (value: string) => (value.trim().length === 0 ? 'Required.' : ''),
  alwaysInvalid: () => 'Never valid, on purpose.',
};

function validatorFor(name: string | undefined): ((value: string) => string) | undefined {
  return name === undefined ? undefined : VALIDATORS[name];
}
`;

export function typeExpr(knob: Knob) {
  if (knob.form === 'slot') return knob.control === 'slotText' ? 'string' : 'boolean';
  if (knob.form === 'array') return `${knob.type}[]`;
  if (knob.form === 'functionInput') return 'string';
  return knob.type;
}

export function contractTypes(model: { knobs: Knob[] }) {
  const names = new Set();
  for (const knob of model.knobs) {
    if (!knob.type) continue;
    if (knob.form === 'enum' || knob.form === 'object') names.add(knob.type);
    if (knob.form === 'array' && !PRIMITIVES.has(knob.type)) names.add(knob.type);
  }
  return [...names].sort();
}

export function importPath(place: Place) {
  return `../../${place.category}/${place.dir}/${place.name}.tsx`;
}

export function literal(value: unknown) {
  return `{${JSON.stringify(value)}}`;
}

export function attributes(members: Record<string, any> | undefined, indent: string) {
  return (Object.entries(members ?? {}) as [string, any][])
    .map(([name, value]) => `\n${indent}${name}=${literal(value)}`)
    .join('');
}

export function renderNode(node: FixtureNode, places: Places, depth: number): string {
  const pad = '  '.repeat(depth);
  if (typeof node.text === 'string' && !node.element) return `${pad}{${JSON.stringify(node.text)}}`;
  if (typeof node.element === 'string' || typeof node.text === 'string') {
    const tag = node.element ?? 'span';
    const attrs = attributes(node.attrs, `${pad}  `);
    if (node.text === undefined) return `${pad}<${tag}${attrs} />`;
    return `${pad}<${tag}${attrs}>{${JSON.stringify(node.text)}}</${tag}>`;
  }

  const place = placeOf(places, node.component);
  const slots = node.slots ?? {};
  const named = (Object.entries(slots) as [string, FixtureNode[]][])
    .filter(([name]) => name !== 'content');
  const attrs = attributes(node.members, `${pad}  `)
    + named.map(([name, list]) => `\n${pad}  ${name}={${inlineList(list, places, depth + 1)}}`).join('');
  const children = (slots.content ?? []) as FixtureNode[];
  if (children.length === 0) return `${pad}<${place.name}${attrs} />`;
  return `${pad}<${place.name}${attrs}>\n${children.map((one) => renderNode(one, places, depth + 1)).join('\n')}\n${pad}</${place.name}>`;
}

export function keyed(rendered: string, index: number) {
  return rendered.replace(/^(<[A-Za-z][\w.]*)/, `$1 key={${index}}`);
}

export function expressionNode(node: FixtureNode, places: Places, depth: number) {
  if (typeof node.text === 'string' && !node.element) return JSON.stringify(node.text);
  return renderNode(node, places, depth);
}

export function inlineList(list: FixtureNode[], places: Places, depth: number) {
  const rendered = list.map((one) => expressionNode(one, places, depth).trim());
  if (rendered.length === 1) return rendered[0];
  return `[${rendered.map((one, i) => keyed(one, i)).join(', ')}]`;
}

export function slotChildren(knob: Knob, places: Places, depth: number) {
  const pad = '  '.repeat(depth);
  if (knob.control === 'slotText') return `${pad}{k.${knob.member}}`;
  return `${pad}{k.${knob.member} ? ${listExpression(knob.nodes ?? [], places, depth)} : undefined}`;
}

export function listExpression(nodes: FixtureNode[], places: Places, depth: number) {
  const pad = '  '.repeat(depth);
  const rendered = nodes.map((one) => expressionNode(one, places, depth + 1));
  if (rendered.length === 1) return `(\n${rendered[0]}\n${pad})`;
  return `[\n${rendered.map((one, i) => keyed(one.trimStart(), i).split('\n').map((l, n) => (n === 0 ? `${pad}  ${l}` : l)).join('\n')).join(',\n')},\n${pad}]`;
}

export function slotAttribute(knob: Knob, places: Places, pad: string, depth: number) {
  if (knob.control === 'slotText') {
    return `\n${pad}${knob.member}={k.${knob.member} === undefined ? undefined : <React.Fragment>{k.${knob.member}}</React.Fragment>}`;
  }
  return `\n${pad}${knob.member}={k.${knob.member} ? ${listExpression(knob.nodes ?? [], places, depth)} : undefined}`;
}

export function memberAttribute(knob: Knob, pad: string) {
  if (knob.form === 'functionInput') return `\n${pad}${knob.member}={validatorFor(k.${knob.member})}`;
  return `\n${pad}${knob.member}={k.${knob.member}}`;
}

export function eventAttribute(event: PlaygroundEvent, pad: string) {
  const bound = bindingName(event.name, 'event', 'react');
  return event.payload
    ? `\n${pad}${bound}={(payload) => play.fire(${JSON.stringify(event.name)}, payload)}`
    : `\n${pad}${bound}={() => play.fire(${JSON.stringify(event.name)})}`;
}

export function renderSubject(model: PlaygroundModel, places: Places, depth: number) {
  const pad = '  '.repeat(depth);
  const inner = `${pad}  `;
  const name = model.component;
  const content = model.knobs.find((knob) => knob.form === 'slot' && knob.member === 'content');

  const attrs = model.knobs
    .filter((knob) => knob.form !== 'slot')
    .map((knob) => memberAttribute(knob, inner))
    .concat(model.knobs
      .filter((knob) => knob.form === 'slot' && knob.member !== 'content')
      .map((knob) => slotAttribute(knob, places, inner, depth + 1)))
    .concat(model.events.map((event) => eventAttribute(event, inner)))
    .join('');

  if (!content) return `${pad}<${name}${attrs} />`;
  return `${pad}<${name}${attrs}>\n${slotChildren(content, places, depth + 1)}\n${pad}</${name}>`;
}

export function holdsSubject(node: FixtureChild): boolean {
  if (node === '$subject') return true;
  if (node === null || typeof node !== 'object') return false;
  return (Object.values(node.slots ?? {}) as any[][]).some((list) => list.some((one) => holdsSubject(one)));
}

export function renderTree(model: PlaygroundModel, places: Places, depth: number) {
  if (model.host === null) return renderSubject(model, places, depth);
  const wrap = (node: FixtureNode | typeof SUBJECT, level: number): string => {
    const pad = '  '.repeat(level);
    if (node === '$subject') return renderSubject(model, places, level);
    if (!holdsSubject(node)) return renderNode(node, places, level);
    const place = placeOf(places, node.component);
    const slots = node.slots ?? {};
    const named = (Object.entries(slots) as [string, FixtureNode[]][])
      .filter(([name]) => name !== 'content');
    const attrs = attributes(node.members, `${pad}  `)
      + named.map(([name, list]) => `\n${pad}  ${name}={${inlineList(list, places, level + 1)}}`).join('');
    const children = ((slots.content ?? []) as FixtureChild[])
      .filter((one): one is FixtureNode | typeof SUBJECT => one !== null)
      .map((one) => wrap(one, level + 1)).join('\n');
    if (children.length === 0) return `${pad}<${place.name}${attrs} />`;
    return `${pad}<${place.name}${attrs}>\n${children}\n${pad}</${place.name}>`;
  };
  return wrap(model.host, depth);
}

export function knobsInterface(model: { knobs: Knob[] }) {
  const rows = model.knobs.map((knob) => {
    const optional = knob.bind === 'optional' ? '?' : '';
    return `  ${knob.member}${optional}: ${typeExpr(knob)};`;
  });
  return `interface Knobs {\n${rows.join('\n')}\n}`;
}

export function validatorTable(model: { knobs: Knob[] }) {
  return model.knobs.some((knob) => knob.form === 'functionInput') ? VALIDATOR_TABLE : '';
}

export function reactEntry(model: PlaygroundModel, places: Places, banner: string) {
  const types = contractTypes(model);
  const components = [...new Set([model.component, ...model.uses])]
    .map((name) => {
      const place = placeOf(places, name);
      return `import { ${name} } from '${place.self ? `./${name}.tsx` : importPath(place)}';`;
    });

  const imports = [
    "import React from 'react';",
    "import { createRoot } from 'react-dom/client';",
    "import { Playground } from '../../../playground/Playground.tsx';",
    "import { usePlayground } from '../../../playground/PlaygroundState.ts';",
    "import type { KnobModel } from '../../../playground/PlaygroundCodec.generated.ts';",
    types.length > 0 ? `import type { ${types.join(', ')} } from '../../../Api.generated.ts';` : '',
    ...components,
  ].filter(Boolean);

  return `${banner}
${imports.join('\n')}

const MODEL: KnobModel = ${JSON.stringify(model, null, 2)};

${knobsInterface(model)}
${validatorTable(model)}
function Demo() {
  const play = usePlayground(MODEL);
  const k = play.values as unknown as Knobs;
  return (
    <Playground model={MODEL} play={play}>
${renderTree(model, places, 3)}
    </Playground>
  );
}

createRoot(document.getElementById('root')!).render(<Demo />);
`;
}

export function reactPage(model: PlaygroundModel, banner: string) {
  const importmap = {
    imports: {
      react: `${UP}frameworks/react/vendor/React.generated.js`,
      'react/jsx-runtime': `${UP}frameworks/react/vendor/ReactJsxRuntime.generated.js`,
      'react-dom/client': `${UP}frameworks/react/vendor/ReactDomClient.generated.js`,
    },
  };
  return playgroundPage({
    component: model.component,
    banner,
    head: `${sheetLinks(model)}\n`
      + `<script type="importmap">\n${JSON.stringify(importmap, null, 2)}\n</script>\n`,
    mount: '<div id="root"></div>',
    script: `${model.component}.demo.entry.generated.js`,
  });
}

// scripts/lib/angular/playground-angular.ts
/* Emits an Angular demo entry from the layer-neutral model. Two rules earn their keep here.
 * A literal inside a fixture node becomes a typed class field rather than template text,
 * because inlining it would mean escaping both the template's quotes and the surrounding
 * backtick's ${; and a named slot is wrapped in @if, because a host querying contentChild
 * counts an empty marked element as filled, so blanking the text would render a header in
 * this layer and none in the other. A marker directive is read from the layer's own source
 * rather than listed here, so a new one joins without an edit. */

import { playgroundPage, sheetLinks } from '../arena/playground-page.ts';
import { kebab } from '../../utils/case.ts';
import { placeOf, SUBJECT } from '../arena/playground-model.ts';
import { captured } from '../../utils/captures.ts';
import type { MemberSpec } from '../arena/contract-shapes.ts';
import type { FixtureNode, Knob, Place, Places, PlaygroundEvent, PlaygroundModel }
  from '../arena/playground-model.ts';

type Field = { name: string; type: string; value: unknown; member: string; node: FixtureNode };

type FieldRef = Pick<Field, 'name' | 'member' | 'node'>;

type Markers = Map<string, string>;

export const PRIMITIVES = new Set(['string', 'number', 'boolean']);

export const VOID_ELEMENTS = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'source', 'track', 'wbr']);

export const VALIDATOR_TABLE = `
const VALIDATORS: Record<string, (value: string) => string> = {
  nonEmpty: (value: string) => (value.trim().length === 0 ? 'Required.' : ''),
  alwaysInvalid: () => 'Never valid, on purpose.',
};

function validatorFor(name: string | undefined): ((value: string) => string) | undefined {
  return name === undefined ? undefined : VALIDATORS[name];
}
`;

export const MARKERS_SOURCE = 'frameworks/angular/ProjectionMarkers.ts';

export function markerNames(source: string): Markers {
  const found: Markers = new Map();
  for (const m of source.matchAll(/selector:\s*'\[(\w+)\]'[^}]*}\)\s*export class (\w+)/g)) {
    found.set(captured(m), captured(m, 2));
  }
  return found;
}

export function selector(name: string) {
  return kebab(name);
}

export function typeExpr(knob: Knob) {
  if (knob.form === 'slot') return knob.control === 'slotText' ? 'string' : 'boolean';
  if (knob.form === 'array') return `${knob.type}[]`;
  if (knob.form === 'functionInput') return 'string';
  return knob.type;
}

export function contractTypes(model: PlaygroundModel, fields: Field[]) {
  const names = new Set();
  for (const knob of model.knobs) {
    if (!knob.type) continue;
    if (knob.form === 'enum' || knob.form === 'object') names.add(knob.type);
    if (knob.form === 'array' && !PRIMITIVES.has(knob.type)) names.add(knob.type);
  }
  for (const field of fields) if (field.type && !PRIMITIVES.has(field.type.replace('[]', ''))) {
    names.add(field.type.replace('[]', ''));
  }
  return [...names].sort();
}

export function importPath(place: Place) {
  return `../../${place.category}/${place.dir}/${place.name}`;
}

export function fieldTypeFor(spec: MemberSpec): string {
  if (spec.form === 'array') return `${spec.of}[]`;
  if (spec.form === 'primitive' || spec.form === 'enum' || spec.form === 'object') return spec.type ?? 'unknown';
  return 'unknown';
}

export function staticAttribute(value: unknown) {
  return typeof value === 'string';
}

export function attributeText(value: unknown) {
  return escapeText(String(value)).replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}

export function collectFields(node: FixtureNode | string | null, contracts: Map<string, any>,
  into: Field[], prefix: string): Field[] {
  if (node === '$subject' || node === null || typeof node !== 'object') return into;
  if (typeof node.component === 'string') {
    const api = contracts.get(node.component)?.api ?? {};
    for (const [member, value] of Object.entries(node.members ?? {}) as [string, any][]) {
      if (staticAttribute(value)) continue;
      const name = `${prefix}${node.component}${member.slice(0, 1).toUpperCase()}${member.slice(1)}${into.length}`;
      into.push({ name, type: fieldTypeFor(api[member] ?? {}), value, member, node });
    }
    for (const list of Object.values(node.slots ?? {}) as any[][]) {
      for (const one of list) collectFields(one, contracts, into, prefix);
    }
  }
  return into;
}

export function fieldFor(fields: FieldRef[],
  node: FixtureNode, member: string) {
  return fields.find((one) => one.node === node && one.member === member)?.name;
}

export function nodeAttributes(node: FixtureNode, fields: FieldRef[]) {
  return (Object.entries(node.members ?? {}) as [string, any][])
    .map(([member, value]) => (staticAttribute(value)
      ? ` ${member}="${attributeText(value)}"`
      : ` [${member}]="${fieldFor(fields, node, member)}"`))
    .join('');
}

export function renderNode(node: FixtureNode, places: Places, fields: FieldRef[],
  markers: Markers, depth: number, imports: Set<string>): string {
  const pad = '  '.repeat(depth);
  if (typeof node.text === 'string' && !node.element) return `${pad}${escapeText(node.text)}`;
  if (typeof node.element === 'string' || typeof node.text === 'string') {
    const tag = node.element ?? 'span';
    const attrs = Object.entries(node.attrs ?? {}).map(([name, value]) => ` ${name}="${String(value)}"`).join('');
    if (VOID_ELEMENTS.has(tag)) return `${pad}<${tag}${attrs} />`;
    if (node.text === undefined) return `${pad}<${tag}${attrs}></${tag}>`;
    return `${pad}<${tag}${attrs}>${escapeText(node.text)}</${tag}>`;
  }

  const place = placeOf(places, node.component);
  const tag = selector(place.name);
  imports.add(place.name);
  const slots = node.slots ?? {};
  const attrs = nodeAttributes(node, fields);
  const children = [];
  for (const [name, list] of Object.entries(slots) as [string, any[]][]) {
    for (const one of list) {
      const marked = name === 'content' ? '' : ` ${name}`;
      const marker = markers.get(name);
      if (marked && marker) imports.add(marker);
      children.push(projected(one, places, fields, markers, depth + 1, imports, marked));
    }
  }
  if (children.length === 0) return `${pad}<${tag}${attrs}></${tag}>`;
  return `${pad}<${tag}${attrs}>\n${children.join('\n')}\n${pad}</${tag}>`;
}

export function projected(node: FixtureNode, places: Places, fields: FieldRef[],
  markers: Markers, depth: number, imports: Set<string>, marked: string) {
  const pad = '  '.repeat(depth);
  if (!marked) return renderNode(node, places, fields, markers, depth, imports);
  if (typeof node.text === 'string' && !node.element) return `${pad}<span${marked}>${escapeText(node.text)}</span>`;
  const rendered = renderNode(node, places, fields, markers, depth, imports).trimStart();
  return `${pad}${rendered.replace(/^(<[\w-]+)/, `$1${marked}`)}`;
}

export function escapeText(text: string) {
  return text.replace(/\{\{/g, '{{ "{{" }}').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

export function slotBlock(knob: Knob, places: Places, fields: FieldRef[],
  markers: Markers, depth: number, imports: Set<string>, marked: string) {
  const pad = '  '.repeat(depth);
  if (knob.control === 'slotText') {
    const body = marked ? `<span${marked}>{{ k().${knob.member} }}</span>` : `{{ k().${knob.member} }}`;
    return `${pad}@if (k().${knob.member} !== undefined) {\n${pad}  ${body}\n${pad}}`;
  }
  const nodes = ((knob.nodes ?? []) as FixtureNode[])
    .map((one) => projected(one, places, fields, markers, depth + 1, imports, marked));
  if (!marked) return `${pad}@if (k().${knob.member}) {\n${nodes.join('\n')}\n${pad}}`;
  return nodes.map((one: string) => `${pad}@if (k().${knob.member}) {\n${one}\n${pad}}`).join('\n');
}

export function renderSubject(model: PlaygroundModel, places: Places,
  fields: FieldRef[],
  markers: Markers, depth: number, imports: Set<string>) {
  const pad = '  '.repeat(depth);
  const inner = `${pad}  `;
  const tag = selector(model.component);
  imports.add(model.component);

  const attrs = model.knobs
    .filter((knob) => knob.form !== 'slot')
    .map((knob) => (knob.form === 'functionInput'
      ? `\n${inner}[${knob.member}]="validatorFor(k().${knob.member})"`
      : `\n${inner}[${knob.member}]="k().${knob.member}"`))
    .concat(model.events.map((event) => (event.payload
      ? `\n${inner}(${event.name})="play.fire('${event.name}', $event)"`
      : `\n${inner}(${event.name})="play.fire('${event.name}')"`)))
    .join('');

  const slots = model.knobs.filter((knob) => knob.form === 'slot');
  if (slots.length === 0) return `${pad}<${tag}${attrs}></${tag}>`;

  const blocks = slots.map((knob) => {
    const marked = knob.member === 'content' ? '' : ` ${knob.member}`;
    const draws = knob.control === 'slotText' || (knob.nodes ?? []).length > 0;
    const marker = markers.get(knob.member);
    if (marked && draws && marker) imports.add(marker);
    return slotBlock(knob, places, fields, markers, depth + 1, imports, marked);
  });
  return `${pad}<${tag}${attrs}>\n${blocks.join('\n')}\n${pad}</${tag}>`;
}

export function holdsSubject(node: FixtureNode | string | null): boolean {
  if (node === '$subject') return true;
  if (node === null || typeof node !== 'object') return false;
  return (Object.values(node.slots ?? {}) as any[][]).some((list) => list.some((one) => holdsSubject(one)));
}

export function renderTree(model: PlaygroundModel, places: Places, fields: FieldRef[],
  markers: Markers, depth: number, imports: Set<string>) {
  if (model.host === null) return renderSubject(model, places, fields, markers, depth, imports);
  const wrap = (node: FixtureNode | typeof SUBJECT, level: number): string => {
    const pad = '  '.repeat(level);
    if (node === '$subject') return renderSubject(model, places, fields, markers, level, imports);
    if (!holdsSubject(node)) return renderNode(node, places, fields, markers, level, imports);
    const place = placeOf(places, node.component);
    const tag = selector(place.name);
    imports.add(place.name);
    const attrs = nodeAttributes(node, fields);
    const children = [];
    for (const [name, list] of Object.entries(node.slots ?? {}) as [string, any[]][]) {
      for (const one of list) {
        const marked = name === 'content' ? '' : ` ${name}`;
        const marker = markers.get(name);
        if (marked && marker) imports.add(marker);
        children.push(holdsSubject(one)
          ? wrap(one, level + 1)
          : projected(one, places, fields, markers, level + 1, imports, marked));
      }
    }
    if (children.length === 0) return `${pad}<${tag}${attrs}></${tag}>`;
    return `${pad}<${tag}${attrs}>\n${children.join('\n')}\n${pad}</${tag}>`;
  };
  return wrap(model.host, depth);
}

export function knobsInterface(model: { knobs: Knob[] }) {
  const rows = model.knobs.map((knob) => {
    const optional = knob.bind === 'optional' ? '?' : '';
    return `  ${knob.member}${optional}: ${typeExpr(knob)};`;
  });
  return `interface Knobs {\n${rows.join('\n')}\n}`;
}

export function validatorTable(model: { knobs: Knob[] }) {
  return model.knobs.some((knob) => knob.form === 'functionInput') ? VALIDATOR_TABLE : '';
}

export function angularEntry(model: PlaygroundModel, places: Places,
  contracts: Map<string, any>, markersSource: string, banner: string) {
  const markers = markerNames(markersSource);
  const fields: Field[] = [];
  collectFields(model.host, contracts, fields, 'host');
  for (const knob of model.knobs) {
    for (const node of knob.nodes ?? []) collectFields(node, contracts, fields, 'slot');
  }

  const imports = new Set<string>();
  const template = renderTree(model, places, fields, markers, 3, imports);
  const used = [...imports].sort();
  const types = contractTypes(model, fields);

  const componentImports = [...new Set(used)]
    .filter((name) => places.has(name))
    .map((name) => {
      const place = placeOf(places, name);
      return `import { ${name} } from '${place.self ? `./${name}` : importPath(place)}';`;
    });
  const markerImports = used.filter((name) => !places.has(name));

  const fieldRows = fields.map(
    (field) => `  protected readonly ${field.name}: ${field.type} = ${JSON.stringify(field.value)};`,
  );

  return `${banner}import * as angularJitCompiler from '@angular/compiler';
import { ChangeDetectionStrategy, Component, computed, provideZonelessChangeDetection } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { Playground } from '../../../playground/Playground';
import { PlaygroundStore } from '../../../playground/PlaygroundState';
import type { KnobModel } from '../../../playground/PlaygroundCodec.generated';
${types.length > 0 ? `import type { ${types.join(', ')} } from '../../../Api.generated';\n` : ''}${
  markerImports.length > 0 ? `import { ${markerImports.join(', ')} } from '../../../ProjectionMarkers';\n` : ''
}${componentImports.join('\n')}

const MODEL: KnobModel = ${JSON.stringify(model, null, 2)};

${knobsInterface(model)}
${validatorTable(model)}
@Component({
  selector: 'demo-root',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [Playground, ${used.join(', ')}],
  template: \`
    <demo-playground [play]="play">
${template}
    </demo-playground>
  \`,
})
class Demo {
  protected readonly play = new PlaygroundStore(MODEL);
  protected readonly k = computed(() => this.play.values() as unknown as Knobs);
${model.knobs.some((knob) => knob.form === 'functionInput') ? '  protected readonly validatorFor = validatorFor;\n' : ''}
${fieldRows.length > 0 ? `${fieldRows.join('\n')}\n` : ''}}

/* @angular/* ships partially compiled and nothing here runs the Angular linker, so an injectable
 * like PlatformLocation resolves through the JIT fallback and the compiler has to be in this
 * bundle. It is READ rather than imported for its side effect alone: the package declares its
 * side effects as the one path "./fesm2022/compiler.mjs", which a bundler holding the resolved
 * file in the host spelling does not match on Windows, so it drops the bare import as dead. The
 * page then loads its entry, throws at bootstrap and renders an empty document. */
Reflect.set(globalThis, 'arenaAngularJitCompiler', angularJitCompiler);

bootstrapApplication(Demo, { providers: [provideZonelessChangeDetection()] });
`;
}

export function angularPage(model: PlaygroundModel, banner: string) {
  return playgroundPage({
    component: model.component,
    banner,
    head: `${sheetLinks(model)}\n`,
    mount: '<demo-root></demo-root>',
    script: `../../../build/demo/js/${model.component}.demo.entry.generated.js`,
  });
}
