// frameworks/react/components/display/arena-calendar/ArenaCalendar.tsx
import type { ArenaCalendarEventProps, ArenaCalendarEventInjected } from '../arena-calendar-event/ArenaCalendarEvent.tsx';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useArenaContainerWidth, arenaReadBreakpoint } from '../../../UseArenaContainerWidth.ts';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaCalendar.classes.generated.ts';
import { arenaCatColor } from '../../../DataVisuals.ts';
import { useArenaLocale } from '../../../ArenaLocale.ts';
import { arenaPhrase } from '../../../Phrase.ts';
import { calendarGutterW, calendarHourH } from '../../../Tokens.generated.js';

import type { ArenaCalendarView, ArenaCatSlot } from '../../../Api.generated';

export type { ArenaCatSlot };

export interface ArenaCalendarProps {

  /** One ArenaCalendarEvent per event. ArenaCalendar reads each one's start, end and colorId and settles where the chip goes, what colour it takes and how the keyboard reaches it; the chip itself is ArenaCalendarEvent's. */
  children?: React.ReactNode;

  /** IANA zone name. Defaults to the reader's own resolved zone, which is right whenever the schedule belongs to the person looking at it. Pass it when the calendar has a zone of its own that differs (a Madrid timetable read from Tokyo), and when server-rendering, where the reader's zone is not knowable. */
  timeZone?: string;

  /** ISO date the view opens on. Defaults to today in `timeZone`; pass and change it to drive the date yourself. */
  anchorDate?: string;

  /** Omit to derive from the CONTAINER width: day below --bp-md, else week. */
  view?: ArenaCalendarView;

  /** HH:MM the grid starts at. Defaults to the earliest visible event's hour, floored. */
  dayStart?: string;

  /** HH:MM the grid ends at. */
  dayEnd?: string;

  /** 0 = Sunday … 6 = Saturday. */
  weekStartsOn?: number;

  /** Drop Sunday from the week unless an event falls on it. */
  hideEmptyWeekend?: boolean;

  /** Whether a day can be activated. A boolean rather than "is `dateClick` bound?", because Arena never derives what it draws from what a consumer listens for, and the same member `ArenaTableRow.interactive` and `ArenaCalendarEvent.interactive` are for the same reason; here the derived render was the day's own cursor, and the layers diverged on screen because of it. With it on, the day header is a <button> (the keyboard's route to the date, and the one element that already names it), and the column background takes a pointer cursor; with it off both are inert and the cursor says so. The default is false because a schedule someone only reads is the ordinary calendar, and a pointer cursor over days that answer nothing is the defect this member exists to end. */
  dayInteractive?: boolean;

  /** A day header or column background was activated; carries the ISO date. Never emitted unless `dayInteractive`. */
  onDateClick?: (isoDate: string) => void;

  /** The anchor moved via prev/Today/next; carries the new ISO date. A date rather than a delta, because Today is not a delta. */
  onRangeChange?: (isoDate: string) => void;

  /** Right-aligned in the toolbar, beside the range title. */
  actions?: React.ReactNode;
}

import {
  arenaAddDays, arenaDefaultDayStart, arenaFormatHM, arenaLayoutDay, arenaNowMinutes, arenaParseHM,
  arenaPlaceEvents, arenaRangeTitle, arenaShowsTime, arenaStacksActions, arenaStartOfWeek, arenaTodayIso, arenaWeekdayOf, arenaFormatDate, ARENA_DATE_OPTIONS,
} from './CalendarInternals.ts';

const TRACKS = (n: number) => `repeat(${n}, minmax(0, 1fr))`;

const arenaCalendarStyles = arenaStyles(manifest);

export function ArenaCalendar({
  children, timeZone, anchorDate, view,
  dayStart, dayEnd = '23:00', weekStartsOn = 1, hideEmptyWeekend = true,
  dayInteractive = false, onDateClick, onRangeChange, actions,
}: ArenaCalendarProps) {

  const locale = useArenaLocale();
  const zone = timeZone || Intl.DateTimeFormat().resolvedOptions().timeZone;
  const [ref, width] = useArenaContainerWidth<HTMLElement>();
  const [anchor, setAnchor] = useState(() => anchorDate || arenaTodayIso(zone));

  useEffect(() => { if (anchorDate) setAnchor(anchorDate); }, [anchorDate]);

  const [tick, setTick] = useState(0);
  useEffect(() => {
    const id = setInterval(() => setTick((n) => n + 1), 60000);
    return () => clearInterval(id);
  }, []);

  const narrow = width !== null && width < arenaReadBreakpoint('md');
  const activeView = view || (narrow ? 'day' : 'week');

  type EventElement = React.ReactElement<
  ArenaCalendarEventProps & Partial<ArenaCalendarEventInjected> & React.RefAttributes<HTMLElement>
  >;
  const kids = useMemo(
    () => React.Children.toArray(children)
      .filter((c): c is EventElement => React.isValidElement(c)),
    [children],
  );
  const events = useMemo(() => kids.map((k) => k.props), [kids]);
  const elementOf = useMemo(() => new Map(kids.map((k) => [k.props, k])), [kids]);

  const placed = useMemo(() => arenaPlaceEvents(events, zone), [events, zone]);

  const days = useMemo(() => {
    if (activeView === 'day') return [anchor];
    const first = arenaStartOfWeek(anchor, weekStartsOn);
    const all = Array.from({ length: 7 }, (_, i) => arenaAddDays(first, i));
    if (!hideEmptyWeekend) return all;

    return all.filter((d) => arenaWeekdayOf(d) !== 0 || placed.some((p) => p.dayIso === d));
  }, [activeView, anchor, weekStartsOn, hideEmptyWeekend, placed]);

  const visible = useMemo(() => placed.filter((p) => days.includes(p.dayIso)), [placed, days]);
  const byDay = useMemo(
    () => days.map((d) => arenaLayoutDay(visible.filter((p) => p.dayIso === d))),
    [days, visible],
  );

  const endMin = arenaParseHM(dayEnd, 23 * 60);
  const rawStart = dayStart !== undefined ? arenaParseHM(dayStart, 8 * 60) : arenaDefaultDayStart(visible);

  const startMin = Math.max(0, Math.min(rawStart, endMin - 60));

  const y = (min: number) => ((min - startMin) / 60) * calendarHourH;
  const hours: number[] = [];
  for (let m = Math.ceil(startMin / 60) * 60; m <= endMin; m += 60) hours.push(m);

  const slots = hours
    .map((m, i) => ({ start: m, end: (i + 1 < hours.length ? hours[i + 1] : endMin) ?? endMin }))
    .filter((s) => s.end > s.start);

  const slotFor = (cols: number) =>
    (width === null ? null : (width - calendarGutterW) / days.length / cols);

  const today = arenaTodayIso(zone);
  const nowMin = useMemo(() => arenaNowMinutes(zone), [zone, tick]);
  const showNow = days.includes(today) && nowMin >= startMin && nowMin <= endMin;

  const step = activeView === 'day' ? 1 : 7;
  const goto = (iso: string) => { setAnchor(iso); onRangeChange && onRangeChange(iso); };
  const activateDay = (iso: string) =>
    (dayInteractive ? () => { onDateClick && onDateClick(iso); } : undefined);

  const idBase = React.useId().replace(/:/g, '');
  const chips = useMemo(
    () => byDay.flatMap((day, di) => day.map((p, i) => ({ p, di, domId: `${idBase}-chip-${di}-${i}` }))),
    [byDay, idBase],
  );
  const ownedIds = (di: number) => chips.filter((c) => c.di === di).map((c) => c.domId).join(' ');

  const gridRef = useRef<HTMLDivElement | null>(null);

  const eventRefs = useRef(new Map<string, HTMLElement>());
  const [cursor, setCursor] = useState({ day: 0, hour: 0 });

  const curDay = Math.min(Math.max(cursor.day, 0), Math.max(days.length - 1, 0));
  const curHour = Math.min(Math.max(cursor.hour, 0), Math.max(slots.length - 1, 0));

  useEffect(() => {
    const g = gridRef.current;
    if (!g) return;
    const active = g.ownerDocument.activeElement;
    if (!active || !g.contains(active)) return;
    const cell = g.querySelector<HTMLElement>('[role="gridcell"][tabindex="0"]');
    if (cell && cell !== active) cell.focus();
  }, [curDay, curHour]);

  const focusCursorCell = () => {
    const cell = gridRef.current?.querySelector<HTMLElement>('[role="gridcell"][tabindex="0"]');
    if (cell) cell.focus();
  };

  const onGridKeyDown = (e: React.KeyboardEvent) => {
    const t = e.target;
    if (!(t instanceof Element)) return;

    if (t.getAttribute('role') === 'gridcell') {
      let day = curDay;
      let hour = curHour;
      if (e.key === 'ArrowLeft') day = Math.max(0, day - 1);
      else if (e.key === 'ArrowRight') day = Math.min(days.length - 1, day + 1);
      else if (e.key === 'ArrowUp') hour = Math.max(0, hour - 1);
      else if (e.key === 'ArrowDown') hour = Math.min(slots.length - 1, hour + 1);

      else if (e.key === 'Home') hour = 0;
      else if (e.key === 'End') hour = slots.length - 1;
      else if (e.key === 'Enter') {

        e.preventDefault();
        const s = slots[curHour];
        const hit = s && (byDay[curDay] || []).find((p) => p.startMin < s.end && p.endMin > s.start);
        const node = hit?.ev.id === undefined ? null : eventRefs.current.get(hit.ev.id);
        if (node) node.focus();
        return;
      } else return;

      e.preventDefault();

      if (day !== curDay || hour !== curHour) setCursor({ day, hour });
      return;
    }

    if (e.key === 'Escape') {
      e.preventDefault();
      focusCursorCell();
    }
  };

  const styles = arenaCalendarStyles({ dayInteractive });
  const range = arenaRangeTitle(days, locale.locale);
  const navBtn = (dir: number) => (
    <button type="button" aria-label={dir < 0 ? locale.calendarPrevious : locale.calendarNext}
      onClick={() => goto(arenaAddDays(anchor, dir * step))}
      className={styles.nav()} data-arena-part={manifest.parts.nav}>
      <i className={dir < 0 ? 'ph-bold ph-caret-left' : 'ph-bold ph-caret-right'} aria-hidden="true" />
    </button>
  );

  return (
    <section ref={ref} aria-label={arenaPhrase(locale.calendarRegion, { range })}
      className={styles.root()} data-arena-part={manifest.parts.root}>

      <div className={styles.toolbar()} data-arena-part={manifest.parts.toolbar}>
        {navBtn(-1)}
        <button type="button" onClick={() => goto(today)}
          className={styles.today()} data-arena-part={manifest.parts.today}>{locale.calendarToday}</button>
        {navBtn(1)}
        <div className={styles.heading()} data-arena-part={manifest.parts.heading}>
          {range}
        </div>
        {actions && <div className={styles.actions()} data-arena-part={manifest.parts.actions}>{actions}</div>}
      </div>

      <div className={styles.headStrip()} data-arena-part={manifest.parts.headStrip} style={{ gridTemplateColumns: TRACKS(days.length) }}>
        {days.map((d) => {
          const isToday = d === today;
          const DayHead = dayInteractive ? 'button' : 'div';
          return (
            <DayHead key={d} onClick={activateDay(d)}
              type={dayInteractive ? 'button' : undefined}
              aria-label={dayInteractive ? arenaFormatDate(d, locale.locale, ARENA_DATE_OPTIONS.dayName) : undefined}
              className={styles.dayHead()} data-arena-part={manifest.parts.dayHead}>
              <div className={styles.weekday()} data-arena-part={manifest.parts.weekday}>{arenaFormatDate(d, locale.locale, ARENA_DATE_OPTIONS.weekdayShort)}</div>
              <div className={arenaCalendarStyles({ today: isToday }).dayNumber()} data-arena-part={manifest.parts.dayNumber}>
                {arenaFormatDate(d, locale.locale, ARENA_DATE_OPTIONS.dayNumber)}
              </div>
            </DayHead>
          );
        })}
      </div>

      {

}
      <div className={styles.scroll()} data-arena-part={manifest.parts.scroll}>
        <div className={styles.body()} data-arena-part={manifest.parts.body} style={{ height: y(endMin) }}>

          <div className={styles.gutter()} data-arena-part={manifest.parts.gutter}>
            {hours.map((m) => (
              <div key={m} className={styles.hourLabel()} data-arena-part={manifest.parts.hourLabel} style={{ top: y(m) }}>
                {arenaFormatHM(m)}
              </div>
            ))}
          </div>

          {

}
          <div ref={gridRef} role="grid" aria-label={arenaPhrase(locale.calendarGrid, { range })}
            onKeyDown={onGridKeyDown}
            className={styles.grid()} data-arena-part={manifest.parts.grid} style={{ gridTemplateColumns: TRACKS(days.length) }}>
            {hours.map((m) => (
              <div key={m} aria-hidden="true" className={styles.rule()} data-arena-part={manifest.parts.rule} style={{ top: y(m) }} />
            ))}

            {days.map((d, di) => (
              <div key={d} role="row"
                aria-label={arenaFormatDate(d, locale.locale, ARENA_DATE_OPTIONS.dayName)}
                aria-owns={ownedIds(di) || undefined}
                onClick={activateDay(d)}
                className={arenaCalendarStyles({ firstColumn: di === 0, dayInteractive }).column()} data-arena-part={manifest.parts.column}>
                {slots.map((s, si) => {
                  const isCursor = di === curDay && si === curHour;
                  return (
                    <div key={s.start} role="gridcell" aria-label={arenaFormatHM(s.start)}
                      tabIndex={isCursor ? 0 : -1}

                      onFocus={() => { if (di !== curDay || si !== curHour) setCursor({ day: di, hour: si }); }}
                      className={styles.cell()} data-arena-part={manifest.parts.cell}
                      style={{ top: y(s.start), height: y(s.end) - y(s.start) }} />
                  );
                })}
              </div>
            ))}

            {chips.map(({ p, di, domId }) => {
              const top = y(p.startMin);
              const rawH = y(p.endMin) - top;
              const element = elementOf.get(p.ev);
              if (!element) return null;
              const leftShare = ((di + p.col / p.cols) / days.length) * 100;
              const widthShare = (1 / (p.cols * days.length)) * 100;
              return React.cloneElement(element, {
                ref: (node: HTMLElement | null) => {
                  const id = p.ev.id;
                  if (id === undefined) return;
                  if (node) eventRefs.current.set(id, node);
                  else eventRefs.current.delete(id);
                },

                domId,
                tabIndex: -1,
                box: { top, height: `max(calc(var(--sp-1) * 6.5), ${rawH}px)`,
                  left: `${leftShare}%`,
                  right: `${100 - leftShare - widthShare}%` },
                color: arenaCatColor(p.ev.colorId ?? 1),
                timeLabel: `${arenaFormatHM(p.startMin)} – ${arenaFormatHM(p.endMin)}`,
                dateLabel: arenaFormatDate(days[di] ?? '', locale.locale, ARENA_DATE_OPTIONS.dayName),
                showTime: arenaShowsTime(rawH, slotFor(p.cols)),
                actionsBelow: arenaStacksActions(rawH, slotFor(p.cols)),
              });
            })}

            {showNow && (
              <div aria-hidden="true" className={styles.now()} data-arena-part={manifest.parts.now} style={{ top: y(nowMin) }}>
                <span className={styles.nowDot()} data-arena-part={manifest.parts.nowDot} />
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}

// frameworks/angular/components/display/arena-calendar/ArenaCalendar.ts
import {
  ChangeDetectionStrategy, Component, DestroyRef, ElementRef, afterNextRender, afterRenderEffect,
  booleanAttribute, computed, contentChild, contentChildren, inject, input, linkedSignal,
  numberAttribute, output, signal, viewChild,
} from '@angular/core';
import type { ArenaCalendarView } from '../../../Api.generated';
import { arenaContainerWidth, arenaReadBreakpoint } from '../../../ContainerSize';
import { ArenaActions } from '../../../ProjectionMarkers';
import { ARENA_LOCALE } from '../../../ArenaLocale';
import { arenaPhrase } from '../../../Phrase';
import { ArenaCalendarEvent } from '../arena-calendar-event/ArenaCalendarEvent';
import { ArenaCalendarState, type ChipPlacement, type HourSlot } from './ArenaCalendarState';
import {
  arenaAddDays, arenaDefaultDayStart, arenaFormatDate, arenaFormatHM, arenaLayoutDay, arenaNowMinutes, arenaParseHM, arenaPlaceEvents,
  arenaRangeTitle, arenaStartOfWeek, arenaTodayIso, arenaWeekdayOf, ARENA_DATE_OPTIONS,
} from './CalendarInternals';
import { arenaCalendarStyles } from './ArenaCalendar.variants';
import manifest from './ArenaCalendar.classes.generated';

const MINUTE = 60000;

@Component({
  selector: 'arena-calendar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [ArenaCalendarState],
  host: { style: 'display: contents' },
  template: `
    <section #frame [class]="styles().root()" [attr.data-arena-part]="parts.root" [attr.aria-label]="regionName()">
      <div [class]="styles().toolbar()" [attr.data-arena-part]="parts.toolbar">
        <button type="button" [class]="styles().nav()" [attr.data-arena-part]="parts.nav" [attr.aria-label]="locale.calendarPrevious" (click)="step(-1)">
          <i class="ph-bold ph-caret-left" aria-hidden="true"></i>
        </button>
        <button type="button" [class]="styles().today()" [attr.data-arena-part]="parts.today" (click)="goto(today())">{{ locale.calendarToday }}</button>
        <button type="button" [class]="styles().nav()" [attr.data-arena-part]="parts.nav" [attr.aria-label]="locale.calendarNext" (click)="step(1)">
          <i class="ph-bold ph-caret-right" aria-hidden="true"></i>
        </button>
        <div [class]="styles().heading()" [attr.data-arena-part]="parts.heading">{{ title() }}</div>
        @if (actionsSlot()) {
          <div [class]="styles().actions()" [attr.data-arena-part]="parts.actions" data-arena-boundary><ng-content select="[actions]" /></div>
        }
      </div>

      <div [class]="styles().headStrip()" [attr.data-arena-part]="parts.headStrip" [style.gridTemplateColumns]="tracks()">
        @for (day of days(); track day) {
          @if (dayInteractive()) {
            <button type="button" [class]="dayHeadClass()" [attr.data-arena-part]="parts.dayHead" [attr.aria-label]="dayLabel(day)"
                    (click)="onDateClick(day)">
              <div [class]="styles().weekday()" [attr.data-arena-part]="parts.weekday">{{ arenaWeekdayOf(day) }}</div>
              <div [class]="dayNumberClass(day)" [attr.data-arena-part]="parts.dayNumber">{{ dayNumberOf(day) }}</div>
            </button>
          } @else {
            <div [class]="dayHeadClass()" [attr.data-arena-part]="parts.dayHead">
              <div [class]="styles().weekday()" [attr.data-arena-part]="parts.weekday">{{ arenaWeekdayOf(day) }}</div>
              <div [class]="dayNumberClass(day)" [attr.data-arena-part]="parts.dayNumber">{{ dayNumberOf(day) }}</div>
            </div>
          }
        }
      </div>

      <div [class]="styles().scroll()" [attr.data-arena-part]="parts.scroll">
        <div [class]="styles().body()" [attr.data-arena-part]="parts.body" [style.height.px]="bodyHeight()">
          <div [class]="styles().gutter()" [attr.data-arena-part]="parts.gutter">
            @for (hour of hours(); track hour) {
              <div [class]="styles().hourLabel()" [attr.data-arena-part]="parts.hourLabel" [style.top.px]="state.y(hour)">{{ hm(hour) }}</div>
            }
          </div>

          <div role="grid" [class]="styles().grid()" [attr.data-arena-part]="parts.grid" data-arena-boundary [style.gridTemplateColumns]="tracks()"
               [attr.aria-label]="gridName()" (keydown)="onKeydown($event)">
            @for (hour of hours(); track hour) {
              <div aria-hidden="true" [class]="styles().rule()" [attr.data-arena-part]="parts.rule" [style.top.px]="state.y(hour)"></div>
            }

            @for (day of days(); track day; let di = $index) {
              <div role="row" [class]="columnClass(di)" [attr.data-arena-part]="parts.column" [attr.aria-label]="dayLabel(day)"
                   [attr.aria-owns]="state.ownedIds(day)" (click)="onDateClick(day)">
                @for (slot of slots(); track slot.start; let si = $index) {
                  <div role="gridcell" [class]="styles().cell()" [attr.data-arena-part]="parts.cell" [attr.aria-label]="hm(slot.start)"
                       [attr.tabindex]="state.isStop(di, si) ? 0 : -1"
                       [style.top.px]="state.y(slot.start)"
                       [style.height.px]="state.y(slot.end) - state.y(slot.start)"
                       (focus)="moveTo(di, si)"></div>
                }
              </div>
            }

            <ng-content />

            @if (showNow()) {
              <div aria-hidden="true" [class]="styles().now()" [attr.data-arena-part]="parts.now" [style.top.px]="state.y(nowMin())">
                <span [class]="styles().nowDot()" [attr.data-arena-part]="parts.nowDot"></span>
              </div>
            }
          </div>
        </div>
      </div>
    </section>
  `,
})
export class ArenaCalendar {
  protected readonly parts = manifest.parts;

  /** IANA zone name. Defaults to the reader's own resolved zone, which is right whenever the schedule belongs to the person looking at it. Pass it when the calendar has a zone of its own that differs (a Madrid timetable read from Tokyo), and when server-rendering, where the reader's zone is not knowable. */
  readonly timeZone = input<string>();
  /** ISO date the view opens on. Defaults to today in `timeZone`; pass and change it to drive the date yourself. */
  readonly anchorDate = input<string>();
  /** Omit to derive from the CONTAINER width: day below --bp-md, else week. */
  readonly view = input<ArenaCalendarView>();
  /** HH:MM the grid starts at. Defaults to the earliest visible event's hour, floored. */
  readonly dayStart = input<string>();
  /** HH:MM the grid ends at. */
  readonly dayEnd = input<string, string | undefined>('23:00', { transform: (value) => value ?? '23:00' });
  /** 0 = Sunday … 6 = Saturday. */
  readonly weekStartsOn = input(1, { transform: numberAttribute });
  /** Drop Sunday from the week unless an event falls on it. */
  readonly hideEmptyWeekend = input(true, { transform: booleanAttribute });
  /** Whether a day can be activated. A boolean rather than "is `dateClick` bound?", because Arena never derives what it draws from what a consumer listens for, and the same member `ArenaTableRow.interactive` and `ArenaCalendarEvent.interactive` are for the same reason; here the derived render was the day's own cursor, and the layers diverged on screen because of it. With it on, the day header is a <button> (the keyboard's route to the date, and the one element that already names it), and the column background takes a pointer cursor; with it off both are inert and the cursor says so. The default is false because a schedule someone only reads is the ordinary calendar, and a pointer cursor over days that answer nothing is the defect this member exists to end. */
  readonly dayInteractive = input(false, { transform: booleanAttribute });
  /** A day header or column background was activated; carries the ISO date. Never emitted unless `dayInteractive`. */
  readonly dateClick = output<string>();
  /** The anchor moved via prev/Today/next; carries the new ISO date. A date rather than a delta, because Today is not a delta. */
  readonly rangeChange = output<string>();

  protected readonly state = inject(ArenaCalendarState);
  protected readonly locale = inject(ARENA_LOCALE);

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly destroyRef = inject(DestroyRef);
  private readonly frame = viewChild.required<ElementRef<HTMLElement>>('frame');
  private readonly measured = arenaContainerWidth(() => this.frame().nativeElement);
  private readonly medium = arenaReadBreakpoint('md');
  private readonly tick = signal(0);

  protected readonly actionsSlot = contentChild(ArenaActions);
  protected readonly chips = contentChildren(ArenaCalendarEvent);

  protected readonly zone = computed(
    () => this.timeZone() || Intl.DateTimeFormat().resolvedOptions().timeZone,
  );

  protected readonly anchor = linkedSignal(() => this.anchorDate() ?? arenaTodayIso(this.zone()));

  protected readonly activeView = computed<ArenaCalendarView>(() => {
    const chosen = this.view();
    if (chosen) return chosen;
    const width = this.measured();
    return width !== null && width < this.medium ? 'day' : 'week';
  });

  private readonly placed = computed(() => arenaPlaceEvents(
    this.chips().flatMap((chip) => {
      const times = this.state.timesOf(chip);
      return times === null ? [] : [{ ...times, chip }];
    }),
    this.zone(),
  ));

  protected readonly days = computed<readonly string[]>(() => {
    if (this.activeView() === 'day') return [this.anchor()];
    const first = arenaStartOfWeek(this.anchor(), this.weekStartsOn());
    const all = Array.from({ length: 7 }, (_, i) => arenaAddDays(first, i));
    if (!this.hideEmptyWeekend()) return all;
    return all.filter((d) => arenaWeekdayOf(d) !== 0 || this.placed().some((p) => p.dayIso === d));
  });

  private readonly visible = computed(
    () => this.placed().filter((p) => this.days().includes(p.dayIso)),
  );

  private readonly byDay = computed(
    () => this.days().map((d) => arenaLayoutDay(this.visible().filter((p) => p.dayIso === d))),
  );

  private readonly placements = computed<ReadonlyMap<object, ChipPlacement>>(() => {
    const out = new Map<object, ChipPlacement>();
    this.byDay().forEach((laid, dayIndex) => {
      for (const p of laid) {
        out.set(p.ev.chip, {
          dayIndex, dayIso: p.dayIso, startMin: p.startMin, endMin: p.endMin,
          col: p.col, cols: p.cols,
        });
      }
    });
    return out;
  });

  private readonly endMin = computed(() => arenaParseHM(this.dayEnd(), 23 * 60));

  private readonly firstMin = computed(() => {
    const declared = this.dayStart();
    const raw = declared !== undefined ? arenaParseHM(declared, 8 * 60) : arenaDefaultDayStart(this.visible());
    return Math.max(0, Math.min(raw, this.endMin() - 60));
  });

  protected readonly hours = computed(() => {
    const out: number[] = [];
    for (let m = Math.ceil(this.firstMin() / 60) * 60; m <= this.endMin(); m += 60) out.push(m);
    return out;
  });

  protected readonly slots = computed<readonly HourSlot[]>(() => {
    const hours = this.hours();
    return hours
      .map((start, i) => ({ start, end: i + 1 < hours.length ? hours[i + 1] : this.endMin() }))
      .filter((slot) => slot.end > slot.start);
  });

  protected readonly today = computed(() => arenaTodayIso(this.zone()));

  protected readonly nowMin = computed(() => {
    this.tick();
    return arenaNowMinutes(this.zone());
  });

  protected readonly showNow = computed(
    () => this.days().includes(this.today())
      && this.nowMin() >= this.firstMin() && this.nowMin() <= this.endMin(),
  );

  protected readonly title = computed(() => arenaRangeTitle(this.days(), this.locale.locale));
  protected readonly regionName = computed(() => arenaPhrase(this.locale.calendarRegion, { range: this.title() }));
  protected readonly gridName = computed(() => arenaPhrase(this.locale.calendarGrid, { range: this.title() }));

  protected readonly tracks = computed(
    () => `repeat(${this.days().length}, minmax(0, 1fr))`,
  );

  protected readonly bodyHeight = computed(() => this.state.y(this.endMin()));

  protected readonly styles = computed(() => arenaCalendarStyles());

  constructor() {
    this.state.zone = this.zone;
    this.state.days = this.days;
    this.state.slots = this.slots;
    this.state.startMin = this.firstMin;
    this.state.width = this.measured;
    this.state.placements = this.placements;
    this.state.focusCursorCell = () => this.focusCursorCell();

    afterNextRender(() => {
      const id = setInterval(() => this.tick.update((n) => n + 1), MINUTE);
      this.destroyRef.onDestroy(() => clearInterval(id));
    });

    afterRenderEffect(() => {
      this.state.clamped();
      const grid = this.host.nativeElement.querySelector('[role="grid"]');
      if (!grid) return;
      const active = grid.ownerDocument.activeElement;
      if (!active || !grid.contains(active)) return;
      if (active.getAttribute('role') !== 'gridcell') return;
      const stop = grid.querySelector<HTMLElement>('[role="gridcell"][tabindex="0"]');
      if (stop && stop !== active) stop.focus();
    });
  }

  protected hm(min: number): string {
    return arenaFormatHM(min);
  }

  protected arenaWeekdayOf(day: string): string {
    return arenaFormatDate(day, this.locale.locale, ARENA_DATE_OPTIONS.weekdayShort);
  }

  protected dayNumberOf(day: string): string {
    return arenaFormatDate(day, this.locale.locale, ARENA_DATE_OPTIONS.dayNumber);
  }

  protected dayLabel(day: string): string {
    return arenaFormatDate(day, this.locale.locale, ARENA_DATE_OPTIONS.dayName);
  }

  protected dayNumberClass(day: string): string {
    return arenaCalendarStyles({ today: day === this.today() }).dayNumber();
  }

  protected dayHeadClass(): string {
    return arenaCalendarStyles({ dayInteractive: this.dayInteractive() }).dayHead();
  }

  protected columnClass(index: number): string {
    return arenaCalendarStyles({
      firstColumn: index === 0, dayInteractive: this.dayInteractive(),
    }).column();
  }

  protected goto(iso: string): void {
    this.anchor.set(iso);
    this.rangeChange.emit(iso);
  }

  protected step(direction: number): void {
    this.goto(arenaAddDays(this.anchor(), direction * (this.activeView() === 'day' ? 1 : 7)));
  }

  protected onDateClick(day: string): void {
    if (this.dayInteractive()) this.dateClick.emit(day);
  }

  protected moveTo(day: number, hour: number): void {
    if (!this.state.isStop(day, hour)) this.state.cursor.set({ day, hour });
  }

  protected onKeydown(event: KeyboardEvent): void {
    const target = event.target as Element | null;
    if (target?.getAttribute?.('role') !== 'gridcell') {
      if (event.key === 'Escape') {
        event.preventDefault();
        this.focusCursorCell();
      }
      return;
    }

    const at = this.state.clamped();
    let { day, hour } = at;
    const lastDay = Math.max(this.days().length - 1, 0);
    const lastHour = Math.max(this.slots().length - 1, 0);

    if (event.key === 'ArrowLeft') day = Math.max(0, day - 1);
    else if (event.key === 'ArrowRight') day = Math.min(lastDay, day + 1);
    else if (event.key === 'ArrowUp') hour = Math.max(0, hour - 1);
    else if (event.key === 'ArrowDown') hour = Math.min(lastHour, hour + 1);
    else if (event.key === 'Home') hour = 0;
    else if (event.key === 'End') hour = lastHour;
    else if (event.key === 'Enter') {
      event.preventDefault();
      const slot = this.slots()[at.hour];
      if (slot) this.state.focusOverlapping(at.day, slot.start, slot.end);
      return;
    } else return;

    event.preventDefault();
    this.moveTo(day, hour);
  }

  private focusCursorCell(): void {
    const cell = this.host.nativeElement
      .querySelector<HTMLElement>('[role="gridcell"][tabindex="0"]');
    if (cell) cell.focus();
  }
}
