// frameworks/react/components/navigation/arena-app-bar/ArenaAppBar.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaAppBar.classes.generated.ts';

export interface ArenaAppBarProps {

  /** The identity, at the start edge: an ArenaAppLogo, a wordmark, a mark. Wrap it in your own link if it should lead home; the bar draws no anchor of its own, which is what keeps a router's link out of a component that would have to swallow it. */
  brand?: React.ReactNode;

  /** The way through the site, between the brand and the actions. It is a slot and not a list of destinations because the links are the consumer's: they are their router's, and the navigation landmark around them is theirs to name, since a page with a side nav as well needs the two told apart. */
  nav?: React.ReactNode;

  /** What follows the reader everywhere, at the end edge: search, theme, basket, account. Arena draws the row; the consumer draws what sits in it. */
  actions?: React.ReactNode;

  /** Whether the bar stays at the top edge as the page scrolls. True by default, because a bar that carries the way through a site and scrolls away with the content is a bar the reader has to go back for. It takes the navigation layer of the stacking order, so a dialog and a sheet still cover it. */
  sticky?: boolean;
}

const arenaAppBarStyles = arenaStyles(manifest);
const PAGE = 'var(--container-max)';

export function ArenaAppBar({ brand, nav, actions, sticky = true }: ArenaAppBarProps) {
  const styles = arenaAppBarStyles({ sticky });

  return (
    <header className={styles.root()} data-arena-part={manifest.parts.root}>
      <div className={styles.band()} data-arena-part={manifest.parts.band} style={{ maxWidth: PAGE }}>
        {brand && <div className={styles.brand()} data-arena-part={manifest.parts.brand} data-arena-boundary="">{brand}</div>}
        {nav && <div className={styles.nav()} data-arena-part={manifest.parts.nav} data-arena-boundary="">{nav}</div>}
        {actions && <div className={styles.actions()} data-arena-part={manifest.parts.actions} data-arena-boundary="">{actions}</div>}
      </div>
    </header>
  );
}

// frameworks/angular/components/navigation/arena-app-bar/ArenaAppBar.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, contentChild, input } from '@angular/core';
import { ArenaActions, ArenaBrand, ArenaNav } from '../../../ProjectionMarkers';
import { arenaAppBarStyles } from './ArenaAppBar.variants';
import manifest from './ArenaAppBar.classes.generated';

const PAGE = 'var(--container-max)';

@Component({
  selector: 'arena-app-bar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <header [class]="styles().root()" [attr.data-arena-part]="parts.root">
      <div [class]="styles().band()" [attr.data-arena-part]="parts.band" [style.maxWidth]="page">
        @if (brand()) { <div [class]="styles().brand()" [attr.data-arena-part]="parts.brand" data-arena-boundary><ng-content select="[brand]" /></div> }
        @if (nav()) { <div [class]="styles().nav()" [attr.data-arena-part]="parts.nav" data-arena-boundary><ng-content select="[nav]" /></div> }
        @if (actions()) { <div [class]="styles().actions()" [attr.data-arena-part]="parts.actions" data-arena-boundary><ng-content select="[actions]" /></div> }
      </div>
    </header>
  `,
})
export class ArenaAppBar {
  protected readonly parts = manifest.parts;

  /** Whether the bar stays at the top edge as the page scrolls. True by default, because a bar that carries the way through a site and scrolls away with the content is a bar the reader has to go back for. It takes the navigation layer of the stacking order, so a dialog and a sheet still cover it. */
  readonly sticky = input(true, { transform: booleanAttribute });

  protected readonly brand = contentChild(ArenaBrand);
  protected readonly nav = contentChild(ArenaNav);
  protected readonly actions = contentChild(ArenaActions);

  protected readonly page = PAGE;
  protected readonly styles = computed(() => arenaAppBarStyles({ sticky: this.sticky() }));
}
