// frameworks/react/components/layout/arena-board-column/ArenaBoardColumn.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import { arenaCatColor } from '../../../DataVisuals.ts';
import manifest from '../arena-board/ArenaBoard.classes.generated.ts';

import type { ArenaCatSlot, ArenaHeadingLevel } from '../../../Api.generated';

export interface ArenaBoardColumnProps {

  /** What this column is: a status, a stage, a person, a day. It is the head's text and the column's accessible name at once. Required and guarded at runtime rather than defaulted, because a column of a board is only ever read by what it groups, and an unnamed one is a pile. */
  title: string;

  /** Which rung of the document outline the head's text takes. Only the element changes: its class is the same at every value, so the render is identical and no appearance follows from it. It defaults to `h3`, the card rung of the title ladder, because a board sits inside the region a section names and a column sits inside the board. The column's accessible name is separate and is unaffected, since it is the group's own and is carried whatever the head is drawn as. `none` is refused at runtime, the rule every component whose `title` is required follows: a title required because it names the thing it draws cannot also be told that the name is not one. */
  headingLevel?: ArenaHeadingLevel;

  /** How many things are in the column, drawn beside the title in the numeric register. It is passed rather than counted, because Arena never derives what it draws from what a consumer projected: the column holds the consumer's own elements, one of which may be a placeholder and none of which Arena can read. */
  count?: number;

  /** One line under the head: the total the column adds up to, an estimate, a limit. A string rather than a number because the unit travels with it, and a column reading "19 pts" is one value and not two. */
  summary?: string;

  /** An identity colour for the column, from the same categorical ramp ArenaTag and the charts read, so a status keeps its colour between a board, a table and a chart. It inks the head's mark and reaches the column as a custom property, `--arena-board-column-cat`, so an appearance that fills the whole head with it is a style plugin's to write and needs no member here. */
  colorId?: ArenaCatSlot;

  /** One control in the head: a menu, a filter, an add. It sits after the count, and the column draws nothing for it beyond the space it takes. */
  action?: React.ReactNode;

  /** The cards, stacked in order. Arena draws none of them: a board's card carries the product's own fields, so what is left once they are removed is the stack, which is what this draws. */
  children?: React.ReactNode;

  /** The action that adds to this column, under the stack, where a board puts it because a new card lands at the bottom. Optional, and a column with none simply ends at its last card. */
  footer?: React.ReactNode;
}


const boardStyles = arenaStyles(manifest);

export function ArenaBoardColumn({ title, headingLevel = 'h3', count, summary, colorId, action, children, footer }: ArenaBoardColumnProps) {
  if (!title?.trim()) throw new Error('ArenaBoardColumn: `title` is required (it is the head and the column\'s accessible name at once)');
  if (headingLevel === 'none') {
    throw new Error('ArenaBoardColumn: `headingLevel` cannot be none, because `title` is required and names the column it heads');
  }
  const styles = boardStyles({ identity: colorId !== undefined });
  const Heading = headingLevel;
  return (
    <section role="group" aria-label={title} className={styles.column()} data-arena-part={manifest.parts.column}
      style={colorId ? { '--arena-board-column-cat': arenaCatColor(colorId) } as React.CSSProperties : undefined}>
      <div className={styles.head()} data-arena-part={manifest.parts.head}>
        {colorId !== undefined && <span aria-hidden="true" className={styles.dot()} data-arena-part={manifest.parts.dot} />}
        <Heading className={styles.title()} data-arena-part={manifest.parts.title}>{title}</Heading>
        {count !== undefined && <span className={styles.count()} data-arena-part={manifest.parts.count}>{count}</span>}
        <span className={styles.action()} data-arena-part={manifest.parts.action} data-arena-boundary="">{action}</span>
      </div>
      {summary && <span className={styles.summary()} data-arena-part={manifest.parts.summary}>{summary}</span>}
      <div className={styles.stack()} data-arena-part={manifest.parts.stack} data-arena-boundary="">{children}</div>
      <div className={styles.foot()} data-arena-part={manifest.parts.foot} data-arena-boundary="">{footer}</div>
    </section>
  );
}

// frameworks/angular/components/layout/arena-board-column/ArenaBoardColumn.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import type { ArenaCatSlot, ArenaHeadingLevel } from '../../../Api.generated';
import { arenaCatColor } from '../../../DataVisuals';
import { arenaBoardStyles } from '../arena-board/ArenaBoard.variants';
import manifest from '../arena-board/ArenaBoard.classes.generated';

@Component({
  selector: 'arena-board-column',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents', '[attr.title]': 'null' },
  template: `
    <section [class]="styles().column()" [attr.data-arena-part]="parts.column"
             role="group" [attr.aria-label]="named()"
             [style.--arena-board-column-cat]="catColour()">
      <div [class]="styles().head()" [attr.data-arena-part]="parts.head">
        @if (colorId() !== undefined) {
          <span aria-hidden="true" [class]="styles().dot()" [attr.data-arena-part]="parts.dot"></span>
        }
        @switch (level()) {
          @case ('h1') { <h1 [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ named() }}</h1> }
          @case ('h2') { <h2 [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ named() }}</h2> }
          @case ('h4') { <h4 [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ named() }}</h4> }
          @default { <h3 [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ named() }}</h3> }
        }
        @if (count() !== undefined) {
          <span [class]="styles().count()" [attr.data-arena-part]="parts.count">{{ count() }}</span>
        }
        <span [class]="styles().action()" [attr.data-arena-part]="parts.action">
          <ng-content select="[action]" />
        </span>
      </div>
      @if (summary(); as line) {
        <span [class]="styles().summary()" [attr.data-arena-part]="parts.summary">{{ line }}</span>
      }
      <div [class]="styles().stack()" [attr.data-arena-part]="parts.stack">
        <ng-content />
      </div>
      <div [class]="styles().foot()" [attr.data-arena-part]="parts.foot">
        <ng-content select="[footer]" />
      </div>
    </section>
  `,
})
export class ArenaBoardColumn {
  protected readonly parts = manifest.parts;

  /** What this column is: a status, a stage, a person, a day. It is the head's text and the column's accessible name at once. Required and guarded at runtime rather than defaulted, because a column of a board is only ever read by what it groups, and an unnamed one is a pile. */
  readonly title = input.required<string>();
  /** Which rung of the document outline the head's text takes. Only the element changes: its class is the same at every value, so the render is identical and no appearance follows from it. It defaults to `h3`, the card rung of the title ladder, because a board sits inside the region a section names and a column sits inside the board. The column's accessible name is separate and is unaffected, since it is the group's own and is carried whatever the head is drawn as. `none` is refused at runtime, the rule every component whose `title` is required follows: a title required because it names the thing it draws cannot also be told that the name is not one. */
  readonly headingLevel = input<ArenaHeadingLevel, ArenaHeadingLevel | undefined>(
    'h3', { transform: (value) => value ?? 'h3' },
  );
  /** How many things are in the column, drawn beside the title in the numeric register. It is passed rather than counted, because Arena never derives what it draws from what a consumer projected: the column holds the consumer's own elements, one of which may be a placeholder and none of which Arena can read. */
  readonly count = input<number>();
  /** One line under the head: the total the column adds up to, an estimate, a limit. A string rather than a number because the unit travels with it, and a column reading "19 pts" is one value and not two. */
  readonly summary = input<string>();
  /** An identity colour for the column, from the same categorical ramp ArenaTag and the charts read, so a status keeps its colour between a board, a table and a chart. It inks the head's mark and reaches the column as a custom property, `--arena-board-column-cat`, so an appearance that fills the whole head with it is a style plugin's to write and needs no member here. */
  readonly colorId = input<ArenaCatSlot>();

  protected readonly level = computed(() => {
    const level = this.headingLevel();
    if (level === 'none') {
      throw new Error('ArenaBoardColumn: `headingLevel` cannot be none, because `title` is required and names the column it heads');
    }
    return level;
  });

  protected readonly named = computed(() => {
    const name = this.title();
    if (name.trim() === '') {
      throw new Error('ArenaBoardColumn: `title` is required (it is the head and the column\'s accessible name at once)');
    }
    return name;
  });

  protected readonly catColour = computed(() => {
    const slot = this.colorId();
    return slot === undefined ? null : arenaCatColor(slot);
  });

  protected readonly styles = computed(() => arenaBoardStyles({ identity: this.colorId() !== undefined }));
}
