// frameworks/angular/components/navigation/arena-menu/ArenaMenu.ts
import {
  ChangeDetectionStrategy, Component, DOCUMENT, DestroyRef, ElementRef, Injector, TemplateRef,
  ViewContainerRef, afterNextRender, afterRenderEffect, computed, inject, input, output, signal,
  untracked, viewChild,
} from '@angular/core';
import {
  type ConnectedPosition, type OverlayRef, createFlexibleConnectedPositionStrategy,
  createOverlayRef, createRepositionScrollStrategy,
} from '@angular/cdk/overlay';
import { TemplatePortal } from '@angular/cdk/portal';
import type { ArenaMenuAlign, ArenaMenuItem } from '../../../Api.generated';
import { sp1 } from '../../../Tokens.generated';
import { arenaWarnOnce } from '../../../WarnOnce';
import { arenaMenuStyles } from './ArenaMenu.variants';
import manifest from './ArenaMenu.classes.generated';

const TRIGGER_SELECTOR =
  'button:not([tabindex="-1"]), a[href]:not([tabindex="-1"]), [role="button"]:not([tabindex="-1"]), [tabindex]:not([tabindex="-1"])';

export const ARENA_MENU_POSITIONS: Record<ArenaMenuAlign, ConnectedPosition[]> = {
  start: [
    { originX: 'start', originY: 'bottom', overlayX: 'start', overlayY: 'top', offsetY: sp1 * 1.5 },
    { originX: 'start', originY: 'top', overlayX: 'start', overlayY: 'bottom', offsetY: -sp1 * 1.5 },
  ],
  end: [
    { originX: 'end', originY: 'bottom', overlayX: 'end', overlayY: 'top', offsetY: sp1 * 1.5 },
    { originX: 'end', originY: 'top', overlayX: 'end', overlayY: 'bottom', offsetY: -sp1 * 1.5 },
  ],
};

export function isArenaActivatable(item: ArenaMenuItem): boolean {
  return !item.divider && item.header === undefined;
}

export function arenaRowState(item: ArenaMenuItem): 'disabled' | 'destructive' | 'default' {
  if (item.disabled) return 'disabled';
  return item.destructive ? 'destructive' : 'default';
}

@Component({
  selector: 'arena-menu',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.data-arena-part]': 'parts.root',
  },
  template: `
    <ng-content select="[trigger]" />
    <ng-template #panel>
      <div role="menu" [class]="styles().panel()" [attr.data-arena-part]="parts.panel">
        @for (item of items(); track $index) {
          @if (item.divider) {
            <div [class]="styles().divider()" [attr.data-arena-part]="parts.divider"></div>
          } @else if (item.header; as heading) {
            <div [class]="styles().header()" [attr.data-arena-part]="parts.header">{{ heading }}</div>
          } @else {
            <button type="button" role="menuitem" [class]="rowClass(item)" [attr.data-arena-part]="parts.item" [disabled]="item.disabled"
                    (click)="run(item)">
              @if (item.icon; as glyph) {
                <i [class]="styles().icon() + ' ' + glyph" [attr.data-arena-part]="parts.icon" aria-hidden="true"></i>
              }
              <span [class]="styles().label()" [attr.data-arena-part]="parts.label">{{ item.label }}</span>
              @if (item.shortcut; as keys) {
                <span [class]="styles().shortcut()" [attr.data-arena-part]="parts.shortcut">{{ keys }}</span>
              }
            </button>
          }
        }
      </div>
    </ng-template>
  `,
})
export class ArenaMenu {
  protected readonly parts = manifest.parts;

  /** The entries, in order: activatable rows, dividers and group headers. */
  readonly items = input.required<readonly ArenaMenuItem[]>();
  /** Which edge of the trigger the panel lines up with. */
  readonly align = input<ArenaMenuAlign, ArenaMenuAlign | undefined>(
    'start',
    { transform: (value) => value ?? 'start' },
  );
  /** An entry was activated; carries the whole item. A disabled entry reports nothing, and a divider or a header cannot be activated at all. */
  readonly select = output<ArenaMenuItem>();

  protected readonly styles = computed(() => arenaMenuStyles({ anchored: true }));

  private readonly open = signal(false);
  private readonly panel = viewChild.required<TemplateRef<unknown>>('panel');
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly injector = inject(Injector);
  private readonly viewContainer = inject(ViewContainerRef);
  private readonly doc = inject(DOCUMENT);

  private ref: OverlayRef | null = null;
  private detachTrigger: (() => void) | null = null;
  private detachDocument: (() => void) | null = null;

  constructor() {
    afterNextRender(() => this.bindTrigger(), { injector: this.injector });
    afterRenderEffect(() => {
      const isOpen = this.open();
      untracked(() => this.describeTrigger(isOpen));
    });
    inject(DestroyRef).onDestroy(() => {
      this.detachTrigger?.();
      this.teardown();
    });
  }

  protected rowClass(item: ArenaMenuItem): string {
    const styles = this.styles();
    const state = arenaRowState(item);
    const modifier = state === 'disabled' ? styles.itemDisabled()
      : state === 'destructive' ? styles.itemDestructive() : styles.itemDefault();
    return `${styles.item()} ${modifier}`;
  }

  protected run(item: ArenaMenuItem): void {
    if (item.disabled) return;
    this.close(true);
    this.select.emit(item);
  }

  private trigger(): HTMLElement | null {
    const found = this.host.nativeElement.querySelector<HTMLElement>(TRIGGER_SELECTOR);
    if (found) return found;
    const first = this.host.nativeElement.firstElementChild;
    return first instanceof HTMLElement ? first : null;
  }

  private reportTrigger(): void {
    if (this.host.nativeElement.querySelector(TRIGGER_SELECTOR)) return;
    const first = this.host.nativeElement.firstElementChild;
    arenaWarnOnce(
      first === null
        ? 'arena-menu is given no trigger: mark the element that opens it with the `trigger` '
          + 'attribute, or nothing opens the menu at all.'
        : `arena-menu's trigger is a <${first.tagName.toLowerCase()}>, which takes no focus and `
          + 'answers no key. The menu opens on a pointer and on nothing else, and a reader on a '
          + 'keyboard cannot reach it. Project a control: an ArenaIconButton or an ArenaButton, '
          + 'or your own element carrying a button role and a tabindex.',
    );
  }

  private bindTrigger(): void {
    this.reportTrigger();
    const trigger = this.trigger();
    if (!trigger) return;
    const onClick = (): void => this.toggle();
    const onKeydown = (event: Event): void => {
      if (!(event instanceof KeyboardEvent)) return;
      if (event.key !== 'Enter' && event.key !== ' ') return;
      event.preventDefault();
      this.toggle();
    };
    trigger.addEventListener('click', onClick);
    trigger.addEventListener('keydown', onKeydown);
    this.detachTrigger = () => {
      trigger.removeEventListener('click', onClick);
      trigger.removeEventListener('keydown', onKeydown);
    };
  }

  private describeTrigger(isOpen: boolean): void {
    const trigger = this.trigger();
    if (!trigger) return;
    trigger.setAttribute('aria-haspopup', 'menu');
    trigger.setAttribute('aria-expanded', String(isOpen));
  }

  private toggle(): void {
    if (this.open()) this.close(true);
    else this.attach();
  }

  private attach(): void {
    if (this.ref) return;
    const ref = createOverlayRef(this.injector, {
      positionStrategy: createFlexibleConnectedPositionStrategy(this.injector, this.host)
        .withPositions(ARENA_MENU_POSITIONS[this.align()])
        .withPush(false),
      scrollStrategy: createRepositionScrollStrategy(this.injector),
    });
    ref.attach(new TemplatePortal(this.panel(), this.viewContainer));
    this.ref = ref;
    this.open.set(true);
    this.listenForDismissal();
    afterNextRender(() => this.focusFirstItem(), { injector: this.injector });
  }

  private close(restoreFocus: boolean): void {
    if (!this.ref) return;
    this.teardown();
    this.open.set(false);
    if (restoreFocus) this.trigger()?.focus();
  }

  private teardown(): void {
    this.detachDocument?.();
    this.detachDocument = null;
    this.ref?.dispose();
    this.ref = null;
  }

  private focusFirstItem(): void {
    const first = this.ref?.overlayElement.querySelector<HTMLElement>('[role="menuitem"]:not([disabled])');
    first?.focus();
  }

  private listenForDismissal(): void {
    const onKeydown = (event: Event): void => {
      if (event instanceof KeyboardEvent && event.key === 'Escape') this.close(true);
    };
    const onPointerDown = (event: Event): void => {
      const target = event.target;
      if (!(target instanceof Node)) return;
      if (this.host.nativeElement.contains(target)) return;
      if (this.ref?.overlayElement.contains(target)) return;
      this.close(false);
    };
    this.doc.addEventListener('keydown', onKeydown);
    this.doc.addEventListener('mousedown', onPointerDown);
    this.detachDocument = () => {
      this.doc.removeEventListener('keydown', onKeydown);
      this.doc.removeEventListener('mousedown', onPointerDown);
    };
  }
}

// frameworks/react/components/navigation/arena-menu/ArenaMenu.tsx
import React, { useState, useRef, useEffect } from 'react';
import { arenaWarnOnce } from '../../../WarnOnce.ts';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaMenu.classes.generated.ts';

import type { ArenaMenuItem, ArenaMenuAlign } from '../../../Api.generated';

export type { ArenaMenuItem };

export interface ArenaMenuProps {

  /** The element that opens the menu. The consumer draws it -- an ArenaIconButton with ph-dots-three-vertical, a secondary ArenaButton -- so it is a slot, and it carries its own accessible name. */
  trigger: React.ReactNode;

  /** The entries, in order: activatable rows, dividers and group headers. */
  items: readonly ArenaMenuItem[];

  /** Which edge of the trigger the panel lines up with. */
  align?: ArenaMenuAlign;

  /** An entry was activated; carries the whole item. A disabled entry reports nothing, and a divider or a header cannot be activated at all. */
  onSelect?: (item: ArenaMenuItem) => void;
}


const TRIGGER_SELECTOR =
  'button:not([tabindex="-1"]), a[href]:not([tabindex="-1"]), [role="button"]:not([tabindex="-1"]), [tabindex]:not([tabindex="-1"])';

const arenaMenuStyles = arenaStyles(manifest);

export function ArenaMenu({ trigger, items, align = 'start', onSelect }: ArenaMenuProps) {

  if (items == null) throw new Error('ArenaMenu: `items` is required');
  if (!React.isValidElement(trigger) || trigger.type === React.Fragment) {
    throw new Error(
      'ArenaMenu: `trigger` must be a single element that forwards props to its focusable control. '
      + 'A fragment or a bare string takes aria-haspopup and aria-expanded nowhere.',
    );
  }
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement | null>(null);
  const panelRef = useRef<HTMLDivElement | null>(null);

  const triggerEl = (): HTMLElement | null =>
    (ref.current?.firstElementChild instanceof HTMLElement ? ref.current.firstElementChild : null);
  const close = (restoreFocus: boolean) => {
    setOpen(false);
    const el = triggerEl();
    if (restoreFocus && el) el.focus();
  };

  useEffect(() => {
    if (!open) return;
    const onDoc = (e: MouseEvent) => {
      if (ref.current && e.target instanceof Node && !ref.current.contains(e.target)) setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') close(true); };
    document.addEventListener('mousedown', onDoc);
    document.addEventListener('keydown', onKey);
    return () => { document.removeEventListener('mousedown', onDoc); document.removeEventListener('keydown', onKey); };
  }, [open]);

  useEffect(() => {
    if (!open) return;
    const first = panelRef.current
      ?.querySelector<HTMLElement>('[role="menuitem"]:not([disabled])');
    if (first) first.focus();
  }, [open]);

  const run = (it: ArenaMenuItem) => { if (it.disabled) return; close(true); onSelect && onSelect(it); };

  useEffect(() => {
    const el = triggerEl();
    if (!el) return;
    if (!el.matches(TRIGGER_SELECTOR) && !el.querySelector(TRIGGER_SELECTOR)) {
      arenaWarnOnce(
        `ArenaMenu's trigger renders a <${el.tagName.toLowerCase()}>, which takes no focus and `
        + 'answers no key. The menu opens on a pointer and on nothing else, and a reader on a '
        + 'keyboard cannot reach it. Pass a control: an ArenaIconButton or an ArenaButton, or your '
        + 'own element carrying a button role and a tabindex.',
      );
    }
    el.setAttribute('aria-haspopup', 'menu');
    el.setAttribute('aria-expanded', String(open));
  }, [open]);

  const decoratedTrigger = React.cloneElement(trigger, {
    'aria-haspopup': 'menu',
    'aria-expanded': open,
    onClick: (e: React.MouseEvent) => {
      const own = (trigger.props as { onClick?: (event: React.MouseEvent) => void }).onClick;
      if (own) own(e);
      setOpen((v) => !v);
    },
  });

  const styles = arenaMenuStyles();

  return (
    <div ref={ref} className={styles.root()} data-arena-part={manifest.parts.root}>
      {decoratedTrigger}
      {open && (
        <div role="menu" ref={panelRef}
          className={align === 'end' ? `${styles.panel()} ${styles.panelEnd()}` : styles.panel()}
          data-arena-part={manifest.parts.panel}>
          {items.map((it, i) => {
            if (it.divider) return <div key={i} className={styles.divider()} data-arena-part={manifest.parts.divider} />;
            if (it.header) return <div key={i} className={styles.header()} data-arena-part={manifest.parts.header}>{it.header}</div>;
            return (
              <MenuRow key={i} item={it} onRun={() => run(it)} />
            );
          })}
        </div>
      )}
    </div>
  );
}

function MenuRow({ item, onRun }: { item: ArenaMenuItem; onRun: () => void }) {
  const styles = arenaMenuStyles();
  const state = item.disabled
    ? styles.itemDisabled()
    : item.destructive ? styles.itemDestructive() : styles.itemDefault();
  return (
    <button role="menuitem" onClick={onRun} disabled={item.disabled}
      className={`${styles.item()} ${state}`} data-arena-part={manifest.parts.item}>
      {item.icon && <i className={`${item.icon} ${styles.icon()}`} data-arena-part={manifest.parts.icon} aria-hidden="true" />}
      <span className={styles.label()} data-arena-part={manifest.parts.label}>{item.label}</span>
      {item.shortcut && <span className={styles.shortcut()} data-arena-part={manifest.parts.shortcut}>{item.shortcut}</span>}
    </button>
  );
}
