// frameworks/react/components/navigation/arena-side-nav-section/ArenaSideNavSection.tsx
import React, { useId } from 'react';
import type { ArenaSideNavInjected } from '../arena-side-nav/SideNavInject.tsx';
import { arenaIndentFor, arenaInjectInto } from '../arena-side-nav/SideNavInject.tsx';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from '../arena-side-nav/ArenaSideNav.classes.generated.ts';

export interface ArenaSideNavSectionProps {

  /** Names the group, both on screen and to assistive technology. Required, and guarded at runtime: a blank label leaves the group with no accessible name, which is the defect the guard exists to prevent arriving through a value that is present, so the guard trims before it decides. */
  label: string;

  /** The items in the group -- SideNavItems, further SideNavSections, SideNavCollapsibles. Each sits one nesting level deeper than the section itself. Required, and guarded at runtime: a section with no children is not a legal shape, and the guard counts the way the render path counts, so a child that is a false conditional counts as absent rather than as one. The ArenaAppLogo.mark shape -- a slot that is both declared required and enforced -- and not the ArenaTooltip.content one, which is declared required and deliberately left unguarded. */
  children: React.ReactNode;
}


const arenaSideNavStyles = arenaStyles(manifest);

export function ArenaSideNavSection({
  label, children,
  depth = 0, activeId, indentStep = 3, onActivate, collapsed = false,
}: ArenaSideNavSectionProps & Partial<ArenaSideNavInjected>) {

  if (!label?.trim()) throw new Error('ArenaSideNavSection: `label` is required');

  if (React.Children.toArray(children).length === 0) {
    throw new Error('ArenaSideNavSection: a section with no children is not a legal shape');
  }
  const labelId = useId();
  const styles = arenaSideNavStyles({ collapsed });
  return (
    <div role="group" aria-labelledby={labelId} className={styles.section()} data-arena-part={manifest.parts.section} data-arena-boundary="">
      {collapsed && <div aria-hidden="true" className={styles.separator()} data-arena-part={manifest.parts.separator} />}
      <div id={labelId} className={styles.sectionLabel()} data-arena-part={manifest.parts.sectionLabel}
        style={collapsed ? undefined : { paddingInlineStart: arenaIndentFor(indentStep, depth) }}>{label}</div>
      {arenaInjectInto(children, { depth: depth + 1, activeId, indentStep, onActivate, collapsed })}
    </div>
  );
}

// frameworks/angular/components/navigation/arena-side-nav-section/ArenaSideNavSection.ts
import {
  ChangeDetectionStrategy, Component, computed, DestroyRef, ElementRef, inject, input,
} from '@angular/core';
import { ArenaSideNavState, arenaIndentFor } from '../arena-side-nav/ArenaSideNavState';
import { arenaSideNavStyles } from '../arena-side-nav/ArenaSideNav.variants';
import manifest from '../arena-side-nav/ArenaSideNav.classes.generated';
import { ArenaIdGenerator } from '../../../ArenaIds';

@Component({
  selector: 'arena-side-nav-section',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [ArenaSideNavState],
  host: {
    'data-arena-boundary': '',
    '[class]': 'styles().section()',
    '[attr.data-arena-part]': 'parts.section',
    role: 'group',
    '[attr.aria-labelledby]': 'labelId',
  },
  template: `
    @if (rail()) {
      <div aria-hidden="true" [class]="styles().separator()" [attr.data-arena-part]="parts.separator"></div>
    }
    <div [id]="labelId" [class]="styles().sectionLabel()" [attr.data-arena-part]="parts.sectionLabel" [style.paddingInlineStart]="indent()">{{ heading() }}</div>
    <ng-content />
  `,
})
export class ArenaSideNavSection {
  protected readonly parts = manifest.parts;

  /** Names the group, both on screen and to assistive technology. Required, and guarded at runtime: a blank label leaves the group with no accessible name, which is the defect the guard exists to prevent arriving through a value that is present, so the guard trims before it decides. */
  readonly label = input.required<string>();

  private readonly parent = inject(ArenaSideNavState, { skipSelf: true });
  private readonly own = inject(ArenaSideNavState);

  private readonly host = inject(ElementRef<HTMLElement>);

  protected readonly labelId = inject(ArenaIdGenerator).next('arena-side-nav-section');

  protected readonly heading = computed(() => {
    const text = this.label();
    if (text.trim() === '') {
      throw new Error('ArenaSideNavSection: `label` is required, and names the group its heading introduces');
    }
    return text;
  });

  protected readonly indent = computed(() => (this.parent.collapsed() ? null : arenaIndentFor(this.parent.indentStep(), this.parent.depth())));
  protected readonly rail = computed(() => this.parent.collapsed());
  protected readonly styles = computed(() => arenaSideNavStyles({ collapsed: this.parent.collapsed() }));

  constructor() {
    this.own.depth = computed(() => this.parent.depth() + 1);
    this.own.activeId = this.parent.activeId;
    this.own.indentStep = this.parent.indentStep;
    this.own.collapsed = this.parent.collapsed;
    this.own.activate = (id: string) => this.parent.activate(id);
    this.parent.adopt(this.own);
    inject(DestroyRef).onDestroy(() => this.parent.orphan(this.own));
  }

  protected ngAfterContentInit(): void {
    if (this.contentAfterHeading().length === 0) {
      throw new Error('ArenaSideNavSection: a section with no children is not a legal shape — its heading would name nothing');
    }
  }

  private contentAfterHeading(): Element[] {
    const element = this.host.nativeElement as HTMLElement;
    return [...element.children].slice(1);
  }
}
