// frameworks/react/components/display/arena-calendar-event/ArenaCalendarEvent.tsx
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from '../arena-calendar/ArenaCalendar.classes.generated.ts';
import React from 'react';
import { ArenaIconButton } from '../../forms/arena-icon-button/ArenaIconButton.tsx';
import { arenaCatColor, arenaCatTint } from '../../../DataVisuals.ts';
import { useArenaLocale } from '../../../ArenaLocale.ts';

import type { ArenaCatSlot } from '../../../Api.generated';

export interface ArenaCalendarEventProps {

  /** Stable identity, so a host can switch on it rather than on the title. */
  id: string;

  /** What the chip reads. */
  title: string;

  /** ISO datetime the event begins. */
  start: string;

  /** ISO datetime the event ends. */
  end: string;

  /** Identity colour. Give the same entity the same slot everywhere and it keeps its colour across views. */
  colorId?: ArenaCatSlot;

  /** Whether the chip can be activated. A boolean rather than "is `click` bound?", because Arena never derives what it draws from what a consumer listens for, and the same member `ArenaTableRow.interactive` is for the same reason. An interactive chip is a <button> a keyboard user reaches with Enter from the hour cell it overlaps; a non-interactive one draws the same chip with no role and no activation, so a read-only schedule announces events rather than a screenful of buttons that do nothing. */
  interactive?: boolean;

  /** Whether the chip is drawn but cannot be activated: an event a consumer's rules lock, such as one already past or owned by someone else. It reflects through `aria-disabled` rather than the native `disabled` attribute, so the chip keeps its place in the grid's roving Tab sequence and is announced as unavailable instead of disappearing from it. With `interactive` false there is nothing to activate and the chip is inert already. */
  disabled?: boolean;

  /** Whether the chip shows its action button. A boolean rather than "is the actions slot filled?": Arena never derives what it draws from what a consumer listens for, because projected content is not inspectable in at least one platform, so gating the drawing on it is a divergence waiting to happen. */
  actionsEnabled?: boolean;

  /** The action panel's content, revealed by the chip's action button. Rendered only while the panel is open, so a consumer's own controls never sit permanently in the grid's Tab sequence. */
  actions?: React.ReactNode;

  /** The chip was activated. No payload: the consumer wrote this element, so they already hold the event this is about. Never emitted while `disabled`. */
  onClick?: () => void;

  /** Lines drawn under the time label, one per entry, each truncated to a single line: the people involved, a room, a capacity. Arena decides how many fit, shedding the last first and then the time label, and every entry reaches what the chip announces whether it is drawn or shed. */
  details?: readonly string[];
}


export interface ArenaCalendarEventInjected {
  box: React.CSSProperties;
  domId: string;
  color: string;
  timeLabel: string;
  dateLabel: string;
  showTime: boolean;
  shownDetails: number;
  actionsBelow: boolean;
  tabIndex: number;
  defaultPanelOpen: boolean;
}

const chipStyles = arenaStyles(manifest);

export const ArenaCalendarEvent = React.forwardRef<
HTMLElement, ArenaCalendarEventProps & Partial<ArenaCalendarEventInjected>
>(function ArenaCalendarEvent({
  id, title, start, end, colorId, onClick, interactive = false, disabled = false,
  actionsEnabled = false, actions, details = [],
  box, domId, color, timeLabel, dateLabel, showTime, shownDetails = 0, actionsBelow, tabIndex, defaultPanelOpen,
}, ref) {

  const locale = useArenaLocale();
  const ink = color ?? arenaCatColor(colorId ?? 1);

  if (!id) throw new Error('ArenaCalendarEvent: `id` is required');
  if (!title) throw new Error('ArenaCalendarEvent: `title` is required');
  if (!start) throw new Error('ArenaCalendarEvent: `start` is required');
  if (!end) throw new Error('ArenaCalendarEvent: `end` is required');

  const hasPanel = actionsEnabled;
  const ArenaTag = interactive && !hasPanel ? 'button' : 'div';

  const [panelOpen, setPanelOpen] = React.useState(Boolean(defaultPanelOpen));
  const styles = chipStyles({
    reserve: hasPanel && !actionsBelow,
    panelOpen,
    clickable: interactive,
    disabled: interactive && disabled,
    actionsBelow,
  });


  const bodyIsButton = interactive && hasPanel;

  const activate = (e: React.SyntheticEvent) => {
    e.stopPropagation();
    if (interactive && !disabled && onClick) onClick();
  };

  const focusableRef = React.useRef<HTMLElement | null>(null);
  const kebabWrapRef = React.useRef<HTMLElement | null>(null);
  const panelRef = React.useRef<HTMLElement | null>(null);
  const setFocusable = (node: HTMLElement | null) => {
    focusableRef.current = node;
    if (typeof ref === 'function') ref(node);
    else if (ref) ref.current = node;
  };

  const kebabEl = (): HTMLElement | null =>
    (kebabWrapRef.current?.firstElementChild instanceof HTMLElement ? kebabWrapRef.current.firstElementChild : null);

  const openedByUser = React.useRef(false);
  React.useEffect(() => {
    if (!panelOpen || !openedByUser.current) return;
    openedByUser.current = false;
    const panel = panelRef.current;
    if (!panel) return;

    const first = panel.querySelector<HTMLElement>('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');
    if (first) first.focus();
  }, [panelOpen]);

  const body = (
    <>
      <span className={styles.title()} data-arena-part={manifest.parts.title}>{title}</span>
      {showTime && (
        <span className={styles.time()} data-arena-part={manifest.parts.time}>{timeLabel}</span>
      )}
      {details.slice(0, shownDetails).map((line, i) => (
        <span key={`d${i}`} className={styles.detail()} data-arena-part={manifest.parts.detail}>{line}</span>
      ))}
      {!interactive && details.slice(shownDetails).map((line, i) => (
        <span key={`s${i}`} className={styles.detailShed()} data-arena-part={manifest.parts.detailShed}>{line}</span>
      ))}
    </>
  );
  const name = [title, dateLabel, timeLabel, ...details].join(', ');

  return (
    <ArenaTag ref={bodyIsButton ? undefined : setFocusable}

      type={interactive && !hasPanel ? 'button' : undefined}
      tabIndex={bodyIsButton ? undefined : tabIndex}
      onClick={hasPanel ? undefined : activate}
      aria-label={interactive && !hasPanel ? name : undefined}
      aria-disabled={interactive && !hasPanel && disabled ? 'true' : undefined}
      onKeyDown={hasPanel ? (e) => {

        if (e.key === 'Escape' && panelOpen) {
          e.stopPropagation();
          setPanelOpen(false);
          const kebab = kebabEl();
          if (kebab) kebab.focus();
          return;
        }
        const kebab = kebabEl();
        if (!kebab) return;
        if (e.key === 'ArrowRight' && e.target !== kebab) {
          e.preventDefault(); e.stopPropagation(); kebab.focus();
        } else if (e.key === 'ArrowLeft' && e.target === kebab && focusableRef.current) {
          e.preventDefault(); e.stopPropagation(); focusableRef.current.focus();
        }
      } : undefined}
      id={domId}
      className={styles.chip()} data-arena-part={manifest.parts.chip}
      style={{ ...box,
        background: arenaCatTint(ink),
        borderLeftColor: ink }}>
      {hasPanel ? (
        <>
          {interactive ? (
            <button type="button" ref={setFocusable} tabIndex={tabIndex}
              onClick={activate}
              aria-label={name}
              aria-disabled={disabled ? 'true' : undefined}

              className={styles.chipBody()} data-arena-part={manifest.parts.chipBody}>
              {body}
            </button>
          ) : (
            <span ref={setFocusable} tabIndex={tabIndex} onClick={activate}
              className={styles.chipBody()} data-arena-part={manifest.parts.chipBody}>
              {body}
            </span>
          )}
          <span ref={kebabWrapRef} className={styles.kebabWrap()} data-arena-part={manifest.parts.kebabWrap}>
            <ArenaIconButton icon="ph-bold ph-dots-three-vertical" label={locale.calendarEventActions} size="sm"
              tabStop={false}
              onClick={() => { openedByUser.current = !panelOpen; setPanelOpen((o) => !o); }} />
            {panelOpen && (
              <span ref={panelRef} className={styles.panel()} data-arena-part={manifest.parts.panel} data-arena-boundary="">
                {actions}
              </span>
            )}
          </span>
        </>
      ) : body}
    </ArenaTag>
  );
});

// frameworks/angular/components/display/arena-calendar-event/ArenaCalendarEvent.ts
import {
  ChangeDetectionStrategy, Component, DestroyRef, ElementRef, afterRenderEffect, booleanAttribute,
  computed, inject, input, output, signal, viewChild,
} from '@angular/core';
import type { ArenaCatSlot } from '../../../Api.generated';
import { arenaCatColor, arenaCatTint } from '../../../DataVisuals';
import { arenaPublished } from '../../../ProjectedInputs';
import { ARENA_LOCALE } from '../../../ArenaLocale';
import { ArenaIconButton } from '../../forms/arena-icon-button/ArenaIconButton';
import { ArenaCalendarState } from '../arena-calendar/ArenaCalendarState';
import {
  type EventTimes, ARENA_DATE_OPTIONS, arenaFormatDate, arenaVisibleDetails, arenaFormatHM, arenaShowsTime, arenaStacksActions,
} from '../arena-calendar/CalendarInternals';
import { arenaCalendarEventStyles } from './ArenaCalendarEvent.variants';
import manifest from '../arena-calendar/ArenaCalendar.classes.generated';

const FOCUSABLE = 'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])';

let seq = 0;

@Component({
  selector: 'arena-calendar-event',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ArenaIconButton],
  host: { style: 'display: contents', '[attr.title]': 'null', '[attr.id]': 'null' },
  template: `
    @if (across(); as across) {
      @if (hasPanel()) {
        <div [id]="domId" [class]="chipClass()" [attr.data-arena-part]="parts.chip" [style]="across"
             [style.top.px]="topPx()" [style.height.px]="heightPx()"
             [style.background]="tint()" [style.borderLeftColor]="ink()"
             (keydown)="onKeydown($event)">
          @if (interactive()) {
            <button #focusable type="button" tabindex="-1" [class]="bodyClass()" [attr.data-arena-part]="parts.chipBody"
                    [attr.aria-label]="label()" [attr.aria-disabled]="inert()"
                    (click)="onActivate($event)">
              <span [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ heading() }}</span>
              @if (showTime()) {
                <span [class]="styles().time()" [attr.data-arena-part]="parts.time">{{ timeLabel() }}</span>
              }
              @for (line of drawnDetails(); track $index) {
                <span [class]="styles().detail()" [attr.data-arena-part]="parts.detail">{{ line }}</span>
              }
            </button>
          } @else {
            <span #focusable tabindex="-1" [class]="bodyClass()" [attr.data-arena-part]="parts.chipBody" (click)="onActivate($event)">
              <span [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ heading() }}</span>
              @if (showTime()) {
                <span [class]="styles().time()" [attr.data-arena-part]="parts.time">{{ timeLabel() }}</span>
              }
              @for (line of drawnDetails(); track $index) {
                <span [class]="styles().detail()" [attr.data-arena-part]="parts.detail">{{ line }}</span>
              }
              @for (line of shedDetails(); track $index) {
                <span [class]="styles().detailShed()" [attr.data-arena-part]="parts.detailShed">{{ line }}</span>
              }
            </span>
          }
          <span #kebabWrap [class]="kebabClass()" [attr.data-arena-part]="parts.kebabWrap">
            <arena-icon-button icon="ph-bold ph-dots-three-vertical" [label]="locale.calendarEventActions" size="sm"
                               [tabStop]="false" (click)="togglePanel()" />
            @if (panelOpen()) {
              <span #panel [class]="styles().panel()" [attr.data-arena-part]="parts.panel" data-arena-boundary [style.zIndex]="1">
                <ng-content select="[actions]" />
              </span>
            }
          </span>
        </div>
      } @else if (interactive()) {
        <button #focusable [id]="domId" type="button" tabindex="-1" [class]="chipClass()" [attr.data-arena-part]="parts.chip"
                [style]="across" [style.top.px]="topPx()" [style.height.px]="heightPx()"
                [style.background]="tint()" [style.borderLeftColor]="ink()"
                [attr.aria-label]="label()" [attr.aria-disabled]="inert()"
                (click)="onActivate($event)">
          <span [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ heading() }}</span>
          @if (showTime()) {
            <span [class]="styles().time()" [attr.data-arena-part]="parts.time">{{ timeLabel() }}</span>
          }
          @for (line of drawnDetails(); track $index) {
            <span [class]="styles().detail()" [attr.data-arena-part]="parts.detail">{{ line }}</span>
          }
        </button>
      } @else {
        <div #focusable [id]="domId" tabindex="-1" [class]="chipClass()" [attr.data-arena-part]="parts.chip"
             [style]="across" [style.top.px]="topPx()" [style.height.px]="heightPx()"
             [style.background]="tint()" [style.borderLeftColor]="ink()"
             (click)="onActivate($event)">
          <span [class]="styles().title()" [attr.data-arena-part]="parts.title">{{ heading() }}</span>
          @if (showTime()) {
            <span [class]="styles().time()" [attr.data-arena-part]="parts.time">{{ timeLabel() }}</span>
          }
          @for (line of drawnDetails(); track $index) {
            <span [class]="styles().detail()" [attr.data-arena-part]="parts.detail">{{ line }}</span>
          }
          @for (line of shedDetails(); track $index) {
            <span [class]="styles().detailShed()" [attr.data-arena-part]="parts.detailShed">{{ line }}</span>
          }
        </div>
      }
    }
  `,
})
export class ArenaCalendarEvent {
  protected readonly parts = manifest.parts;

  /** Stable identity, so a host can switch on it rather than on the title. */
  readonly id = input.required<string>();
  /** What the chip reads. */
  readonly title = input.required<string>();
  /** ISO datetime the event begins. */
  readonly start = input.required<string>();
  /** ISO datetime the event ends. */
  readonly end = input.required<string>();
  /** Identity colour. Give the same entity the same slot everywhere and it keeps its colour across views. */
  readonly colorId = input<ArenaCatSlot>();
  /** Lines drawn under the time label, one per entry, each truncated to a single line: the people involved, a room, a capacity. Arena decides how many fit, shedding the last first and then the time label, and every entry reaches what the chip announces whether it is drawn or shed. */
  readonly details = input<readonly string[], readonly string[] | undefined>([], { transform: (value) => value ?? [] });
  /** Whether the chip can be activated. A boolean rather than "is `click` bound?", because Arena never derives what it draws from what a consumer listens for, and the same member `ArenaTableRow.interactive` is for the same reason. An interactive chip is a <button> a keyboard user reaches with Enter from the hour cell it overlaps; a non-interactive one draws the same chip with no role and no activation, so a read-only schedule announces events rather than a screenful of buttons that do nothing. */
  readonly interactive = input(false, { transform: booleanAttribute });
  /** Whether the chip shows its action button. A boolean rather than "is the actions slot filled?": Arena never derives what it draws from what a consumer listens for, because projected content is not inspectable in at least one platform, so gating the drawing on it is a divergence waiting to happen. */
  readonly actionsEnabled = input(false, { transform: booleanAttribute });
  /** Whether the chip is drawn but cannot be activated: an event a consumer's rules lock, such as one already past or owned by someone else. It reflects through `aria-disabled` rather than the native `disabled` attribute, so the chip keeps its place in the grid's roving Tab sequence and is announced as unavailable instead of disappearing from it. With `interactive` false there is nothing to activate and the chip is inert already. */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** The chip was activated. No payload: the consumer wrote this element, so they already hold the event this is about. Never emitted while `disabled`. */
  readonly click = output<void>();

  private readonly times = arenaPublished<EventTimes>(
    () => ({ id: this.id(), start: this.start(), end: this.end() }),
  );

  protected readonly domId = `arena-calendar-event-${seq++}`;

  private readonly state = inject(ArenaCalendarState);
  protected readonly locale = inject(ARENA_LOCALE);
  private readonly destroyRef = inject(DestroyRef);
  private readonly focusable = viewChild<ElementRef<HTMLElement>>('focusable');
  private readonly kebabWrap = viewChild<ElementRef<HTMLElement>>('kebabWrap');
  private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');
  private openedByUser = false;

  protected readonly panelOpen = signal(false);

  protected readonly hasPanel = computed(() => this.actionsEnabled());

  private readonly placement = computed(() => this.state.placementOf(this));

  protected readonly topPx = computed(() => {
    const at = this.placement();
    return at ? this.state.y(at.startMin) : 0;
  });

  protected readonly heightPx = computed(() => {
    const at = this.placement();
    return at ? this.state.y(at.endMin) - this.state.y(at.startMin) : 0;
  });

  protected readonly across = computed(() => {
    const at = this.placement();
    if (!at) return null;
    const columns = this.state.days().length;
    const leftShare = ((at.dayIndex + at.col / at.cols) / columns) * 100;
    const widthShare = (1 / (at.cols * columns)) * 100;
    return { left: `${leftShare}%`, right: `${100 - leftShare - widthShare}%` };
  });

  protected readonly showTime = computed(() => {
    const at = this.placement();
    return at !== null && arenaShowsTime(this.heightPx(), this.state.slotWidth(at.cols));
  });

  protected readonly shown = computed(() => {
    const at = this.placement();
    return at === null ? 0 : arenaVisibleDetails(this.heightPx(), this.state.slotWidth(at.cols), this.details().length);
  });
  protected readonly drawnDetails = computed(() => this.details().slice(0, this.shown()));
  protected readonly shedDetails = computed(() => this.details().slice(this.shown()));

  protected readonly actionsBelow = computed(() => {
    const at = this.placement();
    return at !== null && arenaStacksActions(this.heightPx(), this.state.slotWidth(at.cols));
  });

  protected readonly ink = computed(() => arenaCatColor(this.colorId() ?? 1));

  protected readonly tint = computed(
    () => arenaCatTint(this.ink()),
  );

  protected readonly timeLabel = computed(() => {
    const at = this.placement();
    return at ? `${arenaFormatHM(at.startMin)} – ${arenaFormatHM(at.endMin)}` : '';
  });

  protected readonly label = computed(() => {
    const at = this.placement();
    if (!at) return null;
    const day = arenaFormatDate(at.dayIso, this.locale.locale, ARENA_DATE_OPTIONS.dayName);
    return [this.heading(), day, this.timeLabel(), ...this.details()].join(', ');
  });

  protected readonly inert = computed(() => (this.disabled() ? 'true' : null));

  protected readonly heading = computed(() => {
    for (const [member, value] of [
      ['id', this.id()], ['title', this.title()], ['start', this.start()], ['end', this.end()],
    ] as const) {
      if (value.trim() === '') throw new Error(`ArenaCalendarEvent: \`${member}\` is required`);
    }
    return this.title();
  });

  protected readonly styles = computed(() => arenaCalendarEventStyles());

  protected readonly chipClass = computed(() => arenaCalendarEventStyles({
    reserve: this.hasPanel() && !this.actionsBelow(),
    panelOpen: this.panelOpen(),
    clickable: this.interactive() && !this.disabled(),
    disabled: this.interactive() && this.disabled(),
  }).chip());

  protected readonly bodyClass = computed(
    () => arenaCalendarEventStyles({ disabled: this.interactive() && this.disabled() }).chipBody(),
  );

  protected readonly kebabClass = computed(
    () => arenaCalendarEventStyles({ actionsBelow: this.actionsBelow() }).kebabWrap(),
  );

  constructor() {
    this.state.register(this, {
      domId: this.domId,
      focus: () => this.focusable()?.nativeElement.focus(),
      times: this.times,
    });
    this.destroyRef.onDestroy(() => this.state.release(this));

    afterRenderEffect(() => {
      if (!this.panelOpen() || !this.openedByUser) return;
      this.openedByUser = false;
      this.panel()?.nativeElement.querySelector<HTMLElement>(FOCUSABLE)?.focus();
    });
  }

  protected togglePanel(): void {
    this.openedByUser = !this.panelOpen();
    this.panelOpen.update((open) => !open);
  }

  protected onActivate(event: MouseEvent): void {
    event.stopPropagation();
    if (this.interactive() && !this.disabled()) this.click.emit();
  }

  protected onKeydown(event: KeyboardEvent): void {
    const kebab = this.kebabWrap()?.nativeElement.querySelector<HTMLElement>('button');
    if (event.key === 'Escape' && this.panelOpen()) {
      event.stopPropagation();
      this.panelOpen.set(false);
      kebab?.focus();
      return;
    }
    if (!kebab) return;
    if (event.key === 'ArrowRight' && event.target !== kebab) {
      event.preventDefault();
      event.stopPropagation();
      kebab.focus();
    } else if (event.key === 'ArrowLeft' && event.target === kebab) {
      event.preventDefault();
      event.stopPropagation();
      this.focusable()?.nativeElement.focus();
    }
  }
}
