// frameworks/angular/components/forms/arena-checkbox/ArenaCheckbox.ts
import {
  ChangeDetectionStrategy, Component, booleanAttribute, computed, input, output,
} from '@angular/core';
import { arenaCheckboxStyles } from './ArenaCheckbox.variants';
import manifest from './ArenaCheckbox.classes.generated';

export const ARENA_CHECK_GLYPH_STYLE = { width: 'var(--sp-3)', height: 'var(--sp-3)' };
export const ARENA_CHECK_STROKE_STYLE = { strokeWidth: 'var(--bw-strong)' };

@Component({
  selector: 'arena-checkbox',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    style: 'display: contents',
    '[attr.name]': 'null',
  },
  template: `
    <label [class]="styles().root()" [attr.data-arena-part]="parts.root">
      <span [class]="styles().box()" [attr.data-arena-part]="parts.box">
        @if (checked()) {
          <svg [class]="styles().check()" [attr.data-arena-part]="parts.check" viewBox="0 0 12 12" fill="none" [style]="glyph">
            <path d="M2 6l3 3 5-6" stroke="currentColor" stroke-linecap="round"
                  stroke-linejoin="round" [style]="glyphStroke"></path>
          </svg>
        }
      </span>
      @if (label(); as text) {
        <span [class]="styles().label()" [attr.data-arena-part]="parts.label">{{ text }}</span>
      }
      <input type="checkbox" [class]="styles().input()" [attr.data-arena-part]="parts.input" [checked]="checked()"
             [attr.name]="name()" [attr.value]="value()" [required]="required()"
             [disabled]="disabled()" (change)="onChange($event)" />
    </label>
  `,
})
export class ArenaCheckbox {
  protected readonly parts = manifest.parts;

  /** Whether it is ticked. */
  readonly checked = input(false, { transform: booleanAttribute });
  /** Text beside the box. */
  readonly label = input<string>();
  /** Blocks toggling and dims it. */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Must be checked for the form to submit. */
  readonly required = input(false, { transform: booleanAttribute });
  /** Submitted with the form. */
  readonly name = input<string>();
  /** The value submitted under `name` when checked. */
  readonly value = input<string>();
  /** Toggled; carries the new checked state. */
  readonly change = output<boolean>();

  protected readonly glyph = ARENA_CHECK_GLYPH_STYLE;
  protected readonly glyphStroke = ARENA_CHECK_STROKE_STYLE;

  protected readonly styles = computed(() => arenaCheckboxStyles({
    checked: this.checked(), disabled: this.disabled(),
  }));

  protected onChange(event: Event): void {
    event.stopPropagation();
    this.change.emit((event.target as HTMLInputElement).checked);
  }
}

// frameworks/react/components/forms/arena-checkbox/ArenaCheckbox.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaCheckbox.classes.generated.ts';

export interface ArenaCheckboxProps {

  /** Whether it is ticked. */
  checked?: boolean;

  /** Text beside the box. */
  label?: string;

  /** Blocks toggling and dims it. */
  disabled?: boolean;

  /** Must be checked for the form to submit. */
  required?: boolean;

  /** Submitted with the form. */
  name?: string;

  /** The value submitted under `name` when checked. */
  value?: string;

  /** Toggled; carries the new checked state. */
  onChange?: (checked: boolean) => void;
}


const arenaCheckboxStyles = arenaStyles(manifest);

export function ArenaCheckbox({ checked = false, onChange, label, disabled = false, required = false, name, value }: ArenaCheckboxProps) {
  const styles = arenaCheckboxStyles({ checked, disabled });
  return (
    <label className={styles.root()} data-arena-part={manifest.parts.root}>
      <span className={styles.box()} data-arena-part={manifest.parts.box}>
        {checked && (
          <svg className={styles.check()} data-arena-part={manifest.parts.check} viewBox="0 0 12 12" fill="none">
            <path d="M2 6l3 3 5-6" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        )}
      </span>
      {label && <span className={styles.label()} data-arena-part={manifest.parts.label}>{label}</span>}
      <input type="checkbox" checked={checked} name={name} value={value} required={required}
        onChange={(e) => onChange && onChange(e.target.checked)} disabled={disabled}
        className={styles.input()} data-arena-part={manifest.parts.input} />
    </label>
  );
}
