// frameworks/angular/components/navigation/arena-tabs/ArenaTabs.ts
import {
  ChangeDetectionStrategy, Component, DestroyRef, ElementRef, Injector, computed, contentChildren,
  inject, input, output, signal, viewChildren,
} from '@angular/core';
import { FocusKeyManager, type FocusableOption } from '@angular/cdk/a11y';
import { ArenaTab } from '../arena-tab/ArenaTab';
import { ArenaTabsState } from './ArenaTabsState';
import { arenaTabsStyles } from './ArenaTabs.variants';
import manifest from './ArenaTabs.classes.generated';
import { ArenaIdGenerator } from '../../../ArenaIds';

@Component({
  selector: 'arena-tabs',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [ArenaTabsState],
  host: {
    'data-arena-boundary': '', style: 'display: contents' },
  template: `
    <div role="tablist" [class]="styles().root()" [attr.data-arena-part]="parts.root" (keydown)="onKeydown($event)">
      @for (tab of tabs(); track tab.value(); let i = $index) {
        <button #tabButton type="button" role="tab" [class]="tabClass(tab.value())" [attr.data-arena-part]="parts.tab"
                [attr.id]="tabId(tab.value())" [attr.aria-controls]="panelId(tab.value())"
                [attr.aria-selected]="tab.value() === active()"
                [attr.tabindex]="i === stopIndex() ? 0 : -1"
                (click)="select(tab.value())">{{ tab.label() }}</button>
      }
    </div>
    <ng-content />
  `,
})
export class ArenaTabs {
  protected readonly parts = manifest.parts;

  /** The selected tab's value. Omit and pass `defaultValue` to let it govern itself. */
  readonly value = input<string>();
  /** The initially selected value when uncontrolled. Defaults to the first tab. */
  readonly defaultValue = input<string>();
  /** A different tab was chosen; carries its value. */
  readonly change = output<string>();

  private readonly base = inject(ArenaIdGenerator).next('arena-tabs');
  private readonly chosen = signal<string | undefined>(undefined);
  private readonly state = inject(ArenaTabsState);
  private readonly injector = inject(Injector);
  private readonly destroyRef = inject(DestroyRef);

  protected readonly tabs = contentChildren(ArenaTab);

  private readonly buttons = viewChildren<ElementRef<HTMLButtonElement>>('tabButton');

  private readonly options = computed<FocusableOption[]>(() => this.buttons()
    .map((ref) => ({ focus: () => ref.nativeElement.focus() })));

  private readonly keys = new FocusKeyManager(this.options, this.injector)
    .withHorizontalOrientation('ltr')
    .withVerticalOrientation(false)
    .withWrap();

  protected readonly active = computed(() => this.value()
    ?? this.chosen()
    ?? this.defaultValue()
    ?? this.tabs()[0]?.value());

  protected readonly stopIndex = computed(() => {
    const at = this.tabs().findIndex((tab) => tab.value() === this.active());
    return at === -1 ? 0 : at;
  });

  protected readonly styles = computed(() => arenaTabsStyles());

  constructor() {
    this.state.selected = this.active;
    this.state.tabId = (value: string) => this.idFor('tab', value);
    this.state.panelId = (value: string) => this.idFor('panel', value);

    const sub = this.keys.change.subscribe((index) => {
      const tab = this.tabs()[index];
      if (tab) this.select(tab.value());
    });
    this.destroyRef.onDestroy(() => {
      sub.unsubscribe();
      this.keys.destroy();
    });
  }

  protected tabClass(value: string): string {
    return arenaTabsStyles({ selected: value === this.active() }).tab();
  }

  protected tabId(value: string): string | null {
    return this.idFor('tab', value);
  }

  protected panelId(value: string): string | null {
    return this.idFor('panel', value);
  }

  protected select(value: string): void {
    if (value === this.active()) return;
    this.chosen.set(value);
    this.change.emit(value);
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (this.keys.activeItemIndex !== this.stopIndex()) this.keys.updateActiveItem(this.stopIndex());
    this.keys.onKeydown(event);
  }

  private idFor(kind: 'tab' | 'panel', value: string): string | null {
    const at = this.tabs().findIndex((tab) => tab.value() === value);
    return at === -1 ? null : `${this.base}-${kind}-${at}`;
  }
}

// frameworks/react/components/navigation/arena-tabs/ArenaTabs.tsx
import React, { useId, useRef, useState } from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaTabs.classes.generated.ts';

export interface ArenaTabsProps {

  /** The tabs. Which one is selected, which is the strip's tab stop, the ids wiring each to its panel and how the choice is reported are the strip's to settle, and none of it is a member here. EVERY tab's content mounts: one panel per tab is rendered and the inactive ones are hidden, because each tab's aria-controls must reference a tabpanel that exists. So a panel's side effects run immediately rather than on first selection. */
  children?: React.ReactNode;

  /** The selected tab's value. Omit and pass `defaultValue` to let it govern itself. */
  value?: string;

  /** The initially selected value when uncontrolled. Defaults to the first tab. */
  defaultValue?: string;

  /** A different tab was chosen; carries its value. */
  onChange?: (value: string) => void;
}


interface ArenaTabInjected {
  /** The selected tab's value. Omit and pass `defaultValue` to let it govern itself. */
  value?: string;
  /** The tabs. Which one is selected, which is the strip's tab stop, the ids wiring each to its panel and how the choice is reported are the strip's to settle, and none of it is a member here. EVERY tab's content mounts: one panel per tab is rendered and the inactive ones are hidden, because each tab's aria-controls must reference a tabpanel that exists. So a panel's side effects run immediately rather than on first selection. */
  children?: React.ReactNode;
  selected: boolean;
  tabStop: boolean;
  tabId: string;
  panelId: string;
  onSelect: (value: string) => void;
}

const arenaTabsStyles = arenaStyles(manifest);

export function ArenaTabs({ children, value, defaultValue, onChange }: ArenaTabsProps) {

  const base = `tabs-${useId().replace(/:/g, '')}`;

  const items = React.Children.toArray(children)
    .filter((c): c is React.ReactElement<Partial<ArenaTabInjected>> => React.isValidElement(c));
  const [internal, setInternal] = useState(defaultValue ?? items[0]?.props.value);
  const active = value ?? internal;

  const at = items.findIndex((c) => c.props.value === active);
  const stop = at === -1 ? 0 : at;
  const listRef = useRef<HTMLDivElement | null>(null);
  const select = (v: string) => { setInternal(v); onChange && onChange(v); };

  const tabId = (i: number) => `${base}-tab-${i}`;
  const panelId = (i: number) => `${base}-panel-${i}`;

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') return;

    if (items.length === 0) return;
    e.preventDefault();
    const next = (stop + (e.key === 'ArrowRight' ? 1 : -1) + items.length) % items.length;
    const target = items[next];
    if (target?.props.value !== undefined) select(target.props.value);
    const buttons = listRef.current?.querySelectorAll<HTMLElement>('[role="tab"]') ?? [];
    buttons[next]?.focus();
  };

  return (
    <>
      <div role="tablist" ref={listRef} onKeyDown={onKeyDown} className={arenaTabsStyles().root()} data-arena-part={manifest.parts.root} {...arenaTabsStyles().$data.root()} data-arena-boundary="">
        {items.map((child, i) => React.cloneElement(child, {
          selected: i === at,

          tabStop: i === stop,
          tabId: tabId(i),
          panelId: panelId(i),
          onSelect: select,
        }))}
      </div>
      {

}
      {items.map((child, i) => (

        <div key={child.key} role="tabpanel" tabIndex={i === at ? 0 : -1}
          id={panelId(i)} aria-labelledby={tabId(i)} hidden={i !== at}
          className={arenaTabsStyles({ selected: i === at }).panel()} data-arena-part={manifest.parts.panel} {...arenaTabsStyles({ selected: i === at }).$data.panel()} data-arena-boundary="">
          {child.props.children}
        </div>
      ))}
    </>
  );
}
