// frameworks/angular/components/charts/arena-doughnut-chart/ArenaDoughnutChart.ts
import { ChangeDetectionStrategy, Component, computed, ElementRef, inject, input, output, signal, viewChild } from '@angular/core';
import { arenaContainerWidth } from '../../../ContainerSize';
import { ARENA_CHART_HEIGHT, ARENA_SR_ONLY, arenaValueWriter } from '../../../DataVisuals';
import { arenaDoughnutSlices } from '../ChartScales';
import { arenaArcPath } from '../ChartMarks';
import { arenaDoughnutRadii } from '../ChartAxis';
import { arenaLegendPlotWidth, arenaLegendStacked } from '../ChartLegend';
import { arenaChartTable, arenaOneSeries, arenaSeriesColors } from '../ChartSeries';
import type { ArenaChartLegendLayout, ArenaChartShape, ArenaNumberFormat, ArenaSeries } from '../../../Api.generated';
import { arenaDoughnutChartStyles } from './ArenaDoughnutChart.variants';
import manifest from './ArenaDoughnutChart.classes.generated';
import { ARENA_LOCALE } from '../../../ArenaLocale';
import { arenaPhrase } from '../../../Phrase';

const ASSUMED_WIDTH = 600;

const FRAME_STYLE = {
  display: 'flex', position: 'relative', width: '100%', gap: 'var(--chart-legend-gap)',
} as const satisfies Readonly<Record<string, string>>;

const DIM_OPACITY = 0.55;

const SVG_STYLE = { display: 'block', flexShrink: '0' } as const satisfies Readonly<Record<string, string>>;

const SEGMENT_STYLE = {
  transition: 'opacity var(--dur-hover) var(--ease-hover)', strokeWidth: 'var(--bw-strong)',
} as const satisfies Readonly<Record<string, string>>;

const CENTRE_LABEL_STYLE = { fontSize: 'var(--dz-text-lg)' } as const satisfies Readonly<Record<string, string>>;

@Component({
  selector: 'arena-doughnut-chart',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <div #frame [style]="frameStyle" [style.height.px]="height">
    <svg [attr.width]="arenaPlotWidth()" [attr.height]="height" role="img" [attr.aria-label]="name()"
         [style]="svgStyle" (pointerleave)="hover.set(null)">
      @for (segment of segments(); track segment.index) {
        @if (segment.path) {
          <path [attr.d]="segment.path" [attr.fill]="segment.color" stroke="var(--surface-card)"
                [attr.opacity]="hover() === null || hover() === segment.index ? 1 : dimOpacity"
                (pointerenter)="hover.set(segment.index)" (click)="sliceActivate.emit(segment.index)"
                [style]="segmentStyle" />
        }
      }
      @if (centre(); as segment) {
        <text [attr.x]="centreX()" [attr.y]="centreY()" text-anchor="middle" dominant-baseline="middle"
              fill="var(--bone)" font-family="var(--font-mono)"
              [style]="centreLabelStyle">{{ segment.percent }}%</text>
      }
    </svg>

    <div [class]="styles().legend()" [attr.data-arena-part]="parts.legend" role="group" [attr.aria-label]="legendName()">
      @for (segment of segments(); track segment.index) {
        <button type="button" [class]="styles().legendRow()" [attr.data-arena-part]="parts.legendRow"
                [style.opacity]="hover() === null || hover() === segment.index ? 1 : dimOpacity"
                (pointerenter)="hover.set(segment.index)" (pointerleave)="hover.set(null)"
                (focus)="hover.set(segment.index)" (blur)="hover.set(null)"
                (click)="sliceActivate.emit(segment.index)">
          <span aria-hidden="true" [class]="styles().legendSwatch()" [attr.data-arena-part]="parts.legendSwatch" [style.background]="segment.color"></span>
          <span [class]="styles().legendText()" [attr.data-arena-part]="parts.legendText">
            <span [class]="styles().legendLabel()" [attr.data-arena-part]="parts.legendLabel">{{ segment.label }}</span>
            <span [class]="styles().legendValue()" [attr.data-arena-part]="parts.legendValue">{{ segment.formatted }}</span>
          </span>
        </button>
      }
    </div>

    <table [style]="arenaSrOnly">
      <caption>{{ name() }}</caption>
      <thead><tr>@for (column of table().columns; track $index) { <th>{{ column }}</th> }</tr></thead>
      <tbody>
        @for (row of table().rows; track $index) {
          <tr><th scope="row">{{ row.header }}</th>@for (cell of row.cells; track $index) { <td>{{ cell }}</td> }</tr>
        }
      </tbody>
    </table>
    </div>
  `,
})
export class ArenaDoughnutChart {
  protected readonly locale = inject(ARENA_LOCALE);
  /** One label per slice, in the same order as the series' `values`. A label with no value at its index is dropped. */
  readonly labels = input.required<readonly string[]>();
  /** The parts, as one series whose values are read as shares of their own total. Exactly one series: a ring of two series is a sunburst, which is a different chart and not this one, so a second warns in development and is ignored. Per-slice identity goes in that series' `colorIds`. */
  readonly series = input.required<readonly ArenaSeries[]>();
  /** Names the chart for its accessible name and for the caption of its data table. Required and guarded rather than defaulted, because a fallback of the chart TYPE satisfies roles.label mechanically and tells a screen-reader user nothing, so two charts on one page announce identically. */
  readonly label = input.required<string>();
  /** Appended verbatim to every number the chart draws: the legend value and the accessible table. Not the centre label, which is a percentage rather than a value. */
  readonly valueSuffix = input<string>();
  /** Drawn verbatim before every number the chart writes, as valueSuffix is drawn after it. A currency that precedes its amount is the majority case worldwide and had no expression: with suffix alone, "1234.5 Bs." is what a chart drew where the table beside it read "Bs. 1.234,50", and the accessible table inherited the disagreement. */
  readonly valuePrefix = input<string>();
  /** How each number is written before the prefix and suffix are added: which locale, how many fraction digits, whether thousands are grouped, whether large numbers are compacted. Absent, the raw JavaScript number, which is what this chart drew before the member existed. */
  readonly valueFormat = input<ArenaNumberFormat>();
  /** Whether the ring keeps its hole or fills to the centre. 'pie' is the same chart with the same slices, the same legend and the same table, drawn solid. It costs the centre percentage, which has nowhere to go once the hole is gone: over a wedge it would put --bone on a --color-cat slot, a pair nothing checks for contrast because nothing had drawn it. The figure is not lost, it is in the legend row and in the accessible table, which is where every other number the chart writes already is. */
  readonly shape = input<ArenaChartShape, ArenaChartShape | undefined>(
    'doughnut',
    { transform: (value) => value ?? 'doughnut' },
  );
  /** How each legend row arranges its label and its figure. 'inline' puts them on one line, which is what fits a wide tile; 'stacked' puts the label above the figure; 'auto' measures the legend column and stacks when the row does not give. It exists because the two do not degrade equally: on one line the figure does not yield, so the label is what gets truncated, and a legend of numbers with nothing saying what they count is the opposite of a legend. The threshold is already declared, as the chart-legend-min and chart-legend-max tokens the ring width is clamped between; what was missing was the behaviour. */
  readonly legendLayout = input<ArenaChartLegendLayout, ArenaChartLegendLayout | undefined>(
    'auto',
    { transform: (value) => value ?? 'auto' },
  );
  /** A slice was activated, by pointer on the arc or on its legend row, or by keyboard on that row, which is a real button and answers Enter and Space without the component binding either. It carries the slice's index in the series' `values`. **In `values`, never in the drawn paths**, and that is the whole member: a slice worth zero paints nothing, so the shapes on screen and the entries in the array are two different lists, and a consumer indexing the SVG has to reproduce that omission from outside to translate one into the other. It is reverse engineering of a component's own DOM, which the next release breaks in silence. */
  readonly sliceActivate = output<number>();

  protected readonly parts = manifest.parts;
  protected readonly height = ARENA_CHART_HEIGHT;
  protected readonly arenaSrOnly = ARENA_SR_ONLY;
  protected readonly svgStyle = SVG_STYLE;
  protected readonly segmentStyle = SEGMENT_STYLE;
  protected readonly centreLabelStyle = CENTRE_LABEL_STYLE;
  protected readonly dimOpacity = DIM_OPACITY;
  protected readonly hover = signal<number | null>(null);

  private readonly write = computed(() => arenaValueWriter({
    prefix: this.valuePrefix(), suffix: this.valueSuffix(), format: this.valueFormat(),
  }));

  protected readonly frameStyle = FRAME_STYLE;

  private readonly frame = viewChild<ElementRef<HTMLElement>>('frame');

  private readonly measured = arenaContainerWidth(() => this.frame()?.nativeElement);

  private readonly width = computed(() => this.measured() ?? ASSUMED_WIDTH);

  protected readonly stacked = computed(() => arenaLegendStacked(this.legendLayout(), this.width()));

  protected readonly styles = computed(() => arenaDoughnutChartStyles({ stacked: this.stacked() }));

  protected readonly name = computed(() => {
    return arenaPhrase(this.shape() === 'pie' ? this.locale.doughnutChartPieName : this.locale.doughnutChartName, { label: this.label() });
  });

  protected readonly arenaPlotWidth = computed(() => arenaLegendPlotWidth(this.width()));
  protected readonly centre = computed(() => (this.shape() === 'pie' ? null : this.active()));
  protected readonly legendName = computed(() => (this.shape() === 'pie' ? this.locale.doughnutChartPieLegend : this.locale.doughnutChartLegend));
  protected readonly centreX = computed(() => this.arenaPlotWidth() / 2);
  protected readonly centreY = computed(() => this.height / 2);

  private readonly only = computed(() => arenaOneSeries(this.series(), 'ArenaDoughnutChart'));

  protected readonly segments = computed(() => {
    const only = this.only();
    const values = only.values;

    const colors = arenaSeriesColors(
      { ...only, colorIds: only.colorIds ?? values.map((_, index) => index + 1) }, values.length, 1,
    );
    const write = this.write();
    const centreX = this.centreX();
    const centreY = this.centreY();
    const { outer, inner } = arenaDoughnutRadii(this.arenaPlotWidth(), this.height, this.shape());
    return arenaDoughnutSlices(values).map((slice) => ({
      ...slice,
      color: colors[slice.index],
      label: this.labels()[slice.index] ?? '',
      formatted: write(values[slice.index]),
      path: slice.to > slice.from ? arenaArcPath(centreX, centreY, outer, inner, slice.from, slice.to) : '',
    }));
  });

  protected readonly table = computed(() => arenaChartTable(
    this.locale.chartTableCategory, this.series().slice(0, 1), this.labels(), this.write(),
  ));

  protected readonly active = computed(() => {
    const index = this.hover();
    return index === null ? null : this.segments()[index] ?? null;
  });
}

// frameworks/react/components/charts/arena-doughnut-chart/ArenaDoughnutChart.tsx
import React, { useState } from 'react';
import { useArenaContainerWidth } from '../../../UseArenaContainerWidth.ts';
import { arenaSrOnly, arenaValueWriter, ARENA_CHART_HEIGHT } from '../../../DataVisuals.ts';
import { arenaDoughnutSlices } from '../ChartScales.ts';
import { arenaArcPath } from '../ChartMarks.ts';
import { arenaDoughnutRadii } from '../ChartAxis.ts';
import { arenaLegendPlotWidth, arenaLegendStacked } from '../ChartLegend.ts';
import { arenaChartTable, arenaOneSeries, arenaSeriesColors } from '../ChartSeries.ts';

import type { ArenaChartLegendLayout, ArenaChartShape, ArenaNumberFormat, ArenaSeries } from '../../../Api.generated';
import { useArenaLocale } from '../../../ArenaLocale.ts';
import { arenaPhrase } from '../../../Phrase.ts';
import type { ArenaDoughnutChartClass } from '../../../Vocabulary.generated.ts';
import { arenaClassName } from '../../../VocabularyClass.ts';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaDoughnutChart.classes.generated.ts';

export interface ArenaDoughnutChartProps {
  className?: ArenaDoughnutChartClass;


  /** One label per slice, in the same order as the series' `values`. A label with no value at its index is dropped. */
  labels: readonly string[];

  /** The parts, as one series whose values are read as shares of their own total. Exactly one series: a ring of two series is a sunburst, which is a different chart and not this one, so a second warns in development and is ignored. Per-slice identity goes in that series' `colorIds`. */
  series: readonly ArenaSeries[];

  /** Names the chart for its accessible name and for the caption of its data table. Required and guarded rather than defaulted, because a fallback of the chart TYPE satisfies roles.label mechanically and tells a screen-reader user nothing, so two charts on one page announce identically. */
  label: string;

  /** Whether the ring keeps its hole or fills to the centre. 'pie' is the same chart with the same slices, the same legend and the same table, drawn solid. It costs the centre percentage, which has nowhere to go once the hole is gone: over a wedge it would put --bone on a --color-cat slot, a pair nothing checks for contrast because nothing had drawn it. The figure is not lost, it is in the legend row and in the accessible table, which is where every other number the chart writes already is. */
  shape?: ArenaChartShape;

  /** How each legend row arranges its label and its figure. 'inline' puts them on one line, which is what fits a wide tile; 'stacked' puts the label above the figure; 'auto' measures the legend column and stacks when the row does not give. It exists because the two do not degrade equally: on one line the figure does not yield, so the label is what gets truncated, and a legend of numbers with nothing saying what they count is the opposite of a legend. The threshold is already declared, as the chart-legend-min and chart-legend-max tokens the ring width is clamped between; what was missing was the behaviour. */
  legendLayout?: ArenaChartLegendLayout;

  /** A slice was activated, by pointer on the arc or on its legend row, or by keyboard on that row, which is a real button and answers Enter and Space without the component binding either. It carries the slice's index in the series' `values`. **In `values`, never in the drawn paths**, and that is the whole member: a slice worth zero paints nothing, so the shapes on screen and the entries in the array are two different lists, and a consumer indexing the SVG has to reproduce that omission from outside to translate one into the other. It is reverse engineering of a component's own DOM, which the next release breaks in silence. */
  onSliceActivate?: (index: number) => void;

  /** Appended verbatim to every number the chart draws: the legend value and the accessible table. Not the centre label, which is a percentage rather than a value. */
  valueSuffix?: string;

  /** Drawn verbatim before every number the chart writes, as valueSuffix is drawn after it. A currency that precedes its amount is the majority case worldwide and had no expression: with suffix alone, "1234.5 Bs." is what a chart drew where the table beside it read "Bs. 1.234,50", and the accessible table inherited the disagreement. */
  valuePrefix?: string;

  /** How each number is written before the prefix and suffix are added: which locale, how many fraction digits, whether thousands are grouped, whether large numbers are compacted. Absent, the raw JavaScript number, which is what this chart drew before the member existed. */
  valueFormat?: ArenaNumberFormat;
}


const arenaDoughnutChartStyles = arenaStyles(manifest);

export function ArenaDoughnutChart({ className, 
  labels, series, label, valueSuffix, valuePrefix, valueFormat,
  shape = 'doughnut', legendLayout = 'auto', onSliceActivate,
}: ArenaDoughnutChartProps) {
  const locale = useArenaLocale();
  if (!label) throw new Error('ArenaDoughnutChart: `label` is required (it names the chart for the accessible name, and nothing can derive that)');
  if (!labels) throw new Error('ArenaDoughnutChart: `labels` is required');
  if (!series) throw new Error('ArenaDoughnutChart: `series` is required');
  const [ref, measured] = useArenaContainerWidth();
  const [hover, setHover] = useState<number | null>(null);

  const width = measured ?? 600;
  const height = ARENA_CHART_HEIGHT;
  const only = arenaOneSeries(series, 'ArenaDoughnutChart');
  const values = only.values;
  const n = values.length;
  const fmt = arenaValueWriter({ prefix: valuePrefix, suffix: valueSuffix, format: valueFormat });
  const colors = arenaSeriesColors(
    { ...only, colorIds: only.colorIds ?? Array.from({ length: n }, (_, i) => i + 1) }, n, 1,
  );

  const stacked = arenaLegendStacked(legendLayout, width);
  const styles = arenaDoughnutChartStyles({ stacked });
  const plotW = arenaLegendPlotWidth(width);
  const cx = plotW / 2;
  const cy = height / 2;
  const { outer: rOuter, inner: rInner } = arenaDoughnutRadii(plotW, height, shape);

  const name = arenaPhrase(shape === 'pie' ? locale.doughnutChartPieName : locale.doughnutChartName, { label });
  const table = arenaChartTable(locale.chartTableCategory, series.slice(0, 1), labels, fmt);

  const segments = arenaDoughnutSlices(values);

  return (
    <div className={arenaClassName('ArenaDoughnutChart', undefined, className)} ref={ref} style={{ position: 'relative', width: '100%', height, display: 'flex', gap: 'var(--chart-legend-gap)' }}>
      <svg width={plotW} height={height} role="img" aria-label={name}
        onPointerLeave={() => setHover(null)} style={{ display: 'block', flexShrink: 0 }}>
        {segments.map(({ index, from, to }) => to > from && (
          <path key={index} d={arenaArcPath(cx, cy, rOuter, rInner, from, to)} fill={colors[index]}

            stroke="var(--surface-card)"
            opacity={hover === null || hover === index ? 1 : 0.55}
            onPointerEnter={() => setHover(index)} onClick={() => onSliceActivate?.(index)}
            style={{ transition: 'opacity var(--dur-hover) var(--ease-hover)', strokeWidth: 'var(--bw-strong)' }} />
        ))}
        {shape !== 'pie' && hover !== null && segments[hover] && (
          <text x={cx} y={cy} textAnchor="middle" dominantBaseline="middle"
            fill="var(--bone)" fontFamily="var(--font-mono)" style={{ fontSize: 'var(--dz-text-lg)' }}>
            {`${segments[hover].percent}%`}
          </text>
        )}
      </svg>

      {

}
      <div role="group" aria-label={shape === 'pie' ? locale.doughnutChartPieLegend : locale.doughnutChartLegend}
        className={styles.legend()} data-arena-part={manifest.parts.legend}>
        {values.map((_, i) => (
          <button key={i} type="button" onPointerEnter={() => setHover(i)} onPointerLeave={() => setHover(null)}
            onFocus={() => setHover(i)} onBlur={() => setHover(null)}
            onClick={() => onSliceActivate?.(i)}
            className={styles.legendRow()} data-arena-part={manifest.parts.legendRow}
            style={{ opacity: hover === null || hover === i ? 1 : 0.55 }}>
            <span aria-hidden="true" className={styles.legendSwatch()} data-arena-part={manifest.parts.legendSwatch} style={{ background: colors[i] }} />
            <span className={styles.legendText()} data-arena-part={manifest.parts.legendText}>
              <span className={styles.legendLabel()} data-arena-part={manifest.parts.legendLabel}>{labels[i] ?? ''}</span>
              <span className={styles.legendValue()} data-arena-part={manifest.parts.legendValue}>{fmt(values[i] ?? 0)}</span>
            </span>
          </button>
        ))}
      </div>

      <table style={arenaSrOnly}>
        <caption>{name}</caption>
        <thead><tr>{table.columns.map((column, i) => <th key={i}>{column}</th>)}</tr></thead>
        <tbody>
          {table.rows.map((row, i) => (
            <tr key={i}><th scope="row">{row.header}</th>{row.cells.map((cell, j) => <td key={j}>{cell}</td>)}</tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
