// frameworks/react/components/charts/arena-radar-chart/ArenaRadarChart.tsx
import React, { useState } from 'react';
import { useArenaContainerWidth } from '../../../UseArenaContainerWidth.ts';
import { arenaSrOnly, arenaAreaFill, arenaValueWriter, ARENA_CHART_HEIGHT } from '../../../DataVisuals.ts';
import { arenaLinearScale, arenaScaleValue } from '../ChartScales.ts';
import { arenaLinePoints } from '../ChartMarks.ts';
import {
  arenaPolarPoint, arenaPolarIndex, arenaPolarAnchor, arenaRadarRings, arenaRadarRadius, arenaRadarLabelRadius,
} from '../ChartPolar.ts';
import {
  arenaChartTable, arenaSeriesColors, arenaSeriesPointCount, arenaRadarDomain,
} from '../ChartSeries.ts';
import { arenaLegendStrip } from '../ChartLegend.ts';
import { arenaTooltipAnchor } from '../ChartTooltip.ts';
import { arenaCursorHandles, arenaCursorStep, arenaPointerClears, arenaPointerUpdates } from '../ChartPointer.ts';
import { chartPointR, chartPointRHover } from '../../../Tokens.generated.js';

import type { ArenaNumberFormat, ArenaSeries } from '../../../Api.generated';
import { useArenaLocale } from '../../../ArenaLocale.ts';
import { arenaPhrase } from '../../../Phrase.ts';
import type { ArenaRadarChartClass } from '../../../Vocabulary.generated.ts';
import { arenaClassName } from '../../../VocabularyClass.ts';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaRadarChart.classes.generated.ts';

export interface ArenaRadarChartProps {
  className?: ArenaRadarChartClass;


  /** One label per axis, in the same order as every series' `values`, running clockwise from 12 o'clock. Keep the count small: past eight or so the labels collide and the shape stops being readable, which is a limit of the form rather than of the drawing. */
  labels: readonly string[];

  /** The plotted series, drawn as one closed polygon each over the same axes. The shape is the reading, so two or three series is the useful case and more is a tangle. The ramp clamps at its last slot rather than cycling. */
  series: readonly ArenaSeries[];

  /** Names the chart for its accessible name and for the caption of its data table. This is the CHART's name, not a series': a series names itself. Required and guarded rather than defaulted, because a fallback of the chart TYPE satisfies roles.label mechanically and tells a screen-reader user nothing. */
  label: string;

  /** Fill each polygon at 18% of its series colour: a tint, never a gradient. Useful for one series, where the filled area reads as a footprint. Past one the fills overlap and the reader cannot tell which polygon an overlap belongs to, so leave it off and let the outlines carry the shape. */
  fill?: boolean;

  /** Appended verbatim to every number the chart draws: the tooltip and the accessible table. Carries its own leading space if one is wanted. */
  valueSuffix?: string;

  /** Drawn verbatim before every number the chart writes, as valueSuffix is drawn after it. */
  valuePrefix?: string;

  /** How each number is written before the prefix and suffix are added: which locale, how many fraction digits, whether thousands are grouped, whether large numbers are compacted. Absent, the raw JavaScript number. */
  valueFormat?: ArenaNumberFormat;

  /** The plot's height in px, the --chart-height token by default. The grid is a circle inscribed in the smaller of the plot's two axes, so this also caps how wide the shape gets. A number rather than a dimension string, because the chart does arithmetic with it to place every mark. */
  height?: number;
}


const arenaRadarChartStyles = arenaStyles(manifest);

export function ArenaRadarChart({ className, 
  labels, series, label, fill = false, valueSuffix, valuePrefix, valueFormat,
  height = ARENA_CHART_HEIGHT,
}: ArenaRadarChartProps) {
  const locale = useArenaLocale();
  const styles = arenaRadarChartStyles();
  if (!label) throw new Error('ArenaRadarChart: `label` is required (it names the chart for the accessible name, and nothing can derive that)');
  if (!labels) throw new Error('ArenaRadarChart: `labels` is required');
  if (!series) throw new Error('ArenaRadarChart: `series` is required');
  const [ref, measured] = useArenaContainerWidth();
  const [hover, setHover] = useState<number | null>(null);

  const width = measured ?? 600;
  const n = arenaSeriesPointCount(series);
  const fmt = arenaValueWriter({ prefix: valuePrefix, suffix: valueSuffix, format: valueFormat });

  const domain = arenaRadarDomain(series);
  const strip = arenaLegendStrip(height, series.length);
  const cx = width / 2;
  const cy = strip.plotH / 2;
  const outer = arenaRadarRadius(width, strip.plotH);
  const labelR = arenaRadarLabelRadius(width, strip.plotH);
  const radial = arenaLinearScale(domain.min, domain.max, 0, outer);
  const reach = (value: number) => Math.max(0, arenaScaleValue(radial, value));

  const colors = series.map((one, s) => arenaSeriesColors(one, 1, s + 1)[0] as string);
  const table = arenaChartTable(locale.chartTableAxis, series, labels, fmt);
  const rings = arenaRadarRings(domain);

  const name = arenaPhrase(locale.radarChartName, { label });

  const onPointer = (e: React.PointerEvent<SVGRectElement>, phase: string) => {
    if (!arenaPointerUpdates(e.pointerType, phase)) return;
    const svg = e.currentTarget.ownerSVGElement?.getBoundingClientRect();
    if (!svg) return;
    const index = arenaPolarIndex(cx, cy, e.clientX - svg.left, e.clientY - svg.top, n);
    if (index >= 0) setHover(index);
  };

  const onKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (!arenaCursorHandles(e.key, 'x')) return;
    e.preventDefault();
    setHover(arenaCursorStep(hover, e.key, n, 'x'));
  };

  return (
    <div className={arenaClassName('ArenaRadarChart', undefined, className)} ref={ref} style={{ position: 'relative', width: '100%', height }}>
      <div tabIndex={0} role="group" aria-label={name} onKeyDown={onKeyDown}
        style={{ display: 'block', outlineOffset: 'var(--focus-offset)' }}>
      <svg width="100%" height={strip.plotH} role="img" aria-label={name}
        style={{ display: 'block', overflow: 'visible' }}>
        {rings.map((value, i) => (
          <polygon key={i} fill="none" stroke="var(--border)" style={{ strokeWidth: 'var(--bw)' }}
            points={arenaLinePoints(Array.from({ length: n }, (_, a) => arenaPolarPoint(cx, cy, reach(value), a, n)))} />
        ))}

        {Array.from({ length: n }, (_, i) => {
          const tip = arenaPolarPoint(cx, cy, outer, i, n);
          return (
            <line key={i} x1={cx} y1={cy} x2={tip.x} y2={tip.y}
              stroke={hover === i ? 'var(--border-strong)' : 'var(--border)'} style={{ strokeWidth: 'var(--bw)' }} />
          );
        })}

        {fill && series.map((one, s) => (
          <polygon key={s} stroke="none" fill={arenaAreaFill(colors[s] as string)}
            points={arenaLinePoints(Array.from({ length: n },
              (_, a) => arenaPolarPoint(cx, cy, reach(one.values[a] ?? 0), a, n)))} />
        ))}

        {series.map((one, s) => (
          <polygon key={s} fill="none" stroke={colors[s]} strokeLinejoin="round"
            style={{ strokeWidth: 'var(--bw-strong)' }}
            points={arenaLinePoints(Array.from({ length: n },
              (_, a) => arenaPolarPoint(cx, cy, reach(one.values[a] ?? 0), a, n)))} />
        ))}

        {series.map((one, s) => Array.from({ length: n }, (_, a) => {
          const value = one.values[a];
          if (value === undefined) return null;
          const at = arenaPolarPoint(cx, cy, reach(value), a, n);
          return (
            <circle key={`${s}-${a}`} cx={at.x} cy={at.y} r={hover === a ? chartPointRHover : chartPointR}
              fill={colors[s]} stroke="var(--surface-card)" style={{ strokeWidth: 'var(--bw-strong)' }} />
          );
        }))}

        {Array.from({ length: n }, (_, i) => {
          const at = arenaPolarPoint(cx, cy, labelR, i, n);
          return (
            <text key={i} x={at.x} y={at.y} textAnchor={arenaPolarAnchor(i, n)} dominantBaseline="middle"
              fill="var(--text-muted)" fontFamily="var(--font-body)" style={{ fontSize: 'var(--dz-text-xs)' }}>{labels[i] ?? ''}</text>
          );
        })}

        <rect x={0} y={0} width="100%" height={strip.plotH} fill="transparent"
          onPointerMove={(e) => onPointer(e, 'move')} onPointerDown={(e) => onPointer(e, 'down')}
          onPointerLeave={(e) => { if (arenaPointerClears(e.pointerType)) setHover(null); }}
          onPointerCancel={() => setHover(null)} />
      </svg>
      </div>

      {strip.stripH > 0 && (
        <div aria-hidden="true" className={styles.legend()} data-arena-part={manifest.parts.legend} {...styles.$data.legend()} style={{ height: strip.stripH }}>
          {series.map((one, s) => (
            <span key={s} className={styles.legendItem()} data-arena-part={manifest.parts.legendItem} {...styles.$data.legendItem()}>
              <span className={styles.legendSwatch()} data-arena-part={manifest.parts.legendSwatch} {...styles.$data.legendSwatch()} style={{ background: colors[s] }} />
              <span className={styles.legendLabel()} data-arena-part={manifest.parts.legendLabel} {...styles.$data.legendLabel()}>{one.label}</span>
            </span>
          ))}
        </div>
      )}

      {hover !== null && hover < n && (
        <div className={styles.tooltip()} data-arena-part={manifest.parts.tooltip} {...styles.$data.tooltip()} style={{
          ...arenaTooltipAnchor(arenaPolarPoint(cx, cy, outer, hover, n).x,
            arenaPolarPoint(cx, cy, outer, hover, n).y),
        }}>
          <div className={styles.tooltipLabel()} data-arena-part={manifest.parts.tooltipLabel} {...styles.$data.tooltipLabel()}>{labels[hover]}</div>
          {series.map((one, s) => one.values[hover] !== undefined && (
            <div key={s} className={styles.tooltipValue()} data-arena-part={manifest.parts.tooltipValue} {...styles.$data.tooltipValue()}>
              {`${series.length > 1 ? `${one.label}: ` : ''}${fmt(one.values[hover] as number)}`}
            </div>
          ))}
        </div>
      )}

      <table style={arenaSrOnly}>
        <caption>{name}</caption>
        <thead><tr>{table.columns.map((column, i) => <th key={i}>{column}</th>)}</tr></thead>
        <tbody>
          {table.rows.map((row, i) => (
            <tr key={i}><th scope="row">{row.header}</th>{row.cells.map((cell, j) => <td key={j}>{cell}</td>)}</tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// frameworks/angular/components/charts/arena-radar-chart/ArenaRadarChart.ts
import {
  booleanAttribute, ChangeDetectionStrategy, Component, computed, ElementRef, inject, input, signal, viewChild,
} from '@angular/core';
import { arenaContainerWidth } from '../../../ContainerSize';
import {
  ARENA_CHART_HEIGHT, ARENA_SR_ONLY, arenaAreaFill, arenaValueWriter,
} from '../../../DataVisuals';
import { arenaLinearScale, arenaScaleValue } from '../ChartScales';
import { arenaLinePoints } from '../ChartMarks';
import {
  arenaPolarPoint, arenaPolarIndex, arenaPolarAnchor, arenaRadarRings, arenaRadarRadius, arenaRadarLabelRadius,
} from '../ChartPolar';
import {
  arenaChartTable, arenaSeriesColors, arenaSeriesPointCount, arenaRadarDomain,
} from '../ChartSeries';
import { arenaLegendStrip } from '../ChartLegend';
import { arenaTooltipAnchor } from '../ChartTooltip';
import { arenaCursorHandles, arenaCursorStep, arenaPointerClears, arenaPointerUpdates } from '../ChartPointer';
import { arenaRadarChartStyles } from './ArenaRadarChart.variants';
import manifest from './ArenaRadarChart.classes.generated';
import type { ArenaNumberFormat, ArenaSeries } from '../../../Api.generated';
import { chartPointR, chartPointRHover } from '../../../Tokens.generated';
import { ARENA_LOCALE } from '../../../ArenaLocale';
import { arenaPhrase } from '../../../Phrase';

const ASSUMED_WIDTH = 600;

const REGION_STYLE = { display: 'block', outlineOffset: 'var(--focus-offset)' } as const satisfies Readonly<Record<string, string>>;

const LINE_STYLE = { strokeWidth: 'var(--bw)' } as const satisfies Readonly<Record<string, string>>;

const CATEGORY_LABEL_STYLE = { fontSize: 'var(--dz-text-xs)' } as const satisfies Readonly<Record<string, string>>;

const SERIES_STROKE_STYLE = { strokeWidth: 'var(--bw-strong)' } as const satisfies Readonly<Record<string, string>>;




@Component({
  selector: 'arena-radar-chart',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    style: 'display:block;position:relative;width:100%',
    '[style.height.px]': 'height()',
  },
  template: `
    <div #region [style]="regionStyle" tabindex="0" role="group" [attr.aria-label]="name()"
         (keydown)="onKey($event)">
    <svg width="100%" [attr.height]="plotH()" role="img" [attr.aria-label]="name()"
         style="display:block;overflow:visible">
      @for (ring of rings(); track ring.value) {
        <polygon [attr.points]="ring.points" fill="none" stroke="var(--border)" [style]="lineStyle" />
      }

      @for (spoke of spokes(); track spoke.index) {
        <line [attr.x1]="centreX()" [attr.y1]="centreY()" [attr.x2]="spoke.x" [attr.y2]="spoke.y"
              [attr.stroke]="hover() === spoke.index ? 'var(--border-strong)' : 'var(--border)'"
              [style]="lineStyle" />
      }

      @if (fill()) {
        @for (shape of shapes(); track shape.key) {
          <polygon [attr.points]="shape.points" stroke="none" [attr.fill]="shape.areaFill" />
        }
      }

      @for (shape of shapes(); track shape.key) {
        <polygon [attr.points]="shape.points" fill="none" [attr.stroke]="shape.color"
                 stroke-linejoin="round" [style]="seriesStrokeStyle" />
      }

      @for (mark of marks(); track mark.key) {
        <circle [attr.cx]="mark.x" [attr.cy]="mark.y"
                [attr.r]="hover() === mark.axis ? pointRHover : pointR"
                [attr.fill]="mark.color" stroke="var(--surface-card)" [style]="seriesStrokeStyle" />
      }

      @for (spoke of spokes(); track spoke.index) {
        <text [attr.x]="spoke.labelX" [attr.y]="spoke.labelY" [attr.text-anchor]="spoke.anchor"
              dominant-baseline="middle"
              fill="var(--text-muted)" font-family="var(--font-body)"
              [style]="categoryLabelStyle">{{ spoke.label }}</text>
      }

      <rect x="0" y="0" width="100%" [attr.height]="plotH()" fill="transparent"
            (pointermove)="onPointer($event, 'move')" (pointerdown)="onPointer($event, 'down')"
            (pointerleave)="onPointerLeave($event)" (pointercancel)="hover.set(null)" />
    </svg>
    </div>

    @if (legend(); as keys) {
      <div aria-hidden="true" [class]="styles.legend()" [attr.data-arena-part]="parts.legend" [style.height.px]="stripH()">
        @for (key of keys; track key.index) {
          <span [class]="styles.legendItem()" [attr.data-arena-part]="parts.legendItem">
            <span [class]="styles.legendSwatch()" [attr.data-arena-part]="parts.legendSwatch" [style.background]="key.color"></span>
            <span [class]="styles.legendLabel()" [attr.data-arena-part]="parts.legendLabel">{{ key.label }}</span>
          </span>
        }
      </div>
    }

    @if (active(); as point) {
      <div [class]="styles.tooltip()" [attr.data-arena-part]="parts.tooltip" [style.left.px]="point.anchor.left" [style.top]="point.anchor.top">
        <div [class]="styles.tooltipLabel()" [attr.data-arena-part]="parts.tooltipLabel">{{ point.label }}</div>
        @for (reading of point.readings; track reading.key) {
          <div [class]="styles.tooltipValue()" [attr.data-arena-part]="parts.tooltipValue">{{ reading.name }}{{ reading.value }}</div>
        }
      </div>
    }

    <table [style]="arenaSrOnly">
      <caption>{{ name() }}</caption>
      <thead><tr>@for (column of table().columns; track $index) { <th>{{ column }}</th> }</tr></thead>
      <tbody>
        @for (row of table().rows; track $index) {
          <tr><th scope="row">{{ row.header }}</th>@for (cell of row.cells; track $index) { <td>{{ cell }}</td> }</tr>
        }
      </tbody>
    </table>
  `,
})
export class ArenaRadarChart {
  protected readonly locale = inject(ARENA_LOCALE);
  /** One label per axis, in the same order as every series' `values`, running clockwise from 12 o'clock. Keep the count small: past eight or so the labels collide and the shape stops being readable, which is a limit of the form rather than of the drawing. */
  readonly labels = input.required<readonly string[]>();
  /** The plotted series, drawn as one closed polygon each over the same axes. The shape is the reading, so two or three series is the useful case and more is a tangle. The ramp clamps at its last slot rather than cycling. */
  readonly series = input.required<readonly ArenaSeries[]>();
  /** Names the chart for its accessible name and for the caption of its data table. This is the CHART's name, not a series': a series names itself. Required and guarded rather than defaulted, because a fallback of the chart TYPE satisfies roles.label mechanically and tells a screen-reader user nothing. */
  readonly label = input.required<string>();
  /** Fill each polygon at 18% of its series colour: a tint, never a gradient. Useful for one series, where the filled area reads as a footprint. Past one the fills overlap and the reader cannot tell which polygon an overlap belongs to, so leave it off and let the outlines carry the shape. */
  readonly fill = input(false, { transform: booleanAttribute });
  /** Appended verbatim to every number the chart draws: the tooltip and the accessible table. Carries its own leading space if one is wanted. */
  readonly valueSuffix = input<string>();
  /** Drawn verbatim before every number the chart writes, as valueSuffix is drawn after it. */
  readonly valuePrefix = input<string>();
  /** How each number is written before the prefix and suffix are added: which locale, how many fraction digits, whether thousands are grouped, whether large numbers are compacted. Absent, the raw JavaScript number. */
  readonly valueFormat = input<ArenaNumberFormat>();
  /** The plot's height in px, the --chart-height token by default. The grid is a circle inscribed in the smaller of the plot's two axes, so this also caps how wide the shape gets. A number rather than a dimension string, because the chart does arithmetic with it to place every mark. */
  readonly height = input<number, number | undefined>(
    ARENA_CHART_HEIGHT,
    { transform: (value) => value ?? ARENA_CHART_HEIGHT },
  );

  protected readonly parts = manifest.parts;
  protected readonly styles = arenaRadarChartStyles();
  protected readonly arenaSrOnly = ARENA_SR_ONLY;
  protected readonly regionStyle = REGION_STYLE;
  protected readonly lineStyle = LINE_STYLE;
  protected readonly seriesStrokeStyle = SERIES_STROKE_STYLE;
  protected readonly categoryLabelStyle = CATEGORY_LABEL_STYLE;
  protected readonly pointR = chartPointR;
  protected readonly pointRHover = chartPointRHover;
  protected readonly hover = signal<number | null>(null);

  private readonly write = computed(() => arenaValueWriter({
    prefix: this.valuePrefix(), suffix: this.valueSuffix(), format: this.valueFormat(),
  }));

  private readonly region = viewChild<ElementRef<HTMLElement>>('region');

  private readonly measured = arenaContainerWidth(() => this.region()?.nativeElement);
  private readonly width = computed(() => this.measured() ?? ASSUMED_WIDTH);

  protected readonly name = computed(() => {
    return arenaPhrase(this.locale.radarChartName, { label: this.label() });
  });

  private readonly axes = computed(() => arenaSeriesPointCount(this.series()));
  private readonly domain = computed(() => arenaRadarDomain(this.series()));
  private readonly strip = computed(() => arenaLegendStrip(this.height(), this.series().length));
  protected readonly plotH = computed(() => this.strip().plotH);
  protected readonly stripH = computed(() => this.strip().stripH);
  protected readonly centreX = computed(() => this.width() / 2);
  protected readonly centreY = computed(() => this.strip().plotH / 2);
  private readonly outer = computed(() => arenaRadarRadius(this.width(), this.strip().plotH));
  private readonly labelR = computed(() => arenaRadarLabelRadius(this.width(), this.strip().plotH));

  private readonly radial = computed(() => arenaLinearScale(this.domain().min, this.domain().max, 0, this.outer()));

  private readonly reach = computed(() => {
    const radial = this.radial();
    return (value: number) => Math.max(0, arenaScaleValue(radial, value));
  });

  protected readonly colors = computed(
    () => this.series().map((one, index) => arenaSeriesColors(one, 1, index + 1)[0] as string),
  );

  protected readonly rings = computed(() => {
    const cx = this.centreX();
    const cy = this.centreY();
    const count = this.axes();
    const reach = this.reach();
    return arenaRadarRings(this.domain()).map((value) => ({
      value,
      points: arenaLinePoints(Array.from({ length: count }, (_, a) => arenaPolarPoint(cx, cy, reach(value), a, count))),
    }));
  });

  protected readonly spokes = computed(() => {
    const cx = this.centreX();
    const cy = this.centreY();
    const count = this.axes();
    const outer = this.outer();
    const labels = this.labels();
    const labelR = this.labelR();
    return Array.from({ length: count }, (_, index) => {
      const tip = arenaPolarPoint(cx, cy, outer, index, count);
      const at = arenaPolarPoint(cx, cy, labelR, index, count);
      return {
        index, x: tip.x, y: tip.y, label: labels[index] ?? '',
        labelX: at.x, labelY: at.y, anchor: arenaPolarAnchor(index, count),
      };
    });
  });

  protected readonly shapes = computed(() => {
    const cx = this.centreX();
    const cy = this.centreY();
    const count = this.axes();
    const reach = this.reach();
    const colors = this.colors();
    return this.series().map((one, index) => ({
      key: index,
      color: colors[index],
      areaFill: arenaAreaFill(colors[index] as string),
      points: arenaLinePoints(Array.from({ length: count },
        (_, a) => arenaPolarPoint(cx, cy, reach(one.values[a] ?? 0), a, count))),
    }));
  });

  protected readonly marks = computed(() => {
    const cx = this.centreX();
    const cy = this.centreY();
    const count = this.axes();
    const reach = this.reach();
    const colors = this.colors();
    return this.series().flatMap((one, index) => Array.from({ length: count }, (_, a) => ({ one, index, a }))
      .flatMap(({ a }) => {
        const value = one.values[a];
        if (value === undefined) return [];
        const at = arenaPolarPoint(cx, cy, reach(value), a, count);
        return [{ key: `${index}-${a}`, axis: a, x: at.x, y: at.y, color: colors[index] }];
      }));
  });

  protected readonly legend = computed(() => {
    if (this.strip().stripH === 0) return null;
    const colors = this.colors();
    return this.series().map((one, index) => ({ index, label: one.label, color: colors[index] }));
  });

  protected readonly table = computed(() => arenaChartTable(
    this.locale.chartTableAxis, this.series(), this.labels(), this.write(),
  ));

  protected readonly active = computed(() => {
    const index = this.hover();
    if (index === null || index >= this.axes()) return null;
    const write = this.write();
    const tip = arenaPolarPoint(this.centreX(), this.centreY(), this.outer(), index, this.axes());
    const many = this.series().length > 1;
    return {
      label: this.labels()[index] ?? '',
      anchor: arenaTooltipAnchor(tip.x, tip.y),
      readings: this.series().flatMap((one, s) => {
        const value = one.values[index];
        if (value === undefined) return [];
        return [{ key: s, name: many ? `${one.label}: ` : '', value: write(value) }];
      }),
    };
  });

  protected onPointer(event: PointerEvent, phase: string): void {
    if (!arenaPointerUpdates(event.pointerType, phase)) return;
    const box = (event.currentTarget as SVGRectElement).ownerSVGElement?.getBoundingClientRect();
    if (!box) return;
    const index = arenaPolarIndex(this.centreX(), this.centreY(),
      event.clientX - box.left, event.clientY - box.top, this.axes());
    if (index >= 0) this.hover.set(index);
  }

  protected onPointerLeave(event: PointerEvent): void {
    if (arenaPointerClears(event.pointerType)) this.hover.set(null);
  }

  protected onKey(event: KeyboardEvent): void {
    if (!arenaCursorHandles(event.key, 'x')) return;
    event.preventDefault();
    this.hover.set(arenaCursorStep(this.hover(), event.key, this.axes(), 'x'));
  }
}
