// frameworks/react/components/feedback/arena-spinner/ArenaSpinner.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaSpinner.classes.generated.ts';

import type { ArenaControlSize, ArenaSpinnerTone } from '../../../Api.generated';

export interface ArenaSpinnerProps {

  /** Diameter. 'sm' is --icon-sm exactly, so a spinner at that size sits inline with control text. */
  size?: ArenaControlSize;

  /** Colour of the ring. 'on-accent' inside a filled button; 'accent' on a page surface. */
  tone?: ArenaSpinnerTone;

  /** Accessible name, announced by the status role. Say what is loading when you can. */
  label?: string;
}


const arenaSpinnerStyles = arenaStyles(manifest);

export function ArenaSpinner({ size = 'md', tone = 'accent', label = 'Loading' }: ArenaSpinnerProps) {
  const styles = arenaSpinnerStyles({ size, tone });
  return (
    <span role="progressbar" aria-live="polite" aria-label={label} className={styles.root()} data-arena-part={manifest.parts.root}>
      <span className={styles.circle()} data-arena-part={manifest.parts.circle} aria-hidden="true" />
    </span>
  );
}

// frameworks/angular/components/feedback/arena-spinner/ArenaSpinner.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import type { ArenaControlSize, ArenaSpinnerTone } from '../../../Api.generated';
import { arenaSpinnerStyles } from './ArenaSpinner.variants';
import manifest from './ArenaSpinner.classes.generated';

@Component({
  selector: 'arena-spinner',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.data-arena-part]': 'parts.root',
    role: 'progressbar',
    'aria-live': 'polite',
    '[attr.aria-label]': 'label()',
  },
  template: `<span [class]="styles().circle()" [attr.data-arena-part]="parts.circle" aria-hidden="true"></span>`,
})
export class ArenaSpinner {
  protected readonly parts = manifest.parts;

  /** Diameter. 'sm' is --icon-sm exactly, so a spinner at that size sits inline with control text. */
  readonly size = input<ArenaControlSize, ArenaControlSize | undefined>(
    'md',
    { transform: (value) => value ?? 'md' },
  );
  /** Colour of the ring. 'on-accent' inside a filled button; 'accent' on a page surface. */
  readonly tone = input<ArenaSpinnerTone, ArenaSpinnerTone | undefined>(
    'accent',
    { transform: (value) => value ?? 'accent' },
  );
  /** Accessible name, announced by the status role. Say what is loading when you can. */
  readonly label = input<string, string | undefined>('Loading', { transform: (value) => value ?? 'Loading' });

  protected readonly styles = computed(() => arenaSpinnerStyles({ tone: this.tone(), size: this.size() }));
}
