// frameworks/react/components/layout/arena-site-footer/ArenaSiteFooter.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaSiteFooter.classes.generated.ts';

export interface ArenaSiteFooterProps {

  /** The columns, one per child, laid out by a grid that decides its own count from the room it is given rather than from a breakpoint anyone picked. A column of links, a signup, an address and a mark all land the same way. */
  children?: React.ReactNode;

  /** The line under the columns, in the muted ink: the licence, the year, the company. Absent, the footer renders no line at all rather than an empty one. */
  note?: string;
}

const arenaSiteFooterStyles = arenaStyles(manifest);
const TRACKS = 'repeat(auto-fit, minmax(min(var(--grid-min), 100%), 1fr))';
const PAGE = 'var(--container-max)';

export function ArenaSiteFooter({ children, note }: ArenaSiteFooterProps) {
  const styles = arenaSiteFooterStyles();

  return (
    <footer className={styles.root()} data-arena-part={manifest.parts.root}>
      <div className={styles.band()} data-arena-part={manifest.parts.band} style={{ maxWidth: PAGE }}>
        {children && (
          <div className={styles.columns()} data-arena-part={manifest.parts.columns} data-arena-boundary="" style={{ gridTemplateColumns: TRACKS }}>{children}</div>
        )}
        {note && <p className={styles.note()} data-arena-part={manifest.parts.note}>{note}</p>}
      </div>
    </footer>
  );
}

// frameworks/angular/components/layout/arena-site-footer/ArenaSiteFooter.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { arenaSiteFooterStyles } from './ArenaSiteFooter.variants';
import manifest from './ArenaSiteFooter.classes.generated';

const TRACKS = 'repeat(auto-fit, minmax(min(var(--grid-min), 100%), 1fr))';
const PAGE = 'var(--container-max)';

@Component({
  selector: 'arena-site-footer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <footer [class]="styles().root()" [attr.data-arena-part]="parts.root">
      <div [class]="styles().band()" [attr.data-arena-part]="parts.band" [style.maxWidth]="page">
        <div [class]="styles().columns()" [attr.data-arena-part]="parts.columns" data-arena-boundary [style.gridTemplateColumns]="tracks"><ng-content /></div>
        @if (note(); as line) { <p [class]="styles().note()" [attr.data-arena-part]="parts.note">{{ line }}</p> }
      </div>
    </footer>
  `,
})
export class ArenaSiteFooter {
  protected readonly parts = manifest.parts;

  /** The line under the columns, in the muted ink: the licence, the year, the company. Absent, the footer renders no line at all rather than an empty one. */
  readonly note = input<string>();

  protected readonly tracks = TRACKS;
  protected readonly page = PAGE;
  protected readonly styles = computed(() => arenaSiteFooterStyles());
}
